### ISSUE TITLE
AR render looks unstable

### ISSUE THREAD

**Issue by Parikshit-Hooda** [hiukim/mind-ar-js#102]
I tried on the project's [Try-on](https://hiukim.github.io/mind-ar-js-doc/face-tracking-samples/tryon.html) feature. I found the below issues with the AR render on my laptop's in-built camera. 
- The objects render look unstable. By unstable, I mean that they are constantly calibrating their size and position even when the Subject/Anchor(my face in this case) is not moving at all. 
- Also, there seems to be a time lag between the calibration of AR objects and the Subject. 

**Laptop specs: HP Pavilion 15, 2016.**

**Comment by grimdeathr** [comment]
Same for me on my gaming PC. 
Even through a virtual webcam the tracking is really slow.

Also slow on ios and android

**Comment by hiukim** [comment]
Face Tracking has been improved in the latest release.
