### ISSUE TITLE
Decouple ThreeJS from MindAR

### ISSUE THREAD

**Issue by Blitzy** [hiukim/mind-ar-js#104]
The Three.js variants of the MindAR library are including Three.js in the bundle. Three.js should instead be left as an external dependency of MindAR. As of writing, MindAR is inextricably tied to a bundle version of Three.js r132.

**Comment by hiukim** [comment]
@Blitzy That's a very good point! 

but I couldn't figure out a way to decouple it without losing the high level API. The raw tracking part is independent of THREE.js, but people will need to write a lot more code to get a working application.

Welcome any suggestions.

**Comment by Blitzy** [comment]
In the simplest form you could just make Three.js an external dependency in the weback configs.

https://webpack.js.org/configuration/externals/

This would allow users of MindAR to provide their own copy of Three.js and allow them to use updated versions of Three.js as they release quite frequently. It also allows you to keep doing the Three.js specific things that are being done.

However, I would not recommend relying on Three.js at all and simply have some sort of output pipe for the anchor transforms/matrices from MindAR that can be applied directly to whatever objects the devs want to apply it too. This is cleaner and keeps MindAR closer to a dependency-free utility API instead of its own rendering framework. It also lets author's setup Three.js the way they want/need to for their project. 

Obviously just making Three an external dependency in webpack is the shortest path 😋

**Comment by Makio64** [comment]
I run into the same problem, the solution is pretty basic : 
copy the class in your repertory : MindARThree.

in your main.js
``` 
import MindARThree from './MindARThree'
```

replace the top part of MindARThree by : 
```
import * as MindAR from 'mind-ar/dist/mindar-image.prod'
import { PerspectiveCamera, Quaternion, Group, sRGBEncoding, WebGLRenderer, Scene, Matrix4, Vector3 } from 'three';
const {CSS3DRenderer} = require('three/examples/jsm/renderers/CSS3DRenderer.js');

 // for some reason MindAR return an empty object but this window is not empty..
const Controller = window.MINDAR.IMAGE.Controller
const UI = window.MINDAR.IMAGE.UI 

const cssScaleDownMatrix = new Matrix4();
cssScaleDownMatrix.compose(new Vector3(), new Quaternion(), new Vector3(0.001, 0.001, 0.001));

class MindARThree {
  constructor({container, imageTargetSrc, maxTrack, captureRegion=false, uiLoading="yes", uiScanning="yes", uiError="yes"}) {
 ```

Done.

Notice : we load mindar-image.prod and not the mindar-image-three.prod ;)

**Comment by hiukim** [comment]
@Blitzy 

In the latest release, I've decoupled the threejs code as much as possible. Now only two files require threejs `https://github.com/hiukim/mind-ar-js/blob/master/src/image-target/three.js`
`https://github.com/hiukim/mind-ar-js/blob/master/src/face-target/three.js`

I also tried to make the dependency `external` as you suggested, but without success. Do you want to give it a shot?

**Comment by Makio64** [comment]
I also gave a try on externals but it was not working if three wasnt imported at the top script.

**Comment by Makio64** [comment]
I think the best architecture woud be like threejs "examples" where peoples can go in and take what they want :)

**Comment by Makio64** [comment]
My solution here work with the latest version of threejs : https://github.com/hiukim/mind-ar-js/issues/104#issuecomment-1019562231 
The only things, the developer have to embed Threejs by themself but with a good "how to" it will not be a problem for the the peoples who want this level of control.

Also I think its a bit similar to the solution offer by Jeeliz library and his JeelizThreeHelper.

**Comment by FiltrosInsta** [comment]
Hello @hiukim, thanks for your great contribution to the WebAR world!!

Would you know how to rotate the camera to see it upside down just like Instagram?

**Comment by uyendo-vn-tmrw** [comment]
> 

I have a problem same you

**Comment by eaallen** [comment]
> Hello @hiukim, thanks for your great contribution to the WebAR world!!
> 
> Would you know how to rotate the camera to see it upside down just like Instagram?

This question belongs in it own thread. But here is a CSS solution
`video {
  -webkit-transform: scaleX(-1);
  transform: scaleX(-1);
}`
I got this from a classic stackoverflow search: https://stackoverflow.com/a/50176947/15034002

**Comment by Eisenh** [comment]
I would love a way to get the canvas coordinates and pose of the matched image before invoking Three.js. in fact, I have ise cases that do not need three.ja or any AR. Simply being able to create and track an arbitrary image is important for more than AR.

**Comment by forerunrun** [comment]
> I run into the same problem, my solution is basic : copy the class in your repertory : MindARThree.
> 
> in your main.js
> 
> ```
> import MindARThree from './MindARThree'
> ```
> 
> replace the top part of MindARThree by :
> 
> ```
> import * as MindAR from 'mind-ar/dist/mindar-image.prod'
> import { PerspectiveCamera, Quaternion, Group, sRGBEncoding, WebGLRenderer, Scene, Matrix4, Vector3 } from 'three';
> const {CSS3DRenderer} = require('three/examples/jsm/renderers/CSS3DRenderer.js');
> 
>  // for some reason MindAR return an empty object but this window is not empty..
> const Controller = window.MINDAR.IMAGE.Controller
> const UI = window.MINDAR.IMAGE.UI 
> 
> const cssScaleDownMatrix = new Matrix4();
> cssScaleDownMatrix.compose(new Vector3(), new Quaternion(), new Vector3(0.001, 0.001, 0.001));
> 
> class MindARThree {
>   constructor({container, imageTargetSrc, maxTrack, captureRegion=false, uiLoading="yes", uiScanning="yes", uiError="yes"}) {
> ```
> 
> Done.
> 
> Notice : we load mindar-image.prod and not the mindar-image-three.prod ;)

Hi @Makio64 do you have a more detailed insight into how you're doing this? The instructions here are a little confusing for me, do you happen to have a live example showing how you've implemented the code in full?

**Comment by amcc** [comment]
Using v1.2.0 installation instructions i'm getting this error:

``` 
No matching export in "node_modules/three/build/three.module.js" for import "sRGBEncoding"

node_modules/mind-ar/dist/mindar-image-three.prod.js:1:91:
      1 │ ...Se, Quaternion as Qt, Scene as Ct, WebGLRenderer as Ti, sRGBEncoding as Si, PerspectiveCamera as vi, Group as zt } from "thr...
        ╵  
```
package.json versions
"mind-ar": "^1.2.5"
"three": "^0.173.0"

i've not implemented anything yet, just imported this at the top of my file:
```
import { MindARThree } from "mind-ar/dist/mindar-image-three.prod.js";
```

**Comment by dogzilla** [comment]
Has this issue been resolved or does MindAR still have a dependency on threejs r160? When I change my imports to r173 then loading fails with MindAR v1.2.5. Is there a working example of loading latest threejs or does it depend on using the hacks above?

**Comment by amcc** [comment]
Even using the above suggestions I couldn't get this to work

**Comment by amcc** [comment]
if there's no objection i might start a new issue around this as currently i don't think the latest three (or even using the version supplied with mind-ar) is working with the suggested install instructions - i'll see if anyone replies to this, otherwise i'll go ahead. I think the faults i'm seeing is related to decoupling, but could perhaps be a whole other thing
