### ISSUE TITLE
error on more than 2 image target

### ISSUE THREAD

**Issue by PersianCoders** [hiukim/mind-ar-js#11]
hello dear
when i add more than 2  image for compile, and when i add targets.mind to project.
project not run and show loading...

please help me to solve the problem.

**Comment by hiukim** [comment]
There is an example of 2 image targets, https://hiukim.github.io/mind-ar-js/samples/example2.html

You can first check whether this works for you.

**Comment by PersianCoders** [comment]
> There is an example of 2 image targets, https://hiukim.github.io/mind-ar-js/samples/example2.html
> 
> You can first check whether this works for you.

yes,i check it , when i set it for 3 or more image target, not work

**Comment by hiukim** [comment]
any console log?
