### ISSUE TITLE
RangeError

### ISSUE THREAD

**Issue by anishjiben** [hiukim/mind-ar-js#112]
HI,
I am getting RangeErrror:Extra 3679 byte(s) found at buffer[1]. Attached the screenshot of the error.
![image](https://user-images.githubusercontent.com/30341338/150718104-065c982c-59d6-4a24-8e1b-69fd175465c4.png)

Here is my code
![image](https://user-images.githubusercontent.com/30341338/150719862-370d89c5-df00-4253-8127-9836085d8b10.png)

function loadMarkers() {
	imageSample = "imageTargetSrc: " + "url to .mind";
	var sceneNode = document.getElementById("#scene");
	sceneNode.setAttribute("mindar-image", imageSample);
}

Any Idea why this error appears ? 
Thank you

**Comment by hiukim** [comment]
What's the purpose of using`loadMarkers` method to add this `mindar-time` attritube?

I'm not sure this will work. AFRAME might have already initialized.

**Comment by hiukim** [comment]
closing it now. feel free to reopen if you have more information.
