### ISSUE TITLE
Question: QR Code + Dynamic a-entity creation

### ISSUE THREAD

**Issue by dehenne** [hiukim/mind-ar-js#113]
Hi,

first of all thank you for the great tool. 🙏

I have a question. Is it possible to read a QR code, use this data and then dynamically create an a-entity, so that mindAR can then read and understand it?

My problem is, I have more than 200k items that I would like to offer as AR. The test worked without a problem.
But I want to create 200k a-entity elements so that all of them are recognized. I think technically this is not great for the performance.

Therefore my idea, in the QR code are some data contained, in which I know, which a-entity I have to create. 
some solutions say to place custom codes IN the QR code, which does not solve my problem of over 200k items.

does anyone have experience what the maximum of items is?

would be happy to hear about solutions :-)

best regards
Hen

**Comment by hiukim** [comment]
@dehenne 
I would say a practical limit is around 10 markers. 

I think that's a smart solution to use a preliminary step (in your case QR code) to filter out the one you want and then start the tracking.

Unfortunately, there is no built-in support for this use case. But I'd say it's definitely possible to do. I guess you have two options:

1. hack the source and compile a custom version of the library
2. To use the current release of the library, compile your 200k markers independently and dynamically load and trigger one of them at a time. It might be easier to start with the three.js example
