### ISSUE TITLE
Images not recognized

### ISSUE THREAD

**Issue by nicolasdekaise** [hiukim/mind-ar-js#116]
Hi,

I've used the image target compiler and some images I use worked in the minimal example, but other did'nt. ^^'

What are the guidelines to make a good image to be recognized ?

Thanks !

**Comment by Makio64** [comment]
in the official doc of mind-ar you have this very useful link : 
https://blog.pictarize.com/how-to-choose-a-good-target-image-for-tracking-in-ar-part-1/
