### ISSUE TITLE
Links to websites not working

### ISSUE THREAD

**Issue by offscreenworld** [hiukim/mind-ar-js#124]
Hi there, first of all thank you for developing such a great bit of kit.

I'm trying to adapt the interactive business card example, however I cannot get the links to open either on your live demo or on my own project. I'm using an iPhone 7 if that's any insight.

I found some suggestions to move the icons/buttons away from the middle of the screen so I put them under the portfolio arrows, still not avail. 

Any help or thoughts would be greatly appreciated.

Cheers,
M

**Comment by offscreenworld** [comment]
I realise now that the icons update the bar at the bottom. My bad, however, do you have any reccomendations for where to look regarding turning them into 'open link in new tab' events

**Comment by hiukim** [comment]
You can try `window.open(XXX, "_blank")`

**Comment by offscreenworld** [comment]
Thanks a lot this worked
