### ISSUE TITLE
image compiler tool not working

### ISSUE THREAD

**Issue by devhims** [hiukim/mind-ar-js#13]
Hi @hiukim, I've tried a couple of images before trying out the default `card.png` that is provided with the repo. In all the cases, the generated `.mind` file isn't getting recognized. I also noticed `2 KB` size difference in the `card.mind` that's included in the example and the one I generate with the same image. 

Here is one of my images: 

![ww](https://user-images.githubusercontent.com/17825870/110251018-7dfc8f80-7fa4-11eb-9155-32ab9526027a.jpg)

**Comment by hiukim** [comment]
@devhims Are you using the latest version of the library? Both for compile and recognize.  I just pushed an update yesterday.

**Comment by devhims** [comment]
Thanks for the prompt reply @hiukim. Yes, I was using the older version of the library. 
All sorted now. Loving the new UX upgrades.  ✌️

**Comment by hiukim** [comment]
Nice!
