### ISSUE TITLE
Question : Does Mind-AR has a React Module?

### ISSUE THREAD

**Issue by krsbx** [hiukim/mind-ar-js#131]
As the title said, at the moment does Mind AR has a React Module?
If we dont have it, then i'm willingly to made one

**Comment by krsbx** [comment]
@hiukim can you have a look on this module that i made https://github.com/krsbx/mind-ar-react

**Comment by hiukim** [comment]
@krsbx Thanks for creating this!

There is no React Module at the moment. I do have written a simple React example long time ago. https://github.com/hiukim/mind-ar-js-react But It merely just shows people how to dynamically render a mindar aframe scene in a component. 

Yours is definitely more structural! :)

**Comment by krsbx** [comment]
@hiukim thank you very much, but too bad for the face tracking one my device is not supported, so i can't really test the module for the face tracking
