### ISSUE TITLE
Shaking problem

### ISSUE THREAD

**Issue by ironblaster** [hiukim/mind-ar-js#132]
hi, I'm new to the AR world, and I'm trying to use the simple versions of your code, in particular I'm using the one that is present in the Readme (QUICKSTART)
the system works well but even with fixed webcam and sheet supported the 3d image continues to vibrate.
can you advise me something?
maybe I haven't found some particular function?
there is a way to set the fps to increase it on cameras to 60fps

**Comment by AIxndr** [comment]
I am neither experienced. But did you try to use the tracking config as described here https://hiukim.github.io/mind-ar-js-doc/quick-start/tracking-config ?

**Comment by fourthedesign** [comment]
I tried modifying the filterMinCF and filterBeta values, but the object in AR on mobile device is extremely shaky. Is there anything else I can do?

**Comment by Nikozil** [comment]
Hello my friends.
I spent a lot of time on this problem. The following configuration oneEuroFilter worked for me:

<a-scene mindar-image="filterMinCF:0.0001; filterBeta: 0.001"/>

It would be great to set it or a working analogue as the default.

**Comment by ironblaster** [comment]
> 

i don't see  your configuration

**Comment by Nikozil** [comment]
Sorry, I forgot to format the string. Now it is visible.

**Comment by ompateldeveloper** [comment]
This is for THree js people
const mindarThree = new MindARThree({
            container: document.body,
            imageTargetSrc:"./targets.mind",
            filterMinCF:0.0001,
            filterBeta:0.001
        });

**Comment by maxrpark** [comment]
> This is for THree js people const mindarThree = new MindARThree({ container: document.body, imageTargetSrc:"./targets.mind", filterMinCF:0.0001, filterBeta:0.001 });

Thanks!
