### ISSUE TITLE
Clickable item remain clickable after the target is lost

### ISSUE THREAD

**Issue by gabdanGraldev** [hiukim/mind-ar-js#133]
After a target containing a clickable object is lost, the area is still clickable and the action associated with the click is performed.
![1d](https://user-images.githubusercontent.com/100126948/154937624-32c5acac-7847-4182-bda0-b781c8e3bb3d.jpg)
![2d](https://user-images.githubusercontent.com/100126948/154937634-95c4ebbd-dac7-4ed9-ad1d-84f93169fc31.jpg)

**Comment by hiukim** [comment]
haha, nice spot. Right now, the contents are simply set to `invisible`. I guess that might be the reason.

**Comment by villelahdenvuo** [comment]
Also it seems to me like click events are not working properly with multiple targets.

**Comment by ArtemOstapov** [comment]
> After a target containing a clickable object is lost, the area is still clickable and the action associated with the click is performed. ![1d](https://user-images.githubusercontent.com/100126948/154937624-32c5acac-7847-4182-bda0-b781c8e3bb3d.jpg) ![2d](https://user-images.githubusercontent.com/100126948/154937634-95c4ebbd-dac7-4ed9-ad1d-84f93169fc31.jpg)

Could you plz share your example with clicking on the video?
Wanna to add play/pause btn on video appeared on target, but still failed

**Comment by ArtemOstapov** [comment]
hi, @hiukim, tell me plz if it possible to have clickable play/pause btn on video appeared on a target? and on multiple targets?
and if yes could you plz share such example?
tnx

**Comment by hiukim** [comment]
@ArtemOstapov Yes, I think you can do that. It's not really related to the AR, more on general web development. You can implement some toggle buttons and programming logic to control the videos.

**Comment by ArtemOstapov** [comment]
> @ArtemOstapov Yes, I think you can do that. It's not really related to the AR, more on general web development. You can implement some toggle buttons and programming logic to control the videos.

@hiukim, tnx for the quick answer, there is one your example from your github that is very interested for me, and it has play btn on the video and also btns left/right, could you plz share it?
that is the link to it:
https://hiukim.github.io/mind-ar-js-doc/examples/interative

**Comment by hiukim** [comment]
@ArtemOstapov yes, sure. view-source:https://hiukim.github.io/mind-ar-js-doc/samples/advanced.html

**Comment by ArtemOstapov** [comment]
> @ArtemOstapov yes, sure. view-source:https://hiukim.github.io/mind-ar-js-doc/samples/advanced.html

tnx, for your answer, HiuKim, I think here I got problem with React... im doing it in React and clicks do not work, and in simple html - they work...

There is an issue on stackoverflow, could you plz take a look on it?

[https://stackoverflow.com/questions/71663554/how-do-i-keep-react-from-stripping-a-frame-attributes](url)

**Comment by ArtemOstapov** [comment]
@hiukim, tnx, i solved my issue, it was because of  a-frame vs React incompatibility.

**Comment by metaColin** [comment]
Has this been addressed?

I am working on a project with multiple image targets, but for some reason the first target in the 'targets.mind' array remains is the one that gets clicked regardless of which target is visible on screen.

**Comment by jessicachrist** [comment]
> > Also it seems to me like click events are not working properly with multiple targets.
> 
> Has this been addressed?
> 
> I am working on a project with multiple image targets, but for some reason the first target in the 'targets.mind' array remains is the one that gets clicked regardless of which target is visible on screen.

@metaColin Have you found a solution?

**Comment by hiukim** [comment]
fixed in v1.2.1
