### ISSUE TITLE
Preview button start video on target image bug with multi-target.

### ISSUE THREAD

**Issue by gabdanGraldev** [hiukim/mind-ar-js#134]
With multi-target, positioning the preview start video button above the target image, it is not possible to press other clickable objects but only the start video button.
Specifically, the DOM object begins with the a-mouse-cursor-hover class even if the cursor is not positioned on a clickable object and remains so until a second target is framed.
In the attached photo you can see the mouse not positioned on a clickable object, but clicking triggers the event anyway, without the possibility of clicking on other clickable objects.
![3d](https://user-images.githubusercontent.com/100126948/154949129-d272147b-e403-4994-960f-841e93eb1686.jpg)

**Comment by hiukim** [comment]
Do you have a testable app online?

**Comment by JamesBotterill** [comment]
I have this issue too, I've worked around it in the short term but it would be good to understand how to fix it

**Comment by JamesBotterill** [comment]
I've been looking at this today and the behaviour is very strange. 

* sometimes I can interact with preview button but this is not 100% and is very hit and miss
* I think this may be more of an issue with conflicts with raycasting

**Comment by hiukim** [comment]
stale. feel free to re-open if there is new insight.
