### ISSUE TITLE
TypeError: this.controller is undefined

### ISSUE THREAD

**Issue by wuiyang** [hiukim/mind-ar-js#135]
In the [events example](https://hiukim.github.io/mind-ar-js-doc/samples/events.html), after pressing "start" without giving camera permission, and then pressing "stop", receives `this.controller is undefined` error.

https://github.com/hiukim/mind-ar-js/blob/7dee01e2a31a2b05ea2465c52529a3add5a2e863/src/image-target/aframe.js#L61

**Comment by hiukim** [comment]
thx for reporting. will fix it.
