### ISSUE TITLE
How to change the resolution of the source?

### ISSUE THREAD

**Issue by giaaaacomo** [hiukim/mind-ar-js#139]
hi! i've tried to use the same code i used in ar.js ( `sourceWidth:2560; sourceHeight:1920; displayWidth: 2560; displayHeight: 1920;` ) but it doesn’t seem to work. is there a way to set a custom resolution, or use by default the maximum supported by the camera?

**Comment by hiukim** [comment]
We are only using the default now: https://github.com/hiukim/mind-ar-js/blob/c39c9e4f4a289b924b1a90c6a3eb72fc8df990ca/src/image-target/aframe.js#L88

I haven't really studied on this issue. Do you know what is default resolution, if not maximum?  Do you have any proposed changes?

**Comment by Nikozil** [comment]
Hello.
You can specify your preferred resolution in the video parameters "getUserMedia".

In my case, I compiled a library build with the following parameters:
```
video: {
      facingMode: 'environment',
      width: {ideal: 1280},
      height: {ideal: 720}
    }
```
It would be great to be able to specify these parameters in <a-scene/>
Reference: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia

**Comment by giaaaacomo** [comment]
> Hello. You can specify your preferred resolution in the video parameters "getUserMedia".
> 
> In my case, I compiled a library build with the following parameters:
> 
> ```
> video: {
>       facingMode: 'environment',
>       width: {ideal: 1280},
>       height: {ideal: 720}
>     }
> ```

sry but i don't understand how could i implement that, could you explain further?

> It would be great to be able to specify these parameters in `<a-scene/>`

@hiukim this would be a really welcome change

**Comment by giaaaacomo** [comment]
> Hello. You can specify your preferred resolution in the video parameters "getUserMedia".
> 
> In my case, I compiled a library build with the following parameters:
> 
> ```
> video: {
>       facingMode: 'environment',
>       width: {ideal: 1280},
>       height: {ideal: 720}
>     }
> ```
> 
> It would be great to be able to specify these parameters in `<a-scene/>` Reference: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia

found out that i had to add width and height to mindar-image.prod.js but for some reason it doesn't work for me, and i get 
`Uncaught TypeError: Cannot read properties of undefined (reading 'IMAGE')
    at altmindar.js:2:52
    at altmindar.js:182:3

Uncaught TypeError: Cannot read properties of undefined (reading 'IMAGE')
    at mindar-image-aframe.prod.js:1:46
    at mindar-image-aframe.prod.js:1:5793

Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.`

**Comment by Nikozil** [comment]
1.  Clone the mind-ar-js repository on your pc
2.  After `  navigator.mediaDevices.getUserMedia({audio: false, video: {
      facingMode: 'environment',` write `width: {ideal: 1280},
      height: {ideal: 720}`
3. Use `npm i ` and `npm run build` in cmd
4. In 'dist' directory will contain your own build

**Comment by giaaaacomo** [comment]
> 1. Clone the mind-ar-js repository on your pc
> 2. After https://github.com/hiukim/mind-ar-js/blob/c39c9e4f4a289b924b1a90c6a3eb72fc8df990ca/src/image-target/aframe.js#L88,L89 write `width: {ideal: 1280}, height: {ideal: 720}`
> 3. Use `npm i ` and `npm run build` in cmd
> 4. In 'dist' directory will contain your own build

thanks!
