### ISSUE TITLE
setting a react starter project with mind-ar-js

### ISSUE THREAD

**Issue by devhims** [hiukim/mind-ar-js#14]
Hi @hiukim, I challenged myself to use your library in a React project. I used jsDeliver to host the library on a CDN. And then created a component with the source code of example 1 from this repo. Unfortunately, I didn't succeed and got the following error:

<img width="1440" alt="Screenshot 2021-03-10 at 12 07 28 AM" src="https://user-images.githubusercontent.com/17825870/110521221-7a4c4280-8135-11eb-81d0-10d240da8f25.png">

Any tips to tackle this? 🙂
You can find my repo [here](https://github.com/devhims/mind-ar-examples).

**Comment by hiukim** [comment]
@devhims 
It might not be related to this issue, but you probably also need to host the `controller.worker.prod.js` in cdn, next to the `mindar.prod.js`

didn't reveal much information from the log. Maybe you can try using a development build instead so we have more information.  clone the repo and run `npm run watch`, the build will appeared in `dist-dev`

**Comment by devhims** [comment]
I tried hosting the 50MB development build on jsDeliver CDN, but it's failing. Anyway, do you plan to release the library as an NPM package? That would be immensely helpful.

**Comment by hiukim** [comment]
@devhims Yes, will definitely make npm package later.

I guess you can try running your repo just locally with the development build and see the error?

**Comment by devhims** [comment]
@hiukim Apart from an npm package, the only other way I know to include an external library is through a CDN. That approach didn't work with the development build as mentioned in the previous comment. If you've any other workaround, I'm willing to give that a try. 

Also, are you active on LinkedIn? I'll tag you in my next post about a demo I created with this library.

**Comment by hiukim** [comment]
@devhims Thanks for reaching out. Just added you in LinkedIn.

I will probably publish an npm package soon. and allow it to be used in React also seems important. So if you are not in particular hurry, I can probably work on that.

I was occupied writing up the documentation before. But it's done now! (do check it out :), so I'll probably have some time on this matter.

**Comment by devhims** [comment]
Awesome work on the documentation @hiukim! I really like your writing because it feels less mechanical and more human. I noticed the same while going through the README. :)

One reason, I got excited about your library is that I'm also working on a React project which simplifies 3d view and AR with model viewer web component. Currently, image tracking is not available with model viewer and is also not in their pipeline, so I was looking for an alternative. Between Ar.js and your library, I found your README instructions much easier to get started with and the demos seemed quite promising. And I must admit, the idea of an independent developer creating useful tools for others is massively inspiring to me. 

Once you make the NPM package, I'll add examples for Image tracking based on your library. There is no rush, you can take your time. ✌️

**Comment by hiukim** [comment]
haha. thx.  Yes, let's all show our respects to Linus.

Yeah, I'd definitely love to see more works based on this library. Please share with us whenever you have something. :)

**Comment by devhims** [comment]
Sure, I'll tag you when I post the demo on LinkedIn. Btw who is Linus?

**Comment by hiukim** [comment]
I mean Linus Torvalds, haha.

**Comment by hiukim** [comment]
just published a npm package. https://www.npmjs.com/package/mind-ar

Also created a React and npm example here: https://github.com/hiukim/mind-ar-js-react

**Comment by kalwalt** [comment]
> just published a npm package. https://www.npmjs.com/package/mind-ar
> 
> Also created a React and npm example here: https://github.com/hiukim/mind-ar-js-react

Super @hiukim !! Really awesome!💯💥🎉
