### ISSUE TITLE
Question : face-tracking-assigment not working on pi4 

### ISSUE THREAD

**Issue by heoyongun** [hiukim/mind-ar-js#141]
I want use, this example on pi4([pisignage](http://pisignage.com/))

example url is [face-tracking-assigment](https://hiukim.github.io/mind-ar-js-doc/face-tracking-samples/tryon.html)

1. camera ready, ok
2. debugger, error message not found. 
3. but not working AR

**Comment by hiukim** [comment]
Hi, I'm not familiar with pi4. If you have more information, I might be able to provide some insights, but I'm not sure.

**Comment by heoyongun** [comment]
I ran a few tests, but failed.

There was not enough time to solve the problem.

I decided to give up and use other equipment.

It works fine on x86.

The issue will end.

Thanks for the great library.
