### ISSUE TITLE
Feature Request : Option to switch between cameras for Image detection as well

### ISSUE THREAD

**Issue by pranavps020** [hiukim/mind-ar-js#142]
Currently only face detection variant have the camera switching feature, I think It's good to have it for Image detection as well.

**Comment by hiukim** [comment]
It's definitely doable.  Curious about what's the use case though?

**Comment by akhrarovsaid** [comment]
I can see this as a useful feature. Say for example an AR experience using a tshirt design as a marker? 

Seems like a simple one/two liner to implement. I can do a PR when I find the time. 👍

**Comment by hiukim** [comment]
@akhrarovsaid sounds good. Thanks!

**Comment by ismaelash** [comment]
> I can see this as a useful feature. Say for example an AR experience using a tshirt design as a marker?
> 
> Seems like a simple one/two liner to implement. I can do a PR when I find the time. 👍

This feature has implemented?

**Comment by hiukim** [comment]
Implemented in the latest version - ThreeJS version only though
