### ISSUE TITLE
OrbitControls issue

### ISSUE THREAD

**Issue by Anulo2** [hiukim/mind-ar-js#143]
Hi everyone, I was looking into adding orbit controls to the camera but It seems like this feature from three js is incompatible with mind ar. Do you have any tips on what I should try or if this is intentional? You can take a look at my code here: https://gitlab.com/_Zaizen_/mind-ar-orbit-controls

**Comment by hiukim** [comment]
I think the way OrbitControls works is by update the camera rotation/position. MindAR also needs direct control over the camera, so they have conflict.

**Comment by adilsonv77** [comment]
Hello... Is there any alternative im MindAR to the user control rotation and zooming the camera?
