### ISSUE TITLE
Wechat compatibility

### ISSUE THREAD

**Issue by grimdeathr** [hiukim/mind-ar-js#144]
Hi, this sort of works on wechat. Can't bring the camera image up but the rest looks like its there and my ios device shows my camera is on, but no image is shown

Was wondering if you had tested it on there?

**Comment by hiukim** [comment]
I have never tried on wechat. If you have more information, e.g. error logs, it can gives us more insights.

**Comment by Makio64** [comment]
If its on iOS < 14.x webwiew doesnt support webworker. 
In iOS >14.x webworker are supported but limitated to "trusted source" defined by the app. I guess thats what its not working in the wechat webview.
