### ISSUE TITLE
black bars on ios, safari

### ISSUE THREAD

**Issue by fourthedesign** [hiukim/mind-ar-js#145]
Hello, there are some gaps on the left side edge and on the bottom edge. Safari is the only browser i can see this bug happening.
Does anyone have a way to fix it? I tried even with the image-tracking examples.
Here is an example of said bars.
![Inkedhttpsstasishellas grWebAR2ar html_LI](https://user-images.githubusercontent.com/99669150/158182086-b417e0ff-2ca1-4dbc-ac85-f11dedc0abd7.jpg)
Thank you!

**Comment by hiukim** [comment]
@fourthedesign 
I can't replicate this issue. Which example were you trying? this one: https://hiukim.github.io/mind-ar-js-doc/examples/basic/?

What iOS device are you using? and what iOS version?
