### ISSUE TITLE
triggering audio play/pause when target is found/lost respectively

### ISSUE THREAD

**Issue by devhims** [hiukim/mind-ar-js#15]
I'm trying to use the `targetFound` and `targetLost` events to play/pause an audio clip. But even with autoplay set to false, I get the following message in the console as soon as the application is loaded. Any workaround to fix this? 

`The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. `

**Comment by devhims** [comment]
Spoke too soon, I guess. Although I do get the warning, still the audio play/pause works fine.

**Comment by devhims** [comment]
Doesn't work on iOS though. In Android/macOS testing it worked fine.

**Comment by PedroNan** [comment]
Could it work to pause or play a video? Do you have examples of the code you used? greetings.
