### ISSUE TITLE
Unable to detect image tracking on iPhone XS

### ISSUE THREAD

**Issue by JamesBotterill** [hiukim/mind-ar-js#151]
I'm attempting to track an imagine using my iPhone XS Max device and having no success.

When I attempt on my Mac it detects it almost instantly.

Is this a setting I can adjust for?

**Comment by pedrorocha-net** [comment]
@JamesBotterill Iphone XS Mac should work. Can you please give more details on how and what have you tried? Do you have a link for the app and the image you're using?
What browser did you use?

**Comment by JamesBotterill** [comment]
It was safari, it's working better now. 

It seems quite random why it's working now and wasn't yesterday.

**Comment by pedrorocha-net** [comment]
Sometimes the luminosity of the environment makes a huge difference to me as well, alongside the quality of the image itself. Unfortunately, it's part of working with AR..hehe
