### ISSUE TITLE
Bug: cannot start the face tracking in React

### ISSUE THREAD

**Issue by krsbx** [hiukim/mind-ar-js#152]
I try to make the Face tracking wrapper for the [Mind AR React](https://github.com/krsbx/mind-ar-react)
When I try to start the face tracking with this code:
![image](https://user-images.githubusercontent.com/21305278/161013959-a72d3625-3e4e-4d42-aa52-9dbac9cacf5d.png)
It show an error like this:
![2022-03-31_15-36-51](https://user-images.githubusercontent.com/21305278/161013565-437ceef1-70be-441f-944a-bb9c11852e39.jpg)

The hook itself is working when using the image one, do we need to delay the initialization for the face tracking in react?

**Comment by hiukim** [comment]
@krsbx 

https://github.com/krsbx/mind-ar-react/blob/df987d08862634d6435074843e9d5e1fc7e38d7b/src/Examples/FaceTracking.tsx#L15

maybe this line should be `mindar-face={{` and remove line 13.

**Comment by krsbx** [comment]
@hiukim after removing it, it still giving an error like that. The weird thing is that in the image tracking one we use the same approach it works fine, but on the face tracking one it doesn't. I try to compare between the face tracking without react and with react, the only difference that i see is that in react we need to start it manually, but somehow cant be triggered.

I'll try to delay the start process and hope it works

**Comment by hiukim** [comment]
I suspect this function is not being called for whatever reason: https://github.com/hiukim/mind-ar-js/blob/c39c9e4f4a289b924b1a90c6a3eb72fc8df990ca/src/face-target/aframe.js#L16

To debug this, you can add a console.log there and create a custom build `> npm run build`. Then use this instead of the production one. You will know whether it's being called (and when).

**Comment by Sossenbinder** [comment]
Hey @hiukim .

Did anything come out of the discussion here? We just tried to follow the ReactJS example as well, but I also got stuck on this issue. The scene just won't render with mindar-face in the props. I made it work with the ThreeJS alternative for now at least.

**Comment by krsbx** [comment]
@Sossenbinder i found the problem where it try to use a camera that doesnt exist in the desktop, so i create a [PR to fix it](https://github.com/hiukim/mind-ar-js/pull/178)

But i found another problem where the open cv.js doesn't has the SVDecomp, idk if it just a problem on my end or not, since i try to add opencv using the script tag, then try to console.log the SVDecomp function, it return undefined

**Comment by hiukim** [comment]
I have a custom compiled cv.js for this. Make sure you use the one provided in this repo.

Also, cv.js is tricky. It takes a little time to initialize. I have a waitCV helper function `https://github.com/hiukim/mind-ar-js/blob/master/src/libs/opencv-helper.js`
