### ISSUE TITLE
Android mobiles incompatibility

### ISSUE THREAD

**Issue by ByJuanCho98** [hiukim/mind-ar-js#154]
Amazing SDK. <3 thx.
I'm having a rough time trying to figure it out why mind ar only works well on IOS mobiles. On some Android i got some weird offsets all the time. Do i have to edit the position property for every object everytime?

**Comment by Qs-cic** [comment]
I ran into the same problem. I noticed that on Android phones, the model doesn't follow the face, it stays in one place. It's not where the model finds people, it's where people find the model. (Virtual wearing example)

**Comment by ByJuanCho98** [comment]
Hi @Qs-cic, I just tested on the Samsung Tab s7 FE and it's working fine. The problem might be with older devices, right? Or maybe not powerfull enough. I noticed that this sdk is working with mediapipe and mediapipe works perfectly on every android device that i tested. IDK what the problem might be :(

**Comment by hiukim** [comment]
Can you guys share some screen recordings to show the problems?

Also, which android devices and OS versions?

**Comment by ByJuanCho98** [comment]
Hi @hiukim, 

It's working on:

Iphone 11. OS 15.3.1,
Iphone 12 pro max. OS 15.3.1,
Samsung Tab s7 FE. 
https://drive.google.com/file/d/1wt3d6r2xHR2u5iXBKzEnE-9W6zLabe4y/view?usp=sharing

It is not working properly on:

Motorola g9,
Realme 6,
Redmi note 9
https://drive.google.com/file/d/1tzxPgLtge0E4knQ5C46K7krSJjwJsUr4/view

For what i can tell... the first problem is that the object is moving when i move around the phone. I tried to turn off the gyroscope but the result is the same. The second issue is that the object isn't in the correct position right when the AR experience begin. 

I have another issue... In both mobile cases the object can be dragged by the user input on "x" coordinate. It is restricted on "y" coordinate. 
https://drive.google.com/file/d/1-tjskLG8XI2cOA_kVFDS0caKOuj_fm4-/view?usp=sharing

On desktop it is not restricted by user input at all.
https://drive.google.com/file/d/1yaATb6XZYWNKpePZC8dwKL8gqMjG4GRe/view?usp=sharing

I believe this is an <a frame> misconfiguration.. but.. Do you know how can i restrict the movement completely?

Thanks for your time and work. You are really awesome 💯

**Comment by ByJuanCho98** [comment]
The SOLUTION of this issue is attaching: look-controls-enabled property to the camera and setting it to false. 

It looks like this.

<a-camera active="false" position="0 0 0" look-controls-enabled="false"></a-camera>

Everything works perfectly now. It works on Android and iOS as intended!!

Thanks once more @hiukim . <3

**Comment by hiukim** [comment]
I see. Thanks for figuring out the problem
