### ISSUE TITLE
display uiScanning component when marker is lost. 

### ISSUE THREAD

**Issue by JamesBotterill** [hiukim/mind-ar-js#155]
At present when the marker is lost  the uiScanning setting isn't displayed, ideally this should be displayed again once a market is lost.

**Comment by hiukim** [comment]
yes. that sounds reasonable.

**Comment by krsbx** [comment]
@JamesBotterill i think we can achieve this by making the mindar image systems subscribe to onMarkerFound and onMarkerLost event
