### ISSUE TITLE
Loading gltf on pending when I access address of your online course assignment

### ISSUE THREAD

**Issue by Simon1059770342** [hiukim/mind-ar-js#157]
Hi Teacher HiuKim! Great Job! 
I have taken your gorgeous WebXR coures online, but when I access your finished world-tracking-assignment in this video both on my OnePlus 7(Chrome 81.x) and iPad(WebXR viewer) by running ngrok http 8887, the furniture gltf model always be at pending from network. The same problem also came out of my laptop (msi). error reported as following:

` "Get https://..../scene.gltf" net: :ERR PROXY CONNECTION FAILED."`

 Is that ngrok ban gltf model loading? Any other webserver software can you recommend? THX for your help!
 FYI, when I access the adress with "localhost:8887/....", it actually worked in my laptop but just in VR scene. 
Thanks for what you've done for us!

BTW, share your online video demostration link here for your convenience: 
https://www.youtube.com/watch?v=P-blSkeKEl8&ab_channel=HiuKimYuen

**Comment by hiukim** [comment]
@Simon1059770342 I feel like sometimes ngrok is slow for transferring large file. It makes sense because they provide free proxy server for that. It might be the issue. I don't recall other services like ngrok, but I would expect similar behaviour unless they are paid service.  The best way is to unblock the firewall in your localnetwork so you don't need ngrok at all. Otherwise, you might have to upload the content to public web server. 

I'm closing this issue because it's not related to MindAR. It's more a like a general web hosting issue.

**Comment by Simon1059770342** [comment]
Thanks for your help Teacher HuiKim! Did you mean that I can unblock the firewall in your localnetwork and access localhost:8887 from my mobile device, am I right?

**Comment by hiukim** [comment]
I'm not an expert in networking.

I think if your mobile device and laptop is under the same local network. You can access your laptop with a local IP address, e.g. 192.168.0.xxx if you internal network doesn't block it.

**Comment by Simon1059770342** [comment]
THX! Hope My issues didnt bother you! 
Yesterday, I tried "npm install http-server ...", surprisingly, I can access the IP address "192.168....." on my Android phone. 
Unfortunately, I still got error as"The specified session configuration is not supported." from [immersive-ar sample](https://immersive-web.github.io/webxr-samples/) on Android phone (OnePlus 7T which is support for ARCore and Chrome version 100). 
And I try to install Acore on my phone it still doesnt work, error as "The specified session configuration is not supported". 
so I report this issue to WebXR on Github https://github.com/immersive-web/webxr/issues/1271
and immersive-web on Github https://github.com/immersive-web/webxr-samples/issues/144

And I also find that WebXR Viewer can not access address like "192.168....".
I am now doing research on finding out the solution for issues above.

If there is any good news, you'll be the second one to know. THX for your help!

**Comment by Simon1059770342** [comment]
Good News! Everything worked after I update Chrome and ARCore in Google Play Store! I will share this simple Solution with others! THX Teacher HuiKim!

**Comment by hiukim** [comment]
nice. good to know!
