### ISSUE TITLE
image/plane are stretched vertically in a-frame with image-tracking

### ISSUE THREAD

**Issue by louis-ev** [hiukim/mind-ar-js#158]
Hi !

first of all thanks a lot for the awesome work ! 
I have been studying and implementing it in one of my open-source apps, [do•doc](https://github.com/l-atelier-des-chercheurs/dodoc/), which is mostly used by kids and they love the face tracking feature. They draw masks and [add them to do•doc](https://capitaine.dodoc.fr/_thumbs/_publications/creer-des-masques-du-futur/image.png.1600.jpeg), where they can see them mapped on their faces. Works great :)

![image](https://user-images.githubusercontent.com/1948417/162007227-47d14534-a70e-4290-bcda-2d076e8e16e0.png)

--- 

Anyway, I’ve been trying to add image-tracking as well (kids take a picture of two drawings, one becomes the target of the other) and almost can get it to work.
However I get what looks like a bug : the projected image is stretched vertically at first, but this is fixed when I open the a-frame inspector. What could cause this ?

Two screenshots to show the problem, the only difference between them is that I opened the inspector :

![screenshot 2022-04-06 à 16 55 57](https://user-images.githubusercontent.com/1948417/162007919-d29dd3df-bcaa-4d2d-af12-ff8229be2f10.png)

![screenshot 2022-04-06 à 16 56 20](https://user-images.githubusercontent.com/1948417/162007965-bc75eba2-9e52-4518-9bb6-ce8f7a8cf13a.png)

My a-frame code (I’ve added height and width but this makes things worse…) :

```
        <a-scene
          :mindar-image="`imageTargetSrc: ${mind_and_results[0].mind}; filterMinCF:0.1; filterBeta: 10;`"
          vr-mode-ui="enabled: false"
          device-orientation-permission-ui="enabled: false"
          color-space="sRGB"
          renderer="colorManagement: true, physicallyCorrectLights"
        >
          <a-assets>
            <img id="result" :src="'/' + mind_and_results[0].result" />
          </a-assets>

          <a-camera position="0 0 0" look-controls="enabled: false"></a-camera>

          <a-entity mindar-image-target="targetIndex: 0">
            <a-plane
              src="#result"
              position="0 0 0"
              height="0.552"
              width="1"
              rotation="0 0 0"
            ></a-plane>
          </a-entity>
        </a-scene>
```

And in context, as a Vue.js component : https://github.com/l-atelier-des-chercheurs/dodoc/blob/dodoc2-dev/public/src/vue/components/publication_templates/subcomponents/ImageTrackingModule.vue

Thanks !

**Comment by hiukim** [comment]
@louis-ev  The face mask from your student is really interesting!

You need to set height and width properly for your ` <a-plane>` according to the dimensions of your `result` image. Checkout the bottom tips on https://hiukim.github.io/mind-ar-js-doc/quick-start/webpage

**Comment by louis-ev** [comment]
Hi @hiukim, thank your for helping!
I actually read your docs, and set the width and height for this reason. I’ll get the actual image ratio later, for now I just tested values coming from your examples.

In my code you can see that `height="0.552"` is not taken into account until I open the inspector.

Here is another example with width and height set to 1. Same bug in Firefox and Chrome on macOS, and Safari on iOS.

```
<a-scene
          :mindar-image="`imageTargetSrc: ${mind_and_results[0].mind}; filterMinCF:0.1; filterBeta: 10;`"
          vr-mode-ui="enabled: false"
          device-orientation-permission-ui="enabled: false"
          color-space="sRGB"
          renderer="colorManagement: true, physicallyCorrectLights"
        >
          <a-camera position="0 0 0" look-controls="enabled: false"></a-camera>

          <a-entity mindar-image-target="targetIndex: 0">
            <a-plane
              position="0 0 0"
              height="1"
              width="1"
              rotation="0 0 0"
            ></a-plane>
          </a-entity>
        </a-scene>
```

<img width="582" alt="screenshot 2022-04-07 à 00 02 25" src="https://user-images.githubusercontent.com/1948417/162079945-e1c694fb-3622-44d7-9a47-7e633cb2c1dc.png">
 
After opening the aframe inspector : 

<img width="703" alt="image" src="https://user-images.githubusercontent.com/1948417/162080018-19af4f13-aa66-4be9-9415-b55fdb8d4d18.png">

Resizing the window doesnt work, it really seems to be the inspector that fixes the a-frame scene. I thought the bug could be with aframe but I couldn’t find anything on this on the web…

**Comment by louis-ev** [comment]
Hi @hiukim,
Do you think I should post this issue in the A-Frame repo?
It seems strange that I’m getting this bug with just a basic a-plane, and that pulling out the inspector fixes it…
Thank you for your time!

**Comment by hiukim** [comment]
@louis-ev sometimes weird things like this happen, it could be a bug anywhere, or opening the inspector trigger some re-rendering.

looking from your code `${mind_and_results[0].mind}`, it looks like you are using some kind of framework maybe react. I guess you have some additional logic instead of a plain html as in the example.

If that's the case, what I normally would do is to start from a working example first (e.g. the original example in the documentation). You can change height and width to see if there is any effect. If yes, then make gradual changes up to a point that doesn't work and we'll know the problem.
