### ISSUE TITLE
The model jitter of mind-ar version 1.0.0 is much better than that of version 1.1.4. Why?

### ISSUE THREAD

**Issue by QingHuanYuJiu** [hiukim/mind-ar-js#161]
hi, Do I configure or jiggle according to https://hiukim.github.io/mind-ar-js-doc/quick-start/tracking-config.
![1649756990(1)](https://user-images.githubusercontent.com/38201850/162932760-85d9df21-25cb-4a55-aff0-77735c264aa4.jpg)

**Comment by QingHuanYuJiu** [comment]
The model jitter of mind-ar version 1.0.0 is much better than that of version 1.1.4. Why?

**Comment by hiukim** [comment]
There were no tracking config in the previous version, the default setting traded off jitter with delay. I think you can probably get similar result by tuning the filter parameters.

**Comment by QingHuanYuJiu** [comment]
> 以前的版本没有跟踪配置，默认设置是用延迟来权衡抖动。我认为您可以通过调整过滤器参数来获得类似的结果。

Are you talking about adjusting Tracking Config?

**Comment by QingHuanYuJiu** [comment]
I am from China and I am not very good at English. I do not understand many meanings in the document very thoroughly. I envy version 1.0.0 very much, because the jitter processing of that version is very good. Please help me thank you very much. /(ㄒoㄒ)/~~

**Comment by QingHuanYuJiu** [comment]
In version 1.1.3, I set these two properties, missTolerance:0; Warp tolerance: 0 doesn't seem to work. The model is hidden a few seconds after the image is lost. Why?
![image](https://user-images.githubusercontent.com/38201850/163172162-f9d74384-279e-489d-b1f5-c6aa718b4554.png)

**Comment by hiukim** [comment]
The config is introduced in v1.1.4

**Comment by QingHuanYuJiu** [comment]
> The config is introduced in v1.1.4

V1.1.3 I can change his delay time

**Comment by QingHuanYuJiu** [comment]
斯巴拉西!!!!

**Comment by hiukim** [comment]
I see. thx for letting me know.
