### ISSUE TITLE
how to build band.mind

### ISSUE THREAD

**Issue by Jarvis3310** [hiukim/mind-ar-js#162]
like example「Image Tracking Examples--> Multi-Targets」 
how to concat two images in one band.mind ?

**Comment by Jarvis3310** [comment]
image like this? and then compile? 
![band](https://user-images.githubusercontent.com/36700902/163137000-bb70ea32-0085-48a6-9e2f-24b0fcd5d4d2.png)

and index like this? 
![image](https://user-images.githubusercontent.com/36700902/163137460-8faf5dfc-763e-4721-b1fb-b777a9e590e1.png)

**Comment by hiukim** [comment]
You can add multiple images in the compiler tool

**Comment by Jarvis3310** [comment]
sorry, I have added in compiler tool. it comes out two .mind , not in one
![Uploading Screenshot_20220420_162209.jpg…]()

**Comment by Jarvis3310** [comment]
sorry, I have added two images in compiler tool. But it comes out two .mind , not in one.
![Screenshot_20220420_162209](https://user-images.githubusercontent.com/36700902/164185677-92c9a4e3-c6fc-4f12-ba0a-7f6719c18087.jpg)

**Comment by mrizkiaiman** [comment]
Same problem with me, I wonder how to generate .mind file with more than one image, since what we see from the example of multiple-track/target is only use 1 .mind file.
