### ISSUE TITLE
Is there an API for the target image compiler?

### ISSUE THREAD

**Issue by Jarvis3310** [hiukim/mind-ar-js#163]
or just in https://hiukim.github.io/mind-ar-js-doc/tools/compile?

**Comment by ragavendranbala** [comment]
Hi @Jarvis3310 have you found the compiler api?

**Comment by Jarvis3310** [comment]
not yet, only Compiler tools web

**Comment by prp-e** [comment]
isn't there some sort of JS library which compiles this?

**Comment by veronicamontezuma** [comment]
there is some info on the [mind-ar-js-doc](https://github.com/hiukim/mind-ar-js-doc) repository, I was able to work with the compiler using what's there as a reference. searching for 'compiler', the file used on the docs page can be used as a practical example. depending on your needs, it may be enough...
