### ISSUE TITLE
Blue Loading Screen

### ISSUE THREAD

**Issue by fourthedesign** [hiukim/mind-ar-js#165]
When loading an application I tried to override the blue loading screen using an image (poster_01) but the loading screen still appears. Is it possible to remove it?
![Screenshot_2022-04-15-14-41-36-476_com android chrome](https://user-images.githubusercontent.com/99669150/163567448-52972ef5-f76c-4b18-8929-a2c55541ba38.jpg)

`<div id="loading" class="hidden">

         <div class="inner">
            <img src="/poster_01.jpg"/>
         </div>
      </div>
      <div id="main">
         <div class="topnav">
            <div id="myLinks">
               <a href="https://test.gr/">WEBPAGE</a>
            </div>
            <a href="javascript:void(0);" class="icon" onclick="BurgerFunction()">
            <i class="fa fa-bars"></i>
            </a>
         </div>
         <a-scene mindar-image="filterMinCF:0.01; filterBeta: 70; warmupTolerance: 1; uiLoading: #loading; uiScanning: #loading;imageTargetSrc: ./targets(1).mind" vr-mode-ui="enabled: false" device-orientation-permission-ui="enabled: false"> 
            <a-assets>
               <video id="myvideo" src="/merged-video.webm" type="video/webm" loop="true" playsinline autoplay></video>
            </a-assets>`

**Comment by veronicamontezuma** [comment]
I believe this loading screen comes from a-frame! 
you can check here for info on how to alter/remove it: https://aframe.io/docs/1.3.0/components/loading-screen.html
