### ISSUE TITLE
Is it possible to use CSS3D with mind-ar?

### ISSUE THREAD

**Issue by Felpat0** [hiukim/mind-ar-js#169]
I would like to render a CSS3DObject, but THREE.CSS3DObject does not exist in https://cdn.jsdelivr.net/npm/mind-ar@1.1.4/dist/mindar-image-three.prod.js .
Is there any other way?

Thanks

**Comment by positlabs** [comment]
I think you'll need to load the CSS3DRenderer first. It's not included in the threejs build by default. You can find it in the examples folder. https://github.com/mrdoob/three.js/blob/master/examples/jsm/renderers/CSS3DRenderer.js
