### ISSUE TITLE
style bug in image targets compiler

### ISSUE THREAD

**Issue by devhims** [hiukim/mind-ar-js#17]
Sometimes the complied image covers up the download button partially or completely. It can be tested with this image: 
https://raw.githubusercontent.com/devhims/mind-ar-examples/main/assets/maggi.png

Reference:
<img width="1293" alt="Screenshot 2021-03-16 at 1 18 54 PM" src="https://user-images.githubusercontent.com/17825870/112326396-7f36f780-8cda-11eb-9255-289ebce55025.png">

**Comment by hiukim** [comment]
thx for reporting. Will look into it!

**Comment by hiukim** [comment]
fixed
