### ISSUE TITLE
Plan to convert to typescript?

### ISSUE THREAD

**Issue by krsbx** [hiukim/mind-ar-js#170]
For now the project is written in javascript, is there any plan to convert the project to typescript? So, people who want to contribute can easily knew which function do things and what thing need to be pass on on the function. And the development process can produce less bugs since we knew which stuff that break the code

**Comment by krsbx** [comment]
I try to rewrite on this [repo](https://github.com/krsbx/mind-ar-ts), but looks like the current code with the current tensorflow/tfjs kinda broken

**Comment by hiukim** [comment]
I don't have this plan. Not something particularly interesting to me, I would say. haha :)
