### ISSUE TITLE
Can't configure OneEuroFilter 

### ISSUE THREAD

**Issue by GooseNinja** [hiukim/mind-ar-js#171]
I have been testing MindAR image tracking, but my models jitter. I tried to configure filterMinCF and filterBeta without any luck. No matter what numbers I use, it still jitters a lot. 

Am I using it wrong, or is something off with the filter?

**Comment by Nikozil** [comment]
Hello my friend.
I spent a lot of time on this problem. The following configuration worked for me:
`<a-scene mindar-image="filterMinCF:0.0001; filterBeta: 0.001"/>`
It would be great to install it or a working analogue of the default one.
