### ISSUE TITLE
Miss the target while rotating phone

### ISSUE THREAD

**Issue by Nikozil** [hiukim/mind-ar-js#174]
If the target(image) was found and then rotate the phone (resize the window), the target is not found.
After turning back, the target is founded again.

**Comment by shabarito** [comment]
Hello.
This solved to me. But the image will be scanned again.

window.onresize = function () {
            document.querySelector('a-scene').systems["mindar-image-system"].pause()
            document.querySelector('video').remove();
            Array.from(document.querySelectorAll('[mindar-image-target]')).forEach((element,index) => {
                element.components['mindar-image-target'].updateWorldMatrix(null, )
            });
            document.querySelector('a-scene').systems["mindar-image-system"]._startVideo()
        }
    }

**Comment by Nikozil** [comment]
Thank you very much. It works
