### ISSUE TITLE
 RangeError: Extra 2412 byte(s) found at buffer[1]

### ISSUE THREAD

**Issue by pranav-pavithran** [hiukim/mind-ar-js#175]
I'm getting this " RangeError: Extra 2412 byte(s) found at buffer[1]" s error [screen shot](https://imgur.com/a/LrAkz62)

I was trying to create .mind file within my app and then set attribute to scene element. It seems like time delay in creating mind file is the  issue. any work around?

**Comment by hiukim** [comment]
delay initializing the scene until the file is ready?

**Comment by divljikunic** [comment]
Identical to #257 

Steps to reproduce: 
1. Run any example locally, using 'card.mind' from cdn
2. Download 'card.mind', give it a local path - RangeError appears

It may be important to note I'm using React (create-react-app) and A-Frame, both installed via npm. 
I've also generated .mind from a custom tracking image and somehow that particular one doesn't produce any errors, however if I try to do it again (even when using the identical image used for the one that works) it fails.

Replacing react-scripts (introduced by create-react-app) with webpack didn't help, but the number of "extra bytes" was reduced considerably. From 1700ish to 100ish in my particular case.

@hiukim hopefully you can point us in the right direction, it seems to be a recurring issue.

**Comment by divljikunic** [comment]
See if this helps: https://github.com/hiukim/mind-ar-js/issues/257#issuecomment-1287445243
