### ISSUE TITLE
camera feed and threejs renderer not aligned in face AR

### ISSUE THREAD

**Issue by rudrdybo** [hiukim/mind-ar-js#176]
the current camera feed was not behaving the way I wanted it to work so I flipped the camera feed to serve my use case(using CSS) but that in turn made the three.js to make the model on face to rotate in other direction which is obvious as I didn't flipped the camera feed but the element showing it. So Please let me know where to change the code to make the threejs work inline with camera feed.

**Comment by hiukim** [comment]
flip the renderer canvas (using CSS) also?
