### ISSUE TITLE
Compile Target Images

### ISSUE THREAD

**Issue by denispriler** [hiukim/mind-ar-js#18]
Is there any way to compile images with NodeJS? Just to run command in console or whatever

**Comment by hiukim** [comment]
Unfortunately, it can't be done at the moment. 

Part of the code is currently run in webgl, which requires a browser environment.

**Comment by ultranano** [comment]
Hi @hiukim! How i can compile the target image on my own server?
I can't found an example of that.
Thanks in advance!

**Comment by hiukim** [comment]
@ultranano Unfortunately, it can't be done at the moment.

Part of the code is currently run in webgl, which requires a browser environment.

**Comment by ultranano** [comment]
I mean... I want to compile image target reference without pass to your site but use my own domain. It’s possible? How I can setup this?

**Comment by hiukim** [comment]
There is an old (not maintained anymore) example here: https://github.com/hiukim/mind-ar-js/blob/master/examples/compile.html. But I think it's still working.

The most important function is this one:
https://github.com/hiukim/mind-ar-js/blob/ba310848f10acf3941bdccd949b3120b14ddda96/examples/compile.html#L90

**Comment by ultranano** [comment]
thanks! i'll try today.
BTW why there isn't a new example of compile target form like in the documentation?

**Comment by hiukim** [comment]
I think you can use either `dist-dev` or `dist`

**Comment by hiukim** [comment]
I just wasn't expecting there is a need to host a custom target compiler. What's the use case of it?

I guess I can tidy that example up and put it in the doc.

**Comment by Ebeleh** [comment]
> I just wasn't expecting there is a need to host a custom target compiler. What's the use case of it?
> 
> I guess I can tidy that example up and put it in the doc.

maybe u can give code for the image compiler? or the link where u got it

**Comment by kalwalt** [comment]
@hiukim if you want we can develop a target compiler to host on our Netlify org account [webarkit](https://github.com/webarkit)

**Comment by hiukim** [comment]
@Ebeleh @kalwalt 

The code is already in the repo. It's mainly the `./src/compiler.js`

There is an example under `./examples/compile.html`. The code should still be working, but just that the UI might not be well polished. but shouldn't be too difficult to understand.

I think the core function call is here:
`https://github.com/hiukim/mind-ar-js/blob/ba310848f10acf3941bdccd949b3120b14ddda96/examples/compile.html#L96`

Yes, feel free to develop your target compiler if you want.

**Comment by Ebeleh** [comment]
> @Ebeleh @kalwalt
> 
> The code is already in the repo. It's mainly the `./src/compiler.js`
> 
> There is an example under `./examples/compile.html`. The code should still be working, but just that the UI might not be well polished. but shouldn't be too difficult to understand.
> 
> I think the core function call is here:
> `https://github.com/hiukim/mind-ar-js/blob/ba310848f10acf3941bdccd949b3120b14ddda96/examples/compile.html#L96`
> 
> Yes, feel free to develop your target compiler if you want.

thanks

**Comment by Swapratim** [comment]
Hi Hiukim,

Thanks for the compiler https://github.com/hiukim/mind-ar-js/blob/master/examples/compile.html. 
About this line: <script src="../dist-dev/mindar.js"></script>
Since I cannot find dist-dev, I am referring the following from dist:
1. mindar.prod.js
2. mindar.prod-min.js

But it is not working as expected. At least I cannot upload any image to the page or start the process (I'm not bothered about the UI but the basic functionality seems not working).

Can you please help?


![image](https://user-images.githubusercontent.com/6933077/126062072-0054a092-65de-49c4-82ba-c33ca4c65f1f.png)

**Comment by hiukim** [comment]
run `npm run watch` to build `dist-dev/mindar.js`  but mindar.prod.js is also okay

what's the error?

**Comment by Swapratim** [comment]
The div for uploading image to start the conversion is not working.
In the above screenshot, the div is apparently non-responsive to upload any image.

I'm not the expert apparently - am I missing anything?

**Comment by Swapratim** [comment]
Hi,

Any suggestion on this?

**Comment by hiukim** [comment]
need to see the error.  Do you know how to open the console log?

**Comment by Swapratim** [comment]
Sure, I am testing it in here, you can too see the code and probably might the root cause of it: https://nft-webui.glitch.me/

**Comment by Swapratim** [comment]
![image](https://user-images.githubusercontent.com/6933077/126492243-8cc0f3ab-2518-49aa-848f-6755ce662c40.png)

There are 2 things that coud possibly create issue:
1. Line 13: const compiler = new MINDAR.Compiler();
    Uncaught ReferenceError: MINDAR is not defined
    
2. I added a few lines of HTML tags inside <div id="dropzone" class="dropzone"></div>
   to make sure image can be uploaded and visible. But clicking on 'Start' button not yielding any action
  
   I added an alert inside JS function: 
    document.getElementById("startButton").addEventListener("click", function() {
          alert('Hi');
     ...}
     this alert is not showing on click. Probably it is related to "myDropzone" files which it cannot refer to.
   
![image](https://user-images.githubusercontent.com/6933077/126492747-53893491-1b07-44a7-a4d3-932e19ed604b.png)

**Comment by hiukim** [comment]
You only need to include `mindar.prod.js`. can remove others

**Comment by Swapratim** [comment]
Followed it. But still the console throws error at [ const compiler = new MINDAR.Compiler(); ] line
After uploading image, the start button does not respond - even after waiting for 10 min - download button does not yield .mind file

**Comment by hiukim** [comment]
can you double check this link exists `https://nft-webui.glitch.me/mindar.prod.js`

**Comment by Swapratim** [comment]
You are absolutely right - the JS was not functioning due to Glitch auto-formattting file structure. 
It is working like a charm. Thank you so much :-)
Sorry for all the inconvenience though...

**Comment by hiukim** [comment]
nice!

**Comment by Swapratim** [comment]
One more question: what is the basis of putting a scale of the compiled image between Scale 1 to 10?

**Comment by Swapratim** [comment]
Hi @hiukim 

Hope you are doing well.
I have two questions for Mind AR:

1. Can we interact with the 3D GLTF in here like rotate, zoom in/out etc.? (It can be done using AR.js for marker-based AR - using gesture-handler tag. But that tag does not work in here). Any suggestion how to make it work?
2. Can we put audio as an asset-item and play it (onclick/autoplay) during AR show? (AR.js can do it actually).

Since it is also based on AR.js - can you not enable/add the functionality in the latest builds?

**Comment by hiukim** [comment]
@Swapratim 

It's not based on AR.js. It's two entirely different engine from ground up.

Even said that, I think those two are totally possible. Unfortunately, I haven't tried any of these and I don't have a working example to show you.

**Comment by Swapratim** [comment]
@hiukim 

Thanks. It totally makes sense.

Do you have any timeline when it can be incorporated in Mind AR?

**Comment by hiukim** [comment]
@Swapratim sorry, I don't have a timeline for that at the moment. When I have some free time, I could try it out.

**Comment by Swapratim** [comment]
@hiukim I would really appreciate that. Thanks for the update.

**Comment by annamarthin** [comment]
@hiukim 

The image targets compiler seems to be broken. Is there any other way to compile the targets?

![image](https://user-images.githubusercontent.com/82447777/184142175-1170edd7-4304-4464-98c5-f2d80c46300b.png)

**Comment by devangpawar17** [comment]
@Swapratim can you please provide the code to compile images in local host i am having problems doing it .

**Comment by mlambie** [comment]
@Swapratim @devangpawar17 I'd be keen on seeing this also

**Comment by icantcook** [comment]
@devangpawar17 @mlambie I managed to get it working with a few edits.. Here's the link. Hope it helps.
[https://glitch.com/edit/#!/evening-malleable-thorn](https://glitch.com/edit/#!/evening-malleable-thorn)
@hiukim thanks a ton for the library, sir!

**Comment by julior0518** [comment]
> @devangpawar17 @mlambie I managed to get it working with a few edits.. Here's the link. Hope it helps. https://glitch.com/edit/#!/evening-malleable-thorn @hiukim thanks a ton for the library, sir!

I'm trying to use your version to try out the compiler but it tells me 
const compiler = new MINDAR.IMAGE.Compiler();
can you help please?

**Comment by icantcook** [comment]
> > @devangpawar17 @mlambie I managed to get it working with a few edits.. Here's the link. Hope it helps. https://glitch.com/edit/#!/evening-malleable-thorn @hiukim thanks a ton for the library, sir!
> 
> I'm trying to use your version to try out the compiler but it tells me mindar is not defined in:
> 
> const compiler = new MINDAR.IMAGE.Compiler();
> 
> can you help please?

That's strange. Can you share the logs? I'll have a look. 
The code is pretty straight forward though, and is tested on Edge, Chrome and Firefox.

**Comment by devangpawar17** [comment]
@icantcook @mlambie it's working fine for me

**Comment by sampath1911** [comment]
@icantcook @mlambie @devangpawar17 
Will this code work on next js and React js enviroment?

**Comment by icantcook** [comment]
> @icantcook @mlambie @devangpawar17 @denispriler Will this code work on next js and React js enviroment?
Yes. That being said, you would have to make changes to the code as per your requirements.
Also, you would have to use hooks to get instance of mind ar and its image compiler first if it's not being explicitly exported as a component.

**Comment by RaheemWilson** [comment]
@hiukim I am trying to use the current cdn version to access the Compiler class but I am getting "Compiler is not defined error". Is there something that I might be missing? Please link below

`<script src=“https://cdn.jsdelivr.net/gh/hiukim/mind-ar-js@1.2.2/dist/mindar.prod.js”></script>`

**Comment by piisan29** [comment]
@hiukim Thank you so much the documentation tutorials are really cool, by any chance is there a way or tutorial we could use to create our own compiler: https://hiukim.github.io/mind-ar-js-doc/tools/compile/

thank you so much

**Comment by Swapratim** [comment]
Hello Hiukim,

Thanks for the brilliant tutorials. Is there a way for adding green screen (video without background - set alpha for background screen so that characters appear as 3D) video in AR (especially in image targeting AR)?

**Comment by piisan29** [comment]
> @hiukim I am trying to use the current cdn version to access the Compiler class but I am getting "Compiler is not defined error". Is there something that I might be missing? Please link below
> 
> `<script src=“https://cdn.jsdelivr.net/gh/hiukim/mind-ar-js@1.2.2/dist/mindar.prod.js”></script>`

Hello, by any chance did you already resolve this problem? Got the same error. Thank yoy

**Comment by morteza-eskandarian** [comment]
> @Swapratim sorry, I don't have a timeline for that at the moment. When I have some free time, I could try it out.

Hello @hiukim
I hope you are doing very well. I just wanted to ask if you have implemented the zoom or rotate feature in Mindar?

**Comment by irfansipai** [comment]
hi @Swapratim , if you are looking for something which can help remove green part from your video and place the video in mind-ar with alpha channel set , you can use this method here. 
[Link](https://github.com/nikolaiwarner/aframe-chromakey-material)
for this you have to place your video tag inside asset and make the plane get it within entity tag like this 
`    <body>      
    <a-scene mindar-image="imageTargetSrc: ./targets.mind; showStats: false; uiScanning: #example-scanning-overlay;" embedded color-space="sRGB" renderer="colorManagement: true, physicallyCorrectLights" vr-mode-ui="enabled: false" device-orientation-permission-ui="enabled: false">
    
        <a-assets>
            
            <video style="opacity: 0;" id="video" src="./video/examplecar.mp4" loop autoplay muted></video>
        </a-assets>

        <a-camera position="0 0 0" look-controls="enabled: false"></a-camera>

        <a-entity id="mytarget" mytarget mindar-image-target="targetIndex: 0">
            <a-text value="" id="text-en" color="purple" align="center" width="2" position="0 0.4 0"
            animation="property: position; to: 0 0.5 0; dur: 1000; easing: easeInOutQuad; loop: true; dir: alternate"
            ></a-text>
            
            <a-plane 
            material="
            shader: chromakey; 
            src: #video; 
            color: 0.1 0.9 0.2" 
            position="0 0 0.2" 
            scale="1 1 1"
            rotation="80 0 0"
            animation="property: position; to: 0 0 -1; dur: 1000; easing: easeInOutQuad; loop: false; dir: alternate"
          ></a-plane>    
            
        </a-entity>
    </a-scene>
  </body>

</html>`
, and can i get the source or anything related for making the compiler work independently so that i can integrate it inside my project , Thanks.

**Comment by pranavkattel** [comment]
> Sure, I am testing it in here, you can too see the code and probably find the root cause: https://nft-webui.glitch.me
> 
> ![image](https://user-images.githubusercontent.com/6933077/126492243-8cc0f3ab-2518-49aa-848f-6755ce662c40.png)
> 
> There are 2 things that could possibly create issue:
> 
> 1. Line 13: const compiler = new MINDAR.Compiler();
>    **Uncaught ReferenceError: MINDAR is not defined** --> I'm not sure how to import the **MINDAR.compiler()** since it is not getting imported from the following JS:
>    
>    * mindar.prod.js
>    * mindar.prod-min.js
>    * compiler.js
>    * compiler.worker.prod.js
>    * compiler.worker.prod-min.js
> 2. I added a few lines of HTML tags inside "div id="dropzone" class="dropzone">"
>    to make sure image can be uploaded and visible. But clicking on 'Start' button not yielding any action
>    I added an alert inside JS function:
>    document.getElementById("startButton").addEventListener("click", function() {
>    alert('Hi');
>    ...}
>    this alert is not showing on click. Probably it is related to "myDropzone" files which it cannot refer to.
> 
> Looking forward for your suggestions here.
> 
> ![image](https://user-images.githubusercontent.com/6933077/126492747-53893491-1b07-44a7-a4d3-932e19ed604b.png)

how did u do it can i get the source code

**Comment by wildy13** [comment]
already resolve  to this problem? i cant make my compiler in local

**Comment by iplanwebsites** [comment]
I'd love to build a custom compiler. 
What's the cleanest way to import the compile function in a browser env? Is the compile function exported somewhere?
My use case is to process sets of images created by users. I'd ideally run in it headless browser if node doesn't work,

**Comment by iwanedogawa** [comment]
> There is an old (not maintained anymore) example here: https://github.com/hiukim/mind-ar-js/blob/master/examples/compile.html. But I think it's still working.
> 
> The most important function is this one:
> 
> [mind-ar-js/examples/compile.html](https://github.com/hiukim/mind-ar-js/blob/ba310848f10acf3941bdccd949b3120b14ddda96/examples/compile.html#L90)
> 
> Line 90 in [ba31084](/hiukim/mind-ar-js/commit/ba310848f10acf3941bdccd949b3120b14ddda96)
> 
>  const compileFiles = async (files) => {

Hi @hiukim, thanks for sharing your projects. That's fantastic. I've just learned AR through your projects. Now, I am trying to compile images on my project environment. Unfortunately, currently, I couldn't find the example of compiler code on the link you provided here... Could you please share again the example of the compiler code? Thanks
