### ISSUE TITLE
Render GLTF 3D Model got blurry

### ISSUE THREAD

**Issue by mrizkiaiman** [hiukim/mind-ar-js#181]
Hello,

I want to ask, has this happened before to anyone here? When I tried to render the GLTF 3D Model, it got blurry like [this](https://imgur.com/a/qtL4dVa)

I suspect this is related to the red bar from **Triangle column of Three.JS - Render** section, but since I'm new to three.js I'm not sure what's going on with the chart.

Please let me know in case you know something about this, thanks^^

**Comment by hiukim** [comment]
Try your model in a regular three.js application first without AR and see if you have this problem? @mrizkiaiman
