### ISSUE TITLE
"Failed to launch" error

### ISSUE THREAD

**Issue by underlabmx** [hiukim/mind-ar-js#182]
A few days ago I realized that in multiple projects of mine and acquaintances the legend "failed to launch" appears, I thought it was the code but I realized that even internet examples present the same error, apparently the camera is not being activated , tried on several devices and browsers with the same result, does this happen to anyone else? 

[Example](http://expensive-abiding-brian.glitch.me/) 
![Screenshot_20220511-115724](https://user-images.githubusercontent.com/62685784/167905752-189f48a5-87a2-4b1d-9cd9-4d2167609137.png)

**Comment by Shackless** [comment]
Same here on my Pixel 6 Pro while trying to connect to a webserver running on my desktop. If I launch the page on the desktop with a webcam connected, everything works fine. If I disconnect the camera, I get the same error, even on Desktop. So yeah, seems like the camera on mobiles is not activated correctly.

**Comment by Shackless** [comment]
@underlabmx My problem was that I was trying to access a the page via http on my mobile. Apparently, the site has to be served using https or Chrome won't let it access the camera at all. Deploying to Netlify or GitHub Pages solved it for me.

**Comment by hiukim** [comment]
Yes, it requires https to obtain the webcam feed.
