### ISSUE TITLE
Plan to release Image Compiling Tool as a node application?

### ISSUE THREAD

**Issue by DDIncNick** [hiukim/mind-ar-js#183]
Was just curious if you plan to release the your Image Compiling tool for creating the .mind files as a node application? Or does this exist somewhere already? I have never heard of a .mind file type. Just curious it would be a lot easier for me personally to run it from node to compile all the targets I need. But I understand if this is not something you are interested in doing.

**Comment by hiukim** [comment]
Hi, unfortunately it's not possible to run in a node.js application because it requires running some webgl code on the browsers. If I have more free time, I might port that part of the code into regular js code. but that's actually not a simple task.

**Comment by DDincBrent** [comment]
Ah I see, well thank you very much for the info!

**Comment by hiukim** [comment]
Basically, the core part of the feature extraction. For example: https://github.com/hiukim/mind-ar-js/blob/master/src/image-target/detector/detector.js

**Comment by DDincBrent** [comment]
Gotcha, thank you! I am going to take a crack at it myself, and see if I can get something going.

**Comment by krsbx** [comment]
@DDincBrent I try to create the compiler in this [repo](https://github.com/krsbx/mind-ar-compiler), but as hiukum said need to convert the things that depends on webgl
