### ISSUE TITLE
Unable to see cursor entity inside a-camera

### ISSUE THREAD

**Issue by ShimantaBhuyan** [hiukim/mind-ar-js#184]
Thanks for this awesome library!
Was trying out some stuff and stumbled upon this potential issue. When I add a cursor entity inside the a-camera, it doesn't show up in my scene:
`
<a-camera 
                position="0 0 0" 
                look-controls="enabled: false"
            >
                <a-entity 
                    cursor
                    raycaster="far: 30; objects: .clickable" 
                    position="0 0 -0.75" 
                    visible="true"
                    geometry="primitive: ring; radiusInner: 0.02; radiusOuter: 0.03" 
                    material="color: black; shader: flat" 
                    animation="property: scale; startEvents: fusing; easing: easeInQuad; dir: alternate; from: 0.01 0.01 0.01; to: 0.02 0.02 0.02; dur: 2000" 
                    animation__color="property: components.material.material.color; isRawProperty: true; type: color; startEvents: fusing; easing: easeInQuad; from: white; to: orange; dur: 2000"
                    animation__scalemouseleave="property: scale; startEvents: mouseleave; easing: easeInQuad; dur: 2000; to: 0.01 0.01 0.01;"
                    animation__colormouseleave="property: components.material.material.color; isRawProperty: true; type: color; startEvents: mouseleave; easing: easeInQuad; dur: 2000; to: white;"
                >
                </a-entity>
            </a-camera>
`

**Comment by cdavisethar** [comment]
I'm also experiencing this issue. Did you ever find a fix?

**Comment by ShimantaBhuyan** [comment]
Unfortunately no :(

**Comment by hiukim** [comment]
seems stale. I'm closing it for now. Feel free to re-open if there is some new insight.
