### ISSUE TITLE
Can gltf model be fixed at the first recognized position?

### ISSUE THREAD

**Issue by lifthtt** [hiukim/mind-ar-js#185]
For example, arSystem.pause(true); a similar but slightly different function.

Can the AR model be fixed at the place where the AR model was first recognized, and even if the camera shows another place and goes back, can the AR model be kept at the place where it was first recognized?

help me plz TT

**Comment by sudharsans85** [comment]
Looking for same feature, Any ideas on how it can be achieved?

**Comment by demisquare** [comment]
One possible solution it could be to stop just the video with something like `document.querySelector("video").stop();`.

**Comment by sudharsans85** [comment]
Stopping the video takes the user out of AR experience - it will become a 3D model viewer
I guess native implementations like AR Core uses plane detection, Feature recognition..etc to achieve this
I see that worldMatrix is being updated continously depends on the orientation/position of the camera in real world
Is there any tweak/solution to achieve this - Without this our product team is not willing to accept it as AR solution 
@hiukim - Please suggest

**Comment by mrchantey** [comment]
@sudharsans85 yes I think you're right, the algorithm is already doing its best to track the original location of the image, ie 'keep the image at its first location', but would require a more general understanding like plane detection to have a stronger idea of where that place is.
