### ISSUE TITLE
Try Intereactive demo with Andriod  cellphone   video always black

### ISSUE THREAD

**Issue by jamess922** [hiukim/mind-ar-js#187]
Try [Intereactive demo](https://hiukim.github.io/mind-ar-js-doc/examples/interative) with Andriod  cellphone ,but video shows black . 
![微信图片_20220517132441](https://user-images.githubusercontent.com/28625879/168735296-f6986287-b1c9-46cb-9668-9490bac0d4c8.jpg)

Work fine with IOS

**Comment by gerickt** [comment]
same problem here

**Comment by endohendo** [comment]
same here any solution?

**Comment by hiukim** [comment]
stale. feel free to re-open if there is new insight.
