### ISSUE TITLE
Get the position of the marker

### ISSUE THREAD

**Issue by FlorianGauvrit** [hiukim/mind-ar-js#189]
Hi!
I would like to get the position of the marker when the event "targetFound" is detected. 
The goal is to get the position of my marker and then use it in a WebXR session. 

Thank you for your help!

**Comment by ompateldeveloper** [comment]
I found a tricky solution for this, add a a simple mesh to anchor and , you can get positions and rotations of same from that mesh
anchor.group.add(Box);

in animation loop:
console.log( Box.position )
