### ISSUE TITLE
Help needed: FaceMesh isn't working in Telegram Web Apps for Bots on Android

### ISSUE THREAD

**Issue by omegastripes** [hiukim/mind-ar-js#190]
I tried to launch [FaceMesh live demo](https://hiukim.github.io/mind-ar-js-doc/face-tracking-samples/three-facemesh.html) in [Web Apps for Bots](https://core.telegram.org/bots/webapps) on Android Telegram App, bot menu setup is simple, here are the steps:

![image](https://user-images.githubusercontent.com/3822668/169270441-e9215f3c-cae6-4d54-9c6e-9028eace2b4f.png)
![image](https://user-images.githubusercontent.com/3822668/169270469-f4c72d7f-d77f-489b-82f3-53d5c98df853.png)
![image](https://user-images.githubusercontent.com/3822668/169270495-0299585b-ef8d-4332-ba21-d844997c6b31.png)

After the page opened in chat with the bot and access to camera allowed, there is no feed from webcam:

![image](https://user-images.githubusercontent.com/3822668/169271394-40afc16f-4d3d-41d7-8866-d1d382ce4612.png)
![image](https://user-images.githubusercontent.com/3822668/169270718-2737b180-9460-4406-8c17-6b97d3269529.png)

[FaceMesh live demo](https://hiukim.github.io/mind-ar-js-doc/face-tracking-samples/three-facemesh.html) works perfectly when opened in Chrome on this device.

Is any additional page setup possible to make it work in Web Apps for Bots?

**Comment by hiukim** [comment]
The issue is stale. feel free to re-open if there is new insight.
