### ISSUE TITLE
Does it work with Unity??

### ISSUE THREAD

**Issue by nsmith1024** [hiukim/mind-ar-js#192]
Hello,

Im doing an AR project with Unity for the  Web and wanted to try this.

Can this work with Unity?

**Comment by krsbx** [comment]
@nsmith1024 so you want to use this in the webgl build? probably works, but not so sure

**Comment by FrankBevr** [comment]
Start with Vuforia.
Unity is a great for AR, but for WebAR it can be quite cumbersome.
If you want to make an AR App use Unity and deploy it on your android. Its super straight forward.

**Comment by hiukim** [comment]
I suspect it might requires some integration work. I mean, in theory the it should work but there are probably errors here and there.

There is no plan to `formally` support Unity webgl build at the moment. Of course it would be great if someone can work on this.

I'm closing this issue for now, until someone wants to work on it. Feel free to re-open
