### ISSUE TITLE
How to create Multi-Target image by myself?

### ISSUE THREAD

**Issue by KuoFeng-Wolf** [hiukim/mind-ar-js#193]
You really do great webAR project, and thanks for your demonstration.
I have one question. In your multi-target example, the "imageTargetSrc" was only *.mind file.
How can I build the mind file for multi-target project ?

**Comment by krsbx** [comment]
the `*.mind` file can contain more than one image since `mind-ar` will detect the `targetIndex` that match with the current `targetImage`. So, you can just put a lot of images in the `compiler` tool or just by creating a page dynamically base on the target image itself.

**Comment by taniya948** [comment]
how to create combined target.mind file
