### ISSUE TITLE
Effect composer - postprocessing

### ISSUE THREAD

**Issue by mancio2388** [hiukim/mind-ar-js#196]
Hi, is there anyone who has tried to use some postprocessing filter?
So instead of using the renderer.render function uses composer.render?
Like this:

`renderer.setAnimationLoop(() => {
composer.render();
//renderer.render(scene, camera);
});`

If i try to use effect composer, i get this error in console with a simple shader filter too.
This is the error:

`THREE.WebGLProgram: Shader Error 0 - VALIDATE_STATUS false Program Info Log: Fragment shader is not compiled......`

Is there a solution?
Thanks

**Comment by mancio2388** [comment]
Anyone are using postprocessing library with MindAR?
ref. https://github.com/pmndrs/postprocessing

**Comment by hiukim** [comment]
The issue is stale. feel free to re-open if there is new insight.
