### ISSUE TITLE
Opening the mind web application with an Android device 

### ISSUE THREAD

**Issue by Tikitaka02** [hiukim/mind-ar-js#198]
Hello, I have deployed your glasses/hat/earrings tryon html code by using glitch. When I open the deployed web page on chrome and google with my android device (Galaxy s10 lite), the glasses, hat, and earrings are located on the wrong places. I tried it with ios and windows laptop, and it worked perfectly fine. Do you know any potential reasons for this? I appreciate your answer in advance.

**Comment by hiukim** [comment]
should be fixed v1.1.5
