### ISSUE TITLE
Loading image on face tracking

### ISSUE THREAD

**Issue by mr339** [hiukim/mind-ar-js#199]
Can an image be loaded when face tracking rather than a gltf model?

**Comment by krsbx** [comment]
yes, it does possible, you can try it out by using this [repo](https://github.com/krsbx/mind-ar-react/blob/main/src/Examples/FaceTracking.tsx), I already made some component that can be used in React

to be note though, the mind ar that i use in that repo is different with this repo, but it should work fine as well using the one that hiukim made
