### ISSUE TITLE
Option for selecting external camera device

### ISSUE THREAD

**Issue by arpitAjnaLens** [hiukim/mind-ar-js#20]
I am running file on mobile browser, but my mobile is connected to HMD-(Head Mounted Display) which has inbuilt camera.
I want the application to select camera from HMD rather than normal phone's camera.

**Comment by hiukim** [comment]
In that case, you might need to do a custom build.

This is where the camera is selected, you could modify and run a build.
https://github.com/hiukim/mind-ar-js/blob/ba310848f10acf3941bdccd949b3120b14ddda96/src/aframe.js#L84
