### ISSUE TITLE
Performance Multi-Track Image-Tracking

### ISSUE THREAD

**Issue by rafhnw** [hiukim/mind-ar-js#200]
Is there any way to improve the performance of simultaneously tracking two image-targets? I'm using the max-track parameter, and displaying content has a huge delay especially, when I track only one target in that multi-track application.

**Comment by hiukim** [comment]
That's a limitation of the library. Will need to research on better algorithm to solve this. This is a definitely something that worths working on. 

I'm closing this issue for now. If someone with Computer Vision can help, we can re-open it.
