### ISSUE TITLE
Object movement is slow on face tracking demo

### ISSUE THREAD

**Issue by naonvl** [hiukim/mind-ar-js#201]
Hi, i'd love to use this library for my project, but after experience the face tracking demo it seems that the object movement didn't match with the head movement. There's always a delay to the object, and on android the object didn't placed correctly but on desktop it is correct the glasses is on the right place, but not on mobile. Is this still an issue or is it already fixed?

Thank you

**Comment by hiukim** [comment]
There is a tradeoff between stability and delay as discussed in this post below, if it helps:

https://hiukim.github.io/mind-ar-js-doc/quick-start/tracking-config
