### ISSUE TITLE
3D-Object keeps flickering

### ISSUE THREAD

**Issue by SabrinaBaumgartner** [hiukim/mind-ar-js#204]
https://user-images.githubusercontent.com/93661060/174621230-e42d1959-0719-437b-8875-7e1ed7d8f4c9.mp4

As you can see in the screen recording the 3D-Object somehow keeps flickering. I happens on both laptop and phone (iPhone 11), however it's worse when I use my phone. I´ve tried to calm it down by using the filter but it's only helping a bit.

Anyone got a clue what I can do about it?

(put my code in here without the "node_modules" folder because it's too big)
[ar.zip](https://github.com/hiukim/mind-ar-js/files/8941451/ar.zip)

**Comment by SabrinaBaumgartner** [comment]
Changed the missTolerance to "5" but now there's a mad jitter.

**Comment by DouglasLapsley** [comment]
Have you tried these settings? https://hiukim.github.io/mind-ar-js-doc/quick-start/tracking-config  Looks like maybe your warm up and miss tolerences could be tweaked a bit.
