### ISSUE TITLE
Virtual Tryon Fitting issue

### ISSUE THREAD

**Issue by rashid301** [hiukim/mind-ar-js#214]
The virtual try-on feature works great. But it changes the size of the model (e.g glass) to fit on the person's face.

* Is there a way to only change the position and rotation without affecting the real size.  
* How can we get the depth of the face from the camera and accordingly resize the object to see how the physical glass will fit on the person?

**Comment by hiukim** [comment]
Yes, the library will change the size relative to the detected face.  

I can see that could be an interesting use case. But at the moment, the library doesn't provide real world scale, i.e. cannot really specify real world units, like 10cm, etc.
