### ISSUE TITLE
Image Targets Compiler does not work

### ISSUE THREAD

**Issue by karandex** [hiukim/mind-ar-js#215]
Image Targets Compiler does not work

The progress is stuck at 0%
![image](https://user-images.githubusercontent.com/8975273/177935615-44153b15-eff3-4b7b-ae0b-15960c14cc27.png)

**Comment by hiukim** [comment]
which browser you use?

**Comment by romeodf** [comment]
i'm having the same problem, i used Chrome and Edge

**Comment by annamarthin** [comment]
Use Firefox. It solved the problem for me
