### ISSUE TITLE
Facemesh alignment fails if viewport is wide/landscape

### ISSUE THREAD

**Issue by Trott** [hiukim/mind-ar-js#216]
(Taking the Udemy course and it's super helpful. Thanks for that!)

Here's a live demo of issue: https://trott.github.io/homestar-facetracking/pompomface.html

....although you can use the MindAR facemesh demo code too as long as you have a wide viewport.

When the viewport is narrow relative to height, it works great. Here is a screenshot with my a 914x865 viewport.

<img width="918" alt="image" src="https://user-images.githubusercontent.com/718899/178108731-b9a06e63-6694-492a-97fe-cd2c3ecbbd9e.png">

However, it is misaligned if the viewport is wide. Here is a screen with a 1036x504 viewport.

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/718899/178108763-adf346a6-fba4-450f-91d1-3f44a66c40ee.png">

I am able to replicate this problem even with the MindAR demo code. A simple way to see it is to use the MindAR facemesh demo when your phone is in landscape.

**Comment by hiukim** [comment]
should be fixed v1.1.5
