### ISSUE TITLE
In face tracking,when my face keep moving,how can i get the real time position of my face on the screen

### ISSUE THREAD

**Issue by littleBelle** [hiukim/mind-ar-js#217]
Hi,hiukim,
In my object, use face tracking,and i hope when my face keep moving, i can get the real time position of my face on the acreen.dose this library has this events handling ?

Hope to get your reply, thank you

**Comment by hiukim** [comment]
The library updates the pose of the `a-entity` with `mindar-face-target` continuosly. It is a 3D coordinate relative to the scene though.  There is no 2D coordinates relative to the screen.
