### ISSUE TITLE
multi-targets crash mobile browser + many targets are problematic to compile targets.mind

### ISSUE THREAD

**Issue by HeimMatthias** [hiukim/mind-ar-js#22]
Hey

(first of: wonderful project, came here from ar.js and I am amazed by the ease of setup and stability in tracking).

I was thinking of using mind-ar-js to AR-enrich a book. This means ~50 targets have to be recognized by the app. I set up a test with only 6 targets and immediately Safari on iPhone X and Chrome on a Galaxy A5 crash. The multi-targets example app works on both devices - but it has only two targets. I managed to get it to load on my iPad Pro, but that is not what end users would use.

Is there any way of getting 10+ targets to work?

Moreover, is it necessary to put all the tracking targets into the same targets.mind-file? This seems to be the bottleneck here, as  even with only 6 targets it grew to 32MB. Moreover, they are difficult to compile and it would be hard to add or remove individual targets at a later point. One .mind-file per target would seem much easier to use and address in the app.

Any feedback or help is highly appreciated.

Best, Matthias

**Comment by hiukim** [comment]
~50 targets is probably too much for the library to handle unless we revamp to some new algorithms. But I guess 10 is possible with some optimization. 

What's the resolution of the images you use? Maybe reducing it could help.

One workaround for applications that require many targets is to separate them into different pages (or maybe just different .mind file as you suggested). Instead of detecting all of them at the same time, just load up the one you needed. It probably requires some UX design to guide users to select.

**Comment by HeimMatthias** [comment]
I've now successfully deployed a test-app with 44 targets. The crash on the mobile phones was actually because I used self-closing tags for `a-entity`. (i.e. `<a-entity id="target-0" mindar-image-target="targetIndex: 0"/>` instead of `<a-entity id="target-0" mindar-image-target="targetIndex: 0"></a-entity>`). This didn't work and meant that these tags ended up being nested inside each other in the DOM. I assume that the more powerful iPad could just handle the nested event-chain, but the others couldn't.

For the successful test, I had 44 images at 96dpi (each at about 600x800px), which seems to be just enough for target detection, but not enough for stable target-retention. It also won't find targets that contain text and graphics instead of photographs. The latter works only with higher resolution target-images.

Unfortunately, the *Image Targets Compiler* does not compile the image set with the higher resolution images. I've found previously that only the new Chromium based Edge can successfully compile larger image sets (who would have thought - curiously, it's also much faster than Chrome), but results are not consistent and crashes happen (with the same images) regularly but not always.

In the `console.log` I get the following message:
``` shell
WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost
3c6a9f77-4ea9-46a9-bb29-ffc4645e1db5:2 Uncaught Error: Failed to link vertex and fragment shaders.
    at 3c6a9f77-4ea9-46a9-bb29-ffc4645e1db5:2
    at iR.createProgram (3c6a9f77-4ea9-46a9-bb29-ffc4645e1db5:2)
    at 3c6a9f77-4ea9-46a9-bb29-ffc4645e1db5:2
    at 3c6a9f77-4ea9-46a9-bb29-ffc4645e1db5:2
    at hD.getAndSaveBinary (3c6a9f77-4ea9-46a9-bb29-ffc4645e1db5:2)
    at hD.runWebGLProgram (3c6a9f77-4ea9-46a9-bb29-ffc4645e1db5:2)
    at hD.compileAndRun (3c6a9f77-4ea9-46a9-bb29-ffc4645e1db5:2)
    at 3c6a9f77-4ea9-46a9-bb29-ffc4645e1db5:2
    at 3c6a9f77-4ea9-46a9-bb29-ffc4645e1db5:2
    at Rr.scopedRun (3c6a9f77-4ea9-46a9-bb29-ffc4645e1db5:2)
(anonym) @ 3c6a9f77-4ea9-46a9-bb29-ffc4645e1db5:2
createProgram @ 3c6a9f77-4ea9-46a9-bb29-ffc4645e1db5:2
(anonym) @ 3c6a9f77-4ea9-46a9-bb29-ffc4645e1db5:2
(anonym) @ 3c6a9f77-4ea9-46a9-bb29-ffc4645e1db5:2
getAndSaveBinary @ 3c6a9f77-4ea9-46a9-bb29-ffc4645e1db5:2
runWebGLProgram @ 3c6a9f77-4ea9-46a9-bb29-ffc4645e1db5:2
compileAndRun @ 3c6a9f77-4ea9-46a9-bb29-ffc4645e1db5:2
(anonym) @ 3c6a9f77-4ea9-46a9-bb29-ffc4645e1db5:2
(anonym) @ 3c6a9f77-4ea9-46a9-bb29-ffc4645e1db5:2
scopedRun @ 3c6a9f77-4ea9-46a9-bb29-ffc4645e1db5:2
tidy @ 3c6a9f77-4ea9-46a9-bb29-ffc4645e1db5:2
so @ 3c6a9f77-4ea9-46a9-bb29-ffc4645e1db5:2
_applyFilter @ 3c6a9f77-4ea9-46a9-bb29-ffc4645e1db5:2
detect @ 3c6a9f77-4ea9-46a9-bb29-ffc4645e1db5:2
(anonym) @ 3c6a9f77-4ea9-46a9-bb29-ffc4645e1db5:2
(anonym) @ 3c6a9f77-4ea9-46a9-bb29-ffc4645e1db5:2
scopedRun @ 3c6a9f77-4ea9-46a9-bb29-ffc4645e1db5:2
tidy @ 3c6a9f77-4ea9-46a9-bb29-ffc4645e1db5:2
so @ 3c6a9f77-4ea9-46a9-bb29-ffc4645e1db5:2
i @ 3c6a9f77-4ea9-46a9-bb29-ffc4645e1db5:2
onmessage @ 3c6a9f77-4ea9-46a9-bb29-ffc4645e1db5:2
hiukim.github.io/:1 WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost
```

Not sure whether this is helpful. It looks to me like a browser-timeout. Maybe I'll check whether inactivity in the window makes a difference.

However, it would be massively easier if it was possible to just drop individual pre-compiled `*.mind`-files into the compiler and it wouldn't have to do the entire work again, just process them into one bigger file. Alternatively, could you give me any advice on how I could go about uncompressing mind-files and putting them together myself?

At the moment, I don't think performance on mobile would actually be an issue. The 44-target test, with a 36MB mind-file runs smoothly on all the devices I tested. It's the compilation of the targets that is the problem.

**Comment by hiukim** [comment]
That's an interesting findings! I wouldn't expect it can cope with 44 targets, although there are still some practical issues as you mentioned. I'd love to see your application, if it is publicly accessible.

For manipulating the .mind file. It's not provided in the API and any published tools, but it's actually not that hard if you are up for some little hacking. 

You can import the .mind file and look at the content with a few lines of code:

https://github.com/hiukim/mind-ar-js/blob/ba310848f10acf3941bdccd949b3120b14ddda96/src/controller.js#L67-L69

https://github.com/hiukim/mind-ar-js/blob/ba310848f10acf3941bdccd949b3120b14ddda96/src/compiler.js#L75-L77

It's just a few array of compiled data, which you can manipulate and then export again.

https://github.com/hiukim/mind-ar-js/blob/ba310848f10acf3941bdccd949b3120b14ddda96/src/compiler.js#L59

**Comment by HeimMatthias** [comment]
Thanks a lot. This has been helpful too. I have, for the moment resolved the issue by manually fine-tuning my ar-target images. I've noticed that both compiler crashes and browser crashes happen mostly on overly complex images. For testing purposes I intentionally deployed this on as many border-line recognizable cases as possible.

My findings for target recognition are basically as follows (writing this down in case anyone finds this useful).

- Photographs are recognized immediately and even when not zoomed in. They make by far the best targets. 75dpi is enough for stable tracking.
- Vector images with clear details (but no overload of text) are recognized well, but need to almost fill the frame for recognition. Surprisingly, for those who - like me came here from ar.js - this means that marker-recognition is weaker than photo-recognition. I have not attempted one obvious use-case: similar patterns with differentiating details. For some graphics that seem clearly distinguishable to the eye, but might use somewhat muted colors, the only way to make the match can be to take an actual photo of the element with a camera phone and to use this for the target instead of a digital export of the graphic.
- Color does not seem to be differentiated at all (unless I am mistaken). This has obvious technical reasons. But it means that color should not be a distinguishing factor for your markers.
- Book pages, even when they have clearly distinguishing aspects such as colored boxes, title elements, etc. won't be recognized, no matter what. The only way to make these match is - I've found - to only use the title as the target image. The title will then produce a match, but only when scanned at close-up with the camera phone.

All in all, this works very well, as long as you're aware of the limitations. I will eventually come back here and post the result of my test. I will try to post more clearly technical issues, as I work on this.

**Comment by tfzxyinhao** [comment]
the feature points collected by the camera and submitting it to the back-end for matching can increase the limit on the number of targets
Is the workload heavy?

**Comment by KingRial** [comment]
Thank your for your informations!

By merging single pre-compiled ".mind" files into a big one, I was able to bypass the CONTEXT_LOST_WEBGL error and explore multitarget limits.

**Comment by kanzaky** [comment]
> Thank your for your informations!
> 
> By merging single pre-compiled ".mind" files into a big one, I was able to bypass the CONTEXT_LOST_WEBGL error and explore multitarget limits.

How did you do that? i would like to do something like that

**Comment by Naushikha** [comment]
@KingRial would love to see how merging multiple Mind files was implemented
