### ISSUE TITLE
GLTFLoader cannot be import in the ThreeJS Face example

### ISSUE THREAD

**Issue by Ariamangames** [hiukim/mind-ar-js#220]
I want to import a simple model and followed the three.js documentation
`import { GLTFLoader } from "./GLTFLoader.js";`

I took GLTFLoader from the original reference.
I get this error when loading

`Uncaught TypeError: Failed to resolve module specifier "three". Relative references must start with either "/", "./", or "../".`

what is the problem?

**Comment by hiukim** [comment]
Apparently `three` is missing. probably something wrong with your import.

**Comment by marianobastiUNRN** [comment]
Same as posted on #173
