### ISSUE TITLE
Custom UI  docs has a small syntax bug

### ISSUE THREAD

**Issue by ffd8** [hiukim/mind-ar-js#223]
Amaaazing lib! Unfortunately was running into an issue that every random time it works fine, others it doesn't... was guessing it's an issue about the loading of scripts (aframe being 2mb, mindar 1.2mb, p5 800k etc) = 5.4 mb..! Switching to check if the window is done loading then triggering the start, and thus needed to disable the built in uiloading, which on the [custom UI](https://hiukim.github.io/mind-ar-js-doc/examples/custom-ui#customize-the-ui) docs page, shows the syntax of:

```
<a-scene mindar-image="imageTargetSrc: ./targets.mind; uiError=no; uiLoading=no; uiScanning=no"/>
```

whereas, i guess an update in the lib is now requires:
```
<a-scene mindar-image="imageTargetSrc: ./targets.mind; uiError:no; uiLoading:no; uiScanning:no"/>
```

**Comment by hiukim** [comment]
fixed. thx for pointing out.
