### ISSUE TITLE
How to display play button on video for ios

### ISSUE THREAD

**Issue by MilosGlisovic** [hiukim/mind-ar-js#224]
Hi, I build image tracking with video to show, and all work great but in iOS I need button to play.
Can someone tell me how to display button on video and on click play the video?
Thank you
This is my js code:
`<script>  window.onload = function() {
   
            const sceneEl = document.querySelector('a-scene');
            const arSystem = sceneEl.systems["mindar-image-system"];
            const scene = document.querySelector("a-scene");
              
          
            
            // arReady event triggered when ready
            sceneEl.addEventListener("arReady", (event) => {
               console.log("MindAR is ready")
            });
              
          var targetVid = document.getElementById("backVideo");
            // detect target found
             const exampleTarget = document.querySelector('#backAR');
              exampleTarget.addEventListener("targetFound", event => {
                console.log("target found backAR");
                  targetVid.play();
              });
        
              // detect target lost
              exampleTarget.addEventListener("targetLost", event => {
                console.log("target lost backAR");
                  //targetVid.stop();
              });
              
          const VRButton = document.querySelector('#start-button');
            VRButton.addEventListener("click",event =>{
                
                 console.log("target lost backAR");
            });
                
         }
        
        
             
            </script>`

**Comment by hiukim** [comment]
That looks like a UI and implementation issue, no?  You can create some element (as button) and place it anywhere (maybe on top of your video).

I'm closing it for now. Let me know if I misunderstood your issue.
