### ISSUE TITLE
Threejs version to show what's in a div

### ISSUE THREAD

**Issue by marcusx2** [hiukim/mind-ar-js#225]
Hi @hiukim, do you know if it's possible to modify the [threejs example](https://hiukim.github.io/mind-ar-js-doc/more-examples/threejs-image) to show what's on a div instead of a threejs geometry? Basically I have some content in a div on the same page that I want to show in AR.

**Comment by hiukim** [comment]
There is a method `addCSSAnchor` instead of `addAnchor`. But I haven't had the chance to add that tutorial/example yet.

**Comment by marcusx2** [comment]
How do I use it? I tried this

```
const anchor = mindarThree.addCSSAnchor(0);
const content = document.getElementsByTagName('canvas')[0];
anchor.group.add(content);
```

but it didn't work. I keep getting the error

`mindar-image-three.prod.js:2 THREE.Object3D.add: object not an instance of THREE.Object3D. `

on the line `anchor.group.add(content);`

**Comment by positlabs** [comment]
Instead of trying to add the canvas object to a threejs object, you will need to create a texture from the canvas, and apply it to a plane (which subclasses Object3D)
