### ISSUE TITLE
webpack not recognized as an internal command

### ISSUE THREAD

**Issue by Wirivera** [hiukim/mind-ar-js#226]
I can't create a custom build, due to this error:

"webpack" is not recognized as an internal or external command, executable program or batch file.

Could you give me a guide on how to fix it?

**Comment by hiukim** [comment]
Did you install it?

**Comment by positlabs** [comment]
I think there should be some installation instructions. I added a PR for it after struggling for a while.
https://github.com/hiukim/mind-ar-js/pull/251/commits/92f4d634b1918c35ea568de5dfd5ef3e54bb5c66
