### ISSUE TITLE
How to display video in same size like image

### ISSUE THREAD

**Issue by MilosGlisovic** [hiukim/mind-ar-js#227]
Hi, can anybody know how to display video in same size like image in image tracking, when you track image from flayer, bilbords or other size? Thank you very much

**Comment by hiukim** [comment]
just resize the video accordingly. width=1 means same size of the target image

This page discuss this: https://hiukim.github.io/mind-ar-js-doc/quick-start/webpage

**Comment by MilosGlisovic** [comment]
I set it that way, but the height is not exactly the same as the picture, while the width is correct

` <a-video webkit-playsinline playsinline height="0.552" width="1" rotation="0 0 0" src="#backVideo" loop="true"></a-video>`

**Comment by hiukim** [comment]
You need to set the height relative to your target image aspect ratio. Read the last paragraph: https://hiukim.github.io/mind-ar-js-doc/quick-start/webpage

**Comment by MilosGlisovic** [comment]
Thank you very much, I would try this.
