### ISSUE TITLE
Playcanvas support

### ISSUE THREAD

**Issue by AVTPJ** [hiukim/mind-ar-js#229]
Would _love_ to have a Playcanvas-supported version of MindAR. Would you be able to provide a simple demo to just load the library in PC? https://playcanvas.com/

**Comment by Rechi86** [comment]
Same here. I would love to integrate into my Playcanvas project.
@hiukim Maybe you could provide us some hints on how to start such an integration (how to get the transformation matrix from the camer stream or else) and I might could help with the PC-side of things.

**Comment by positlabs** [comment]
I am just starting with the library, but in general I think it would be nice to have a super basic version that doesn't do any rendering, just tracking. It would be a "BYOR" (bring your own renderer) build.

**Comment by issacclee** [comment]
playcanvas support would be great. Am I right to assume it will be easy to achieve once mind-ar is fully decoupled from three.js?

**Comment by Rechi86** [comment]
I think so. A decoupled tracking, returning a transform of the marker would an ideal starting point.

**Comment by hiukim** [comment]
sorry, I've no plan to support PlayCanvas at the moment. In case someone wants to lead this development, feel free to re-open the issue.
