### ISSUE TITLE
Scanning screen does not come back after targetLost-event

### ISSUE THREAD

**Issue by HeimMatthias** [hiukim/mind-ar-js#23]
The scanning screen provides clear gui-feedback to the user that scanning is going on. As such, it is very helpful. However, once a target-match has been found, it won't come back.
Is there any way of making it show up again after a targetLost-event?

**Comment by hiukim** [comment]
@HeimMatthias Actually, I couldn't decide which one should be the default behaviour when I implemented that. Should the scanning screen only be shown the first time or not.

Will it be very annoying if the scanning screen show up every time when the tracking is lost like momentarily for a second or so?

Love to hear some feedback.

**Comment by HeimMatthias** [comment]
I think the most practical for users of the library would be to have a function with which to enable the scanning screen again.
I can see that it would be annoying if the screen came back every time the target is lost for a second, but the default behaviour will be different from project to project (and maybe even from target to target).
For example, in my sample project, I have targets that trigger a video to play - if I loose the target , for a fraction of a second, I clearly don't want the additional overhead for the scanning screen to to come back before the video continues. On the other hand, I also use targets that simply trigger a slide-in frame with additional links, and in this case I don't mind if the scanning screen comes back immediately; as the user may simply use the scanner to go to the next target to load a different information screen.

So, while it would be good to have a boolean loading option to change the default behaviour of the screen coming back or not, in my case it would be most useful to be able to do something like this programatically:
````
exampleTarget.addEventListener("targetLost", event => {
      setTimeout(function() {
          if (!arSystem.targetIsBeingTrackedAtTheMoment()) arSystem.showScanningScreen();
      }, 2000);
    });
````

(sorry, the function names are woefully inadequate, but I think you get the idea).

**Comment by diandrae** [comment]
Hi, wondering if anyone's got a solution/workaround to this?

**Comment by thauska** [comment]
`this.el.addEventListener('targetLost', () => {
            setTimeout(() => {
              return document.querySelector('a-scene').systems['mindar-image-system'].ui.showScanning()
            }, 1000)
 })`

work for me

**Comment by underlabmx** [comment]
> `this.el.addEventListener('targetLost', () => { setTimeout(() => { return document.querySelector('a-scene').systems['mindar-image-system'].ui.showScanning() }, 1000) })`
> 
> funciona para mi

I was just looking for this, the code looks very good, but it is not clear to me where to write it

**Comment by ffd8** [comment]
@underlabmx check out the [events-handling](https://hiukim.github.io/mind-ar-js-doc/examples/events-handling) demo see how/where to reference an 'exampleTarget' and catch when lost. 

ie something like :
```
const exampleTarget = document.querySelector('#example-target')
// detect target lost
exampleTarget.addEventListener("targetLost", event => {
	// console.log("target lost")
	setTimeout(() => { return document.querySelector('a-scene').systems['mindar-image-system'].ui.showScanning() }, 1000)
})
```
