### ISSUE TITLE
Failed to launch on mobile browser

### ISSUE THREAD

**Issue by stefanienobel** [hiukim/mind-ar-js#230]
I simply copied and paste your quick start code into VS Code and startet a live server. 
On my desktop browser everything works well. But when I try to access via mobile browser over LAN it says " Failed to launch :( - Looks like your device browser is not compatiple."

I tried different devices: IPad, IPhone, Samsung Galaxy Tab S7, but always the same result. 
With inspect devices I could find out:
- No DPDB device match
- getGamepad will noch require Secure Context
- Failed to recalculate device parameters

What I'm doing wrong?

**Comment by hiukim** [comment]
make sure you use https

**Comment by sonalipd** [comment]
facing the same issue..can you please explain how to check on mobile

**Comment by Jellybu** [comment]
for me it worked once i changed from http to https

**Comment by sonalipd** [comment]
can you tell what exactly you are writting 
eg : https://192.168.1.xx:port

**Comment by ahmed-khaled18** [comment]
I had an issue while using the Quick start code too on mobile using VScode local server or any local server, when i deployed the project on firebase it worked fine, so you have to deploy the project in order for it to work on mobiles
