### ISSUE TITLE
How can I control when the uiLoading and uiScanning first show up?

### ISSUE THREAD

**Issue by marcusx2** [hiukim/mind-ar-js#231]
@hiukim I read [this section](https://hiukim.github.io/mind-ar-js-doc/examples/custom-ui), however I was wondering if there was a way that could control when the uiLoading and uiScanning first show up? I don't want to override them, but I need to control when they first show up. This is the flow I need

1. Some splash screen shows up that I control
2. ui loading shows up. When loading finishes, it **does not** show uiScanning yet. Instead it goes to step 3.
3. Show some other random stuff on the screen that I control.
4. Show uiScanning and effectively starts scanning.

**Comment by hiukim** [comment]
In that case, you can't use the default. You will need to implement this custom logic using the events callback

**Comment by marcusx2** [comment]
That was quick :D. Yes, I was reading about the events callback. But I can't find anywhere how can I call the uiLoading and uiScanning. Can you give an example? Thanks.

**Comment by hiukim** [comment]
You can't call uiLoading and uiScanning. but you can copy the html and css of those and control them if needed. 

Or just implement your own. :)

**Comment by marcusx2** [comment]
Ah I see, got it. Thanks for the clarification. A little bit off topic, are there any new features coming to the library, or did it come to a halt?

**Comment by hiukim** [comment]
I personally don't have big plan at the moment. But if anyone wants to do something, I'm definitely happy to assist.
