### ISSUE TITLE
Black Video on Android

### ISSUE THREAD

**Issue by gerickt** [hiukim/mind-ar-js#232]
My code
https://glitch.com/edit/#!/elfin-muddy-brake

te black screen
![mindar-blackvideo](https://user-images.githubusercontent.com/4694035/182887225-d9ad5d34-1098-474c-865c-fa11898d14ea.jpeg)

I'm testing on android

**Comment by hiukim** [comment]
Does it work without MindAR?   I mean as a regular AFRAME application?

**Comment by endohendo** [comment]
same problem - any guidance greatly appreciated

**Comment by annamarthin** [comment]
Hi, I see black screen on Android, and white on iOS. 

`<html>

  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="apple-mobile-web-app-capable" content="yes">
    <script src="https://cdn.jsdelivr.net/gh/hiukim/mind-ar-js@1.1.5/dist/mindar-image.prod.js"></script>
    <script src="https://aframe.io/releases/1.2.0/aframe.min.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/hiukim/mind-ar-js@1.1.5/dist/mindar-image-aframe.prod.js"></script>
  </head>


  <body>
    <a-scene 
      mindar-image="imageTargetSrc: ./targets.mind;" 
      color-space="sRGB" 
      renderer="colorManagement: true, physicallyCorrectLights" 
      vr-mode-ui="enabled: false" 
      device-orientation-permission-ui="enabled: false"
      smooth="true"
      smoothCount="10"
      smoothTolerance="0.01"
      smoothThreshold="5">

      <a-camera 
      position="0 0 0" 
      look-controls="enabled: false">
      </a-camera>

      <a-entity mindar-image-target="targetIndex: 0">
        <a-video 
          src="cardanimate.mp4" 
          position="0 0 0" 
          height="0.6" 
          width="1" 
          mute="true"
          loop="true"
          autoplay="true"
          rotation="0 0 0"
          webkit-playsinline
          playsinline>
        </a-video>
      </a-entity>

    </a-scene>
  </body>
</html> `

**Comment by annamarthin** [comment]
Hi, I have the same problem. Black video on Android, white on iOS

**Comment by positlabs** [comment]
You should be able to autoplay the video with a few extra parameters.

`<video src="..." muted autoplay playsinline></video>`

**Comment by skyredmilad** [comment]
I have the same issue.
Some browser works but a few browsers such as Xiaomi and Android default browser didn't work
However, I use this code and it works for many browsers.

`        <div dangerouslySetInnerHTML={{
          __html: `
        <video
        webkit-playsinline
        playsinline
        muted
          id="video"
        >
          <source src="${videoUrl}"  type="video/mp4}"/>
        </video>,
      ` }}></div>`

**Comment by hiukim** [comment]
The issue is stale. feel free to re-open if there is new insight.

**Comment by luigimannoni** [comment]
The problem is that some android devices with more than one camera (and on different roms) might report a wrongly sorted camera list. Example, LineageOS lists cameras backwards on chrome so `facingMode = "environment"` might attach to a virtual/depth camera.

It can be solved by exposing the video constraints like the threejs counterpart does:
on `aframe.js:110`
```
    const constraints = {
      audio: false,
      video: {
        height: { ideal: 1920 },
        width: { ideal: 1080 },
      },
    };

    if (this.shouldFaceUser) {
      if (this.userDeviceId) {
        constraints.video.deviceId = { exact: this.userDeviceId };
      } else {
        constraints.video.facingMode = "user";
      }
    } else {
      if (this.environmentDeviceId) {
        constraints.video.deviceId = { exact: this.environmentDeviceId };
      } else {
        constraints.video.facingMode = "environment";
      }
    }
```

and on your Aframe project:

```
navigator.mediaDevices.enumerateDevices().then((devices) => {

  const videoDevices = devices.filter(
    (device) => device.kind === "videoinput"
  );
  console.log("Available video devices:", videoDevices);
  const cameraZero =
    videoDevices.find(
      (device) =>
        device.label.toLowerCase().includes("camera 0") &&
        device.label.toLowerCase().includes("back")
    ) || null;

  if (cameraZero) {
    const scene = document.querySelector("a-scene");
    scene.setAttribute(
      "mindar-image",
      `environmentDeviceId: ${cameraZero.deviceId}`
    );
  }
});
```
