### ISSUE TITLE
Can we choice camera when using a multi-camers smartphone

### ISSUE THREAD

**Issue by jamess922** [hiukim/mind-ar-js#234]
Is it possible to choose a camera when using a multi-camera phone? 
especially android phones
Some browsers choose the wrong camera

**Comment by hiukim** [comment]
programmatically choose?

**Comment by jamess922** [comment]
Maybe a button to choose the right camera

**Comment by hiukim** [comment]
added in v1.2.2. 
Please refer to this issue: https://github.com/hiukim/mind-ar-js/issues/105

**Comment by Nicholas003** [comment]
hi,How to create a multi-objective "*. mind" file
