### ISSUE TITLE
Questions regarding mind files.

### ISSUE THREAD

**Issue by marcusx2** [hiukim/mind-ar-js#235]
1- I want to have a function that takes a .mind file as parameter, and sets up the entities with` mindar-image-target` component (example: `<a-entity mindar-image-target="targetIndex: 0">`) at runtime

Is this possible, or do I need a second parameter with the number of images?

2- Can I retrieve from the .mind file, the name of the files that were used to create it?

3- Can I compile a .mind file at runtime? If possible, how can I do it? Or does the user always need to access [https://hiukim.github.io/mind-ar-js-doc/tools/compile/](https://hiukim.github.io/mind-ar-js-doc/tools/compile/) to compile it beforehand?

4- Is it possible to reference more than one .mind file in the html? If it's possible to reference only one .mind file with the mindar-image component, is it possible to switch .mind files at runtime? One .mind file can reference multiple images, so the idea here is that I'd be able to change the images I want to reference by grouping them in different .mind files.

Thanks @hiukim !

**Comment by langxiankui** [comment]
3. 
[./examples/image-tracking/compile.html](https://github.com/hiukim/mind-ar-js/blob/master/examples/image-tracking/compile.html)

**Comment by marcusx2** [comment]
@hiukim ?

**Comment by hiukim** [comment]
Hi, unfortunately the answers to 1,2,4 are all no.  You cannot change them at runtime.

**Comment by pranavkattel** [comment]
how do i create my own .mind file without going into mindarjs github website;s tool
@hiukim

**Comment by diaznannz** [comment]
Hi, I have 10 separate .mind files as image targets for MindAR. How can I combine these multiple target files into a single .mind file so I can use them all together in one project?
