### ISSUE TITLE
Errors in code-example "Events Handling"

### ISSUE THREAD

**Issue by HeimMatthias** [hiukim/mind-ar-js#24]
The source code example [Events Handling](https://hiukim.github.io/mind-ar-js-doc/examples/events-handling/) in the documentation has a couple of mistakes:
- The example on the page (not the one linked under demo) links to version ´mind-ar-js@0.3.1´ of the script. However, the unpause() function has only been added with version 0.3.2
- The code example `arSystem.pause(true); // pause AR and video` is incorrect - the parameter needs to be `false` to stop AR and freeze the video.

Keep up the good work. This is such a cool library!

**Comment by hiukim** [comment]
@HeimMatthias  Thanks for pointing it out! Will fix that.

**Comment by hiukim** [comment]
fixed
