### ISSUE TITLE
How can i edit the .mind file or target image ?

### ISSUE THREAD

**Issue by turkyden** [hiukim/mind-ar-js#247]
How can i edit the .mind file or target image ?

**Comment by hiukim** [comment]
why do you want to remove red dots?

**Comment by turkyden** [comment]
> why do you want to remove red dots?

Because I want to use mindjs to identify similar objects of the same class.

**Comment by hiukim** [comment]
use a generic background image as the target then?

**Comment by turkyden** [comment]
OK, thanks your help, i will check it.

**Comment by turkyden** [comment]
i have to good idea, Compile the target image just in time (AOT) without `.mind`.

username ---> ${username}.png -----> compiler.compileImageTargets ---> compiler.exportData ----> compiler.importData(buffer)
