### ISSUE TITLE
Camera is not really switched off after triggering arSystem.pause()

### ISSUE THREAD

**Issue by HeimMatthias** [hiukim/mind-ar-js#25]
Calling arSystem.pause(false) switches off the camera feed in the a-frame, but the camera remains active. At least on iOS, the status-light remains switched on. For user-security reasons it would be good if it could be switched off completely during pause, or at least optionally. Especially as the camera is also a drain on energy consumption.

**Comment by hiukim** [comment]
@HeimMatthias Yes, `the arSystem.pause(false)` function translate to `video.pause()`, which keeps the video so the light indicator will still be on.

If you want to have it completely switched off, you can call `arSystem.stop()`, which should stop the video completely. and then you can call `arSystem.start()` again. There is still a bit of extra overhead when restart, but I think should be much faster than the first time.

**Comment by HeimMatthias** [comment]
Thanks, I'll try that.
