### ISSUE TITLE
mindar-image.prod.js:2 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'dummyRun') 

### ISSUE THREAD

**Issue by rafelis1997** [hiukim/mind-ar-js#256]
Hello, i'm trying to use this with Vite but i'm getting this error

`
mindar-image.prod.js:2 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'dummyRun')
    at Controller.dummyRun (mindar-image.prod.js:2:1147635)
    at NewSystem._startAR (mindar-image-aframe.prod.js:1:3059)
`

With create-react-app works fine, I think it's a compiler issue on the lib maybe

**Comment by hiukim** [comment]
The issue is stale. feel free to re-open if there is new insight.
