### ISSUE TITLE
keep on screen

### ISSUE THREAD

**Issue by Khodour** [hiukim/mind-ar-js#26]
its it possible to keep object on screen after losing the marker ? and the object will set it self in the middle of the screen in front of the camera !

**Comment by hiukim** [comment]
@Khodour 

Unfortunately, the library doesn't support this behaviour at this point. One option I can think of is to utilize the `targetLost` event, and then display another static object at the center.   Then when `targetFound`, you switch back.

The transition might be odd, I'm not sure.
