### ISSUE TITLE
Test invisible until camera distant from target

### ISSUE THREAD

**Issue by solosails** [hiukim/mind-ar-js#261]
Hi there (first thanks for releasing this code!)

I have been trying your advanced interactive example here https://hiukim.github.io/mind-ar-js-doc/samples/advanced.html

All great, however, the text linked to the buttons (showInfo) only displays when the camera is taken quit a long way away from the target.

This happens for me on ios and android mobiles on all browsers (Chrome, Safari etc) . Interestingly, does not happen when testing on a Windows PC using a webcam in all browsers. 

Any ideas? 

Many thanks, Andrew

**Comment by hiukim** [comment]
Probably it's just because the position of the text is bad. If you update the text position `depth` to be more align with the card, then it should be fine.
