### ISSUE TITLE
Buttons and Images are shrunk on IOS and don't work

### ISSUE THREAD

**Issue by QennNg** [hiukim/mind-ar-js#262]
Hi, I got an iPhone recently and wanted to see how the ar looks on ios. When I loaded up the page, I found that the buttons and images got shrunk on ios and somehow causes it to not function properly. I can't click on any of the buttons and therefore have no interactability. This issue does not happen when I load the page on android. 

![IMG_0036](https://user-images.githubusercontent.com/21268945/194930211-f566ad44-e5c0-4cd5-82e2-fe9924255a2f.PNG)

This is a screenshot from IOS

![Screenshot_20221010-185920_Chrome](https://user-images.githubusercontent.com/21268945/194930342-b3818271-da73-47d4-a60a-09c4705412ed.jpg)
This is a screenshot from Android

I'm not sure how to solve this issue/bug. Any help would be greatly appreciated.

Thanks, Qenn

**Comment by hiukim** [comment]
The issue is stale. feel free to re-open if there is new insight.
