### ISSUE TITLE
Mindar in react

### ISSUE THREAD

**Issue by Arslan-Uzi** [hiukim/mind-ar-js#264]
Hi there! I am trying to use mindar in react and I want to use mindar-face for face tracking. However, I am facing an issue and need your help. 

Following is the image where I used mindar-face in a-scene 
![image](https://user-images.githubusercontent.com/61595007/195977808-75213bb0-3030-475b-a0a3-cc0459975005.png)

But I am getting this error  
![image](https://user-images.githubusercontent.com/61595007/195978284-3963e0c6-1092-467a-9b1b-91612f9ae87f.png)

Your help would be highly appreciated.

**Comment by tranphuongthao2405** [comment]
if you are using react ver 18, then downgrade to ver 17, I'm facing similar issue with image tracking, but using react ver 17 works for me

**Comment by hiukim** [comment]
You can refer to this example: https://github.com/hiukim/mind-ar-js-react
