### ISSUE TITLE
Image Tracking in ReactJS

### ISSUE THREAD

**Issue by taican-1002** [hiukim/mind-ar-js#265]
I faced some problems when using **Image-tracking** with **Reactjs**. Specifically, when I call the **api** and map to the interface, scanning the image does not show the 3D model. While I get the link directly from github, the scan still has the 3D model. I don't know what is the error happening here. Hope to get help from everyone.

**Comment by hiukim** [comment]
You can refer to this example: https://github.com/hiukim/mind-ar-js-react
