### ISSUE TITLE
Hello, what can I do if I can't open it on ios WeChat browser

### ISSUE THREAD

**Issue by bxiaotao** [hiukim/mind-ar-js#267]
Hello, what can I do if I can't open it on ios WeChat browser. No problem with Android WeChat browser

**Comment by shikaiguo** [comment]
It requires manually running video.play()

**Comment by magixmin** [comment]
The Same Problem like youo .

> bxiaotao

**Comment by bububear** [comment]
> It requires manually running video.play()

兄弟，能否贴一下demo？
Brother, can you post a demo?
