### ISSUE TITLE
Face-Tracking offset on Android Chrome

### ISSUE THREAD

**Issue by FireDragonGameStudio** [hiukim/mind-ar-js#268]
Hi, I just tried the try-on example and it runs flawless within Chrome on PC. But when I test on my Android 13 device (Pixel 5) with Chrome, I get a strange Y offset on my 3D geometry. Face-Tracking itself works. I attached a screenshot for showing this issue.

Thank you for your help :)

Best regards,
Max

![Screenshot_20221020-115159](https://user-images.githubusercontent.com/23502690/196918659-47d8af8a-d604-4351-a23a-2342c89ecb72.png)

**Comment by hiukim** [comment]
which version of mindAR are you using? I thought it's fixed in v1.1.5

**Comment by FireDragonGameStudio** [comment]
I tried the example from the docs (https://hiukim.github.io/mind-ar-js-doc/face-tracking-samples/tryon.html) which are using 1.1.5

**Comment by marcusx2** [comment]
I have the same issue. Face tracking not working on Android Chrome. The offset is even bigger than what that picture shows, also using latest version.

**Comment by hiukim** [comment]
duplicate https://github.com/hiukim/mind-ar-js/issues/316
