### ISSUE TITLE
Video won't stop

### ISSUE THREAD

**Issue by graboid0110** [hiukim/mind-ar-js#269]
Hey hukkim!
Thank you for your work! For me this is something new. I'm just starting to learn different programming languages. And I am very interested in your project. In your example: https://hiukim.github.io/mind-ar-js-doc/examples/interative/ the video doesn't stop when the target is lost. I tried to fix this for a long time, but my knowledge is not enough yet. could you explain how to catch this video and pause or at least stop. Thanks in advance!

**Comment by hiukim** [comment]
you can pause the video using the `targetLost` event. Ref: https://hiukim.github.io/mind-ar-js-doc/examples/events-handling#targetfound-and-targetlost
