### ISSUE TITLE
[Bug][firefox] Target Compiler cannot compile image

### ISSUE THREAD

**Issue by Ynohtna-Fr** [hiukim/mind-ar-js#27]
When I try to compile an image from the targetCompiler _(https://hiukim.github.io/mind-ar-js-doc/tools/compile/)_ it failed at 50%.

I'm using Firefox

I tried with 2 images without success. Here is the error from the console if it can help.

![image](https://user-images.githubusercontent.com/45896947/116806871-27d54400-ab30-11eb-93b0-9ba3b37344bf.png)

I tried with this image : 
![Recettes-Repas-de-famille](https://user-images.githubusercontent.com/45896947/116806899-49cec680-ab30-11eb-9a4c-4fb0e222922c.jpg)
And this one : 
![price](https://user-images.githubusercontent.com/45896947/116806908-56531f00-ab30-11eb-9b2e-ed0f5444dac3.jpg)

Any idea where I can compile file other than the website ?

**Comment by Ynohtna-Fr** [comment]
I tried with chrome. Worked well, so seem's like it's broken only with firefox

**Comment by hiukim** [comment]
fixed
