### ISSUE TITLE
Using mindar with Tensor flow segmentation 

### ISSUE THREAD

**Issue by Mrbside** [hiukim/mind-ar-js#270]
I wanna make body segmentation with the face tracking feature, using tensor flow and body-pix model.

https://towardsdatascience.com/virtual-background-in-webcam-with-body-segmentation-technique-fc8106ca3038

Would the AR feature still work if I apply this to the camera?

**Comment by hiukim** [comment]
I can't tell for sure. I would guess the answer depends on at which point do you apply that filter. If you pass the raw video the mindar, then I don't see any difference it will caused.  If you pass the processed video to mindar, I guess it would still work because the human face is still there
