### ISSUE TITLE
Multiple image targets compiler issue

### ISSUE THREAD

**Issue by BartCheng** [hiukim/mind-ar-js#271]
Hello @hiukim 

I using 24 images on image targets compiler,
most image can track greate,
but there are two pictures in different order and one cannot appear.

**Comment by neogruh2405** [comment]
I'm facing the same issue, I'm using 6 QR code images, 2 of them can not show up, 1 is a black card

**Comment by hiukim** [comment]
does the two pictures look alike?

**Comment by BartCheng** [comment]
@hiukim 
the two pictures not look alike, 
but size is different.

Example：
1. 800x600
2. 600x800

I finally figured out a solution, it worked after resizing the two images to the same size.

**Comment by hiukim** [comment]
I see. Thanks for letting us know.
