### ISSUE TITLE
"Offline" Image Targets Compiler

### ISSUE THREAD

**Issue by DikkeryDok** [hiukim/mind-ar-js#282]
Not an issue, but rather a tool feature request.

I travel via trains and ride the metro a lot, where stable internet connection is really hard to achieve. Using existing targets compiler in such conditions is an absolute nightmare. Is there any chance for an offline compiler? Like node.js version for ar.js? I think a lot of people would appreciate such feature. Thanks for the answer in advance

**Comment by dtboy1995** [comment]
hi bro in example https://github.com/hiukim/mind-ar-js/blob/master/examples/image-tracking/compile.html

**Comment by veterinarypathology3d** [comment]
> hi bro in example https://github.com/hiukim/mind-ar-js/blob/master/examples/image-tracking/compile.html
Hi dtboy1995,
How to run it? as offline.
need a small tutorial.
