### ISSUE TITLE
 Any plan on supporting hand tracking or VOT of wrist ?

### ISSUE THREAD

**Issue by aliwangzai** [hiukim/mind-ar-js#291]
Any plan on supporting hand tracking or VOT of wrist ? please @hiukim  :)

**Comment by hiukim** [comment]
I don't, haha.  But if anyone is interested to lead, I'm happy to assist.

**Comment by aliwangzai** [comment]
That's ok , any idea how to implement this , i am new to this ,but i 'd like to have a try 😃
