### ISSUE TITLE
Smoothing control

### ISSUE THREAD

**Issue by TeMa183** [hiukim/mind-ar-js#293]
Hey guys, there is a problem with the smoothing video, which is being displayed over the marker @hiukim 

used the recommended filterMinCF:0.1; filterBeta: 10 "warmupTolerance: 1" and "missTolerance: 1", however no success

https://user-images.githubusercontent.com/117938899/202874023-2d38b491-d996-4f4b-96c9-19ac7a1270be.MP4

**Comment by arslc** [comment]
@TeMa183 Try this:
`filterMinCF: .001` and `filterBeta: 1`
or try self variant params, mayb .0001 & .01 or others (find best for ur app)

**Comment by TeMa183** [comment]
@arslc I'm sorry, could you please check my code?^^
As I'm not sure I use these tags properly(

**Comment by TeMa183** [comment]
@arslc Thanks, works much better!
