### ISSUE TITLE
[bug report] arSystem.pause() pauses video feed as well

### ISSUE THREAD

**Issue by marcusx2** [hiukim/mind-ar-js#296]
According to the [docs](https://hiukim.github.io/mind-ar-js-doc/examples/events-handling), arSystem.pause() should only pause the ar engine, not the video feed. But here it pauses both.

**Comment by marcusx2** [comment]
The issue is that this line in the documentation `arSystem.pause(true); // pause AR and video` is wrong. Actually, by passing true the video **doesn't** pause. Without true it pauses. I guess it's just a documentation error.

**Comment by hiukim** [comment]
thx for reporting

**Comment by hiukim** [comment]
fixed, thx.
