### ISSUE TITLE
Image target tool fault

### ISSUE THREAD

**Issue by ckbsbal** [hiukim/mind-ar-js#3]
Your image target tool is not working. After uploading the photo nothing is happening after clicking on start button. I had wait for around 30 minutes nothing was happened

**Comment by hiukim** [comment]
can you open the developer console and see any error messages?

**Comment by ckbsbal** [comment]
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: webpack:///./node_modules/aframe/dist/aframe-master.js?
Source Map URL: aframe-master.js.map

**Comment by hiukim** [comment]
I think you can ignore that warning.

**Comment by ckbsbal** [comment]
still not working
kindly plz recheck your web tool

**Comment by hiukim** [comment]
Unfortunately I don't have a window platform to fix it. If you have a mac or linux, maybe you can use those. Otherwise, you could also try using your ios/android phones/tablets to try.

**Comment by sunshichen** [comment]
I have another error shows that:

Uncaught (in promise):

Event {isTrusted: true, type: "error", target: null, currentTarget: null, eventPhase: 0, …}
bubbles: false
cancelBubble: false
cancelable: false
composed: false
currentTarget: null
defaultPrevented: false
eventPhase: 0
isTrusted: true
path: [img]
returnValue: true
srcElement: null
target: null
timeStamp: 6867.7700001280755
type: "error"
__proto__: Event

I'm  using Ubuntu, chrome however.

**Comment by ragavendranbala** [comment]
![image](https://user-images.githubusercontent.com/32410475/101906253-ac094800-3bde-11eb-8250-4a53a486d5e3.png)
@hiukim having the same issue on my firefox.

**Comment by hiukim** [comment]
@ragavendranbala Thanks for reporting. 

Please follow this issue for updates. https://github.com/hiukim/mind-ar-js/issues/8

**Comment by hiukim** [comment]
@ragavendranbala @ckbsbal 

I have just finished a big revamp, removing GPU.js completely. Hopefully it will solve a lot of these problems.

If you guys could try again with your devices (whatever devices you have, haha), that would be nice!

**Comment by patrickoshaughnessey** [comment]
I haven't been able to get the compile to work on Mac or iOS. 

Mac console::
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/115180/106203385-eb84f700-6180-11eb-82f6-307c2a522b36.png">

iOS console
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/115180/106203326-d14b1900-6180-11eb-9536-c7213dfacfdb.png">

**Comment by hiukim** [comment]
@patrickoshaughnessey the Mac one might be loading. What's the resolution of your image?
