### ISSUE TITLE
Keeping the object in front of camera

### ISSUE THREAD

**Issue by MatHeartGaming** [hiukim/mind-ar-js#30]
Hi, I'm new to mind-ar-js and Javascript. I have to create an AR experience where after having detected the target the AR experience starts, and I want it to continue even after the target is lost. Specifically, I have a video playing, and when I lose the target the audio keeps playing but the video is no longer visible, so I want the whole a-entity to be retained on screen. This is a snippet of the code I'm using. I'll be glad for any help!

```
AFRAME.registerComponent('mytarget-one', {
        init: function () {
          this.el.addEventListener('targetFound', event => {
            console.log("target found");
              setTimeout(() => {
                
                  setTimeout(() => {
                    showInfo();
                  }, 100);
              }, 100);

          });
          this.el.addEventListener('targetLost', event => {
            console.log("target lost");
            //stopInfoOne();
          });
          this.el.emit('targetFound');
        }
});
```

```
<a-scene mindar="imageTargetSrc: multitargets.mind; showStats: false;" embedded color-space="sRGB" renderer="colorManagement: true, physicallyCorrectLights" vr-mode-ui="enabled: false" device-orientation-permission-ui="enabled: false">
       
        <a-assets>...</a-assets>

 <a-camera position="0 0 0" look-controls="enabled: false" cursor="fuse: false; rayOrigin: mouse;" raycaster="far: 10000; objects: .clickable"></a-camera>
```

```
<a-entity id="mytarget-one" mytarget-one mindar-image-target="targetIndex: 1">
          <a-video id="paintandquest-video-link_wear" webkit-playsinline playsinline muted autoplay width="1" height="0.552" position="0 0 0.2"  ></a-video>
          <a-image id="paintandquest-preview-button" class="clickable" src="#paintandquest-preview" alpha-test="0.5" position="0 0 0.25" height="0.552" width="1">
          </a-image>
          <a-image id="linkedin" class="clickable" src="#icon-profile" position="-0.42 -0.5 0" height="0.15" width="0.15"
        ></a-image>

        <a-image  id="facebook" class="clickable" src="#icon-web" alpha-test="0.5" position="-0.14 -0.5 0" height="0.15" width="0.15"
        ></a-image>

        <a-image  id="web" class="clickable" src="#icon-email"  position="0.14 -0.5 0" height="0.15" width="0.15"
        ></a-image>

        <a-image  id="contact" class="clickable" src="#icon-location"  position="0.42 -0.5 0" height="0.15" width="0.15"
        ></a-image>
      </a-entity>
```

**Comment by kalwalt** [comment]
Hi @MatHeartGaming in targetLost event listener you should set the **object3D.visible** to `true`, in this way the object will be always visible.

**Comment by MatHeartGaming** [comment]
> Hi @MatHeartGaming in `targetLost` event listener you should set the **object3D.visible** to `true`, in this way the object will be always visible.

That doesn't seem to work. What should I set to visible? My a-entity? Should I do
`document.querySelector("mytarget-one").setAttribute("visible", true);`
is that what you were referring to?
Thanks in advance.

**Comment by Ebeleh** [comment]
> > Hi @MatHeartGaming in `targetLost` event listener you should set the **object3D.visible** to `true`, in this way the object will be always visible.
> 
> That doesn't seem to work. What should I set to visible? My a-entity? Should I do
> `document.querySelector("mytarget-one").setAttribute("visible", true);`
> is that what you were referring to?
> Thanks in advance.

did you find a solution?

**Comment by Ebeleh** [comment]
> Hi @MatHeartGaming in `targetLost` event listener you should set the **object3D.visible** to `true`, in this way the object will be always visible.

where I need to add this code?

**Comment by hiukim** [comment]
I'll close this issue for now.

The library doesn't officially support this behaviour at the moment. However, it's possible to customize the aframe wrapper to achieve that. 

I have updated the doc to include a section giving a high level guide on digging deeper to access the core API: https://hiukim.github.io/mind-ar-js-doc/core-api
