### ISSUE TITLE
[bug report] Multiple Tracks doesn't work with same target index

### ISSUE THREAD

**Issue by marcusx2** [hiukim/mind-ar-js#301]
If you take [this example](https://hiukim.github.io/mind-ar-js-doc/examples/multi-tracks), and change the `targetIndex` from the second image target entity from 1 to 0

```
BEFORE
<a-entity mindar-image-target="targetIndex: 1">
        <a-gltf-model rotation="0 0 0 " position="0 -0.25 0" scale="0.05 0.05 0.05" src="#bearModel" animation-mixer>
      </a-entity>
```
```
AFTER
<a-entity mindar-image-target="targetIndex: 0">
        <a-gltf-model rotation="0 0 0 " position="0 -0.25 0" scale="0.05 0.05 0.05" src="#bearModel" animation-mixer>
      </a-entity>
```
and try to track 2 raccoon images, it won't work. The scanning visual disappears, indicating that the raccoon images were detected, but no models showed up. I expected 1 raccoon to show up on top of one of the raccoon images, and 1 bear to show on top of the other raccoon image.

Maybe it's not a bug and works as intended, but it really seems like a bug since it looks like the raccoon images were detected, the models just don't show. Besides, if it's working as intended, can't you change so that multiple image targets of the same target index can also be tracked? I don't see why this can't be done.

@hiukim Please clarify if this is intended behavior and if it will be changed or not. Thanks!

**Comment by marcusx2** [comment]
I can make it work if I compile the raccoon image twice and still use `targetIndex 0` and `targetIndex1` instead of having 2 `targetIndex 0`
![image](https://user-images.githubusercontent.com/5656275/204140607-6e4f3707-78e9-4963-be61-3b931f809d6b.png)

Maybe it's by design after all, although a bit counter-intuitive and wasteful. If I want to track multiple images that are all the same, I need to compile it multiple times.

**Comment by hiukim** [comment]
It's not really a bug, but It is simply not able to track multiple instances of the same targets.
