### ISSUE TITLE
On Multi Target Image Tracking click on a model not work

### ISSUE THREAD

**Issue by micfio** [hiukim/mind-ar-js#306]
Hello I ahv etis scriopt event code :`<script>
      document.addEventListener("DOMContentLoaded", function() {
        const iguanosound = document.querySelector("#sound1");
		const iguanotarget=document.querySelector("#iguano-target");
	// detect click event
	iguanosound.addEventListener("click", event => {
	  alert("i am here!"); 	
	  let audio = document.querySelector("#iguano-wav");
	  audio.play();
	});
	// detect target found
	iguanotarget.addEventListener("targetFound", event => {
	  alert("target found");
	  
	});
	
      });
    </script>`

`<audio id="iguano-wav" src="sound/iguano.wav"></audio>`

`<a-camera position="0 0 0" look-controls="enabled: false" cursor="fuse: false; rayOrigin: mouse;" raycaster="far: 10000; objects: .clickable"></a-camera>`

`<a-entity id="iguano-target" mindar-image-target="targetIndex: 1">
        <a-entity geometry="primitive: sphere;radius:2;" material="color: #feb3c7; src:#sky; transparent:false; opacity:0.7;" position="0 0 -1" scale="1 1 1" rotation="0 0 0" shadow="receive:false;cast:false" visible="true"></a-entity>
        <a-gltf-model class="clickable" rotation="0 0 0 " position="0 0 0.1" scale="0.1 0.1 0.1" src="#iguano"
          animation-mixer
        ></a-gltf-model>
        <a-gltf-model id="sound1" class="clickable" rotation="0 15 0 " position="0.3 -0.7 0.1" scale="0.01 0.01 0.01" src="#speaker" animation-mixer ></a-gltf-model>
        </a-entity>`

The click event is newer fired.

**Comment by hiukim** [comment]
Can you double check whether it works without mindAR first, to make sure it's not an aframe issue?  Just create a standard aframe scene without "mindar-image"

**Comment by hiukim** [comment]
fixed in v1.2.2
