### ISSUE TITLE
image tracking and face tracking on the same app?

### ISSUE THREAD

**Issue by marcusx2** [hiukim/mind-ar-js#307]
Can I have an app with both image tracking and face tracking functionalities, or can I only use one of them? I can see from the docs on the event handling part that both image tracking and face tracking have the arSystem variable, but on the facetracking I can switch the camera and on the image tracking I can't. Are they actually different, can I have both or must I choose to have an image tracking experience **or** a face tracking experience? Thanks!

**Comment by hiukim** [comment]
You cannot run both at the same time

**Comment by marcusx2** [comment]
But can you stop one and start the other, on the same app?

**Comment by hiukim** [comment]
@marcusx2 I haven't tried that, but I think it's possible.

**Comment by viswongdev** [comment]
I have both example snippets on the same page. They are not running at the same time, but the video changes from fullscreen when there is only one AR system on the page. When both are present, the video appears at the top of the page, leaving a blank black space at the bottom. Any idea?
