### ISSUE TITLE
what do I need to do to make object3D.visible = true after loss of target picture?

### ISSUE THREAD

**Issue by Ebeleh** [hiukim/mind-ar-js#31]
I know that I need to add some code here:

```
exampleTarget.addEventListener("targetLost", event => {
          console.log("target lost");
});

```
i tried to add this:         
`  exampleTarget.addEventListener("targetLost", event => {
          arSystem.el.object3D.visible = true;
          console.log("target lost");
});
`
but it didnt work

**Comment by hiukim** [comment]
@Ebeleh It's not `arSystem.el`. Probably get the `el` of the `exampleTarget`. I don't have the code right away, but that's the idea. 

Also, I'm not entirely sure this approach will work properly for the current production build. For sure, something like this can be done but just that this use case wasn't being considered before and I'm not sure the behaviour is expected in the current production release.  If that doesn't work, then will need to customize the source code and rebuild the library.

**Comment by Ebeleh** [comment]
> @Ebeleh It's not `arSystem.el`. Probably get the `el` of the `exampleTarget`. I don't have the code right away, but that's the idea.
> 
> Also, I'm not entirely sure this approach will work properly for the current production build. For sure, something like this can be done but just that this use case wasn't being considered before and I'm not sure the behaviour is expected in the current production release. If that doesn't work, then will need to customize the source code and rebuild the library.

I added the function to mindar.prod.js : 
```
AFRAME.registerSystem("mindar-system", {
...
 object3DSetVisible: function(value){
    console.log("value visible set");
    this.el.object3D.visible = value;
}, 
...
```
and called it: 

`exampleTarget.addEventListener("targetLost", event => {
 arSystem.object3DSetVisible(true); 
});`

but it doesn't work...

**Comment by hiukim** [comment]
I'll close this issue for now.

The library doesn't officially support this behaviour at the moment. However, it's possible to customize the aframe wrapper to achieve that. 

I have updated the doc to include a section giving a high level guide on digging deeper to access the core API: https://hiukim.github.io/mind-ar-js-doc/core-api
