### ISSUE TITLE
[image-target] web worker instance registered in the controller stays in browser after removing the a-scene element from the DOM

### ISSUE THREAD

**Issue by jotatoledo** [hiukim/mind-ar-js#313]
![image](https://user-images.githubusercontent.com/20740204/207390849-07fb0f59-4434-47bb-ab2f-062657283422.png)

While working inside a relatively simple react SPA using the library, I noticed that multiple mount/unmounts of the same component with a `<a-scene mindar-image=....>....</a-scene>` results in multiple workers not being disposed, which finally leads to a very slugish performance of the app when the scene is rendered

**Comment by jotatoledo** [comment]
Just noticed in a locally patched v1.1.5 that despite the changes in #314 my application still becomes very sluggish after mounting/unmounting the scene as described in the issue. @hiukim any hints as to what elements could be causing this? seems to be some sort of mem leak/resources not been disposed when appropiate.

**Comment by hiukim** [comment]
Can you confirm the issue is caused by mounting/unmounting?   There is no leak if you keep running the app without mounting and unmounting? @jotatoledo

**Comment by jotatoledo** [comment]
@hiukim  I didnt saw/noticed any performance issues when running the same scene (single and multitargets) over a long period. If you need I might try to setup a small repro. Thanks for the quick responses 👍

**Comment by hiukim** [comment]
Sure, that could be useful.
