### ISSUE TITLE
[question] Custom UI for face tracking not available?

### ISSUE THREAD

**Issue by marcusx2** [hiukim/mind-ar-js#315]
The image tracking have a [custom UI overlay system](https://hiukim.github.io/mind-ar-js-doc/examples/custom-ui). You have these components: _uiError, uiLoading, uiScanning_.  On the face tracking documentation, I can't find this information. Are these custom overlays only available for the image tracking, or is the documentation missing? Can I have a custom ui scanning for face tracking like I can for image tracking, is it all the same but the docs is missing the info?

**Comment by hiukim** [comment]
those are for image tracking only.
