### ISSUE TITLE
[feature request] More events for face tracking

### ISSUE THREAD

**Issue by marcusx2** [hiukim/mind-ar-js#317]
Namely [`on mouth open, on mouth close, on left eye open, on left eye close, on right eye open, on right eye close`](https://docs.zap.works/static/v-f574d4b2/img/zappar-studio/face-tracking/face-actions.jpg). The cool thing with these events is the ability to have more interactive experiences where something happens depending on the user's facial expression.

See [this](https://docs.zap.works/studio/project-templates/face-tracking/face-tracking-expression-trigger/) for example.

**Comment by hiukim** [comment]
sounds interesting.

**Comment by hiukim** [comment]
blendshapes is added in v1.2.5

check out this example for reference: https://hiukim.github.io/mind-ar-js-doc/more-examples/threejs-face-blendshapes
