### ISSUE TITLE
[bug report] Link to mesh map is broken

### ISSUE THREAD

**Issue by marcusx2** [hiukim/mind-ar-js#321]
The link displayed [here](https://hiukim.github.io/mind-ar-js-doc/face-tracking-quick-start/webpage#anchor-points) is broken. This is the [correct URL](https://github.com/tensorflow/tfjs-models/blob/master/face-landmarks-detection/mesh_map.jpg)

**Comment by hiukim** [comment]
thx, thanks for reporting!
