### ISSUE TITLE
Recreate target image from mind file

### ISSUE THREAD

**Issue by Squidmaan** [hiukim/mind-ar-js#323]
I was wondering how you generate the target image created by the compiler on the front end? I cannot seem to figure out how to place that image on the canvas through the image tracking data.

Thank you!

**Comment by Squidmaan** [comment]
Then how did you go about creating this target image after the mind file is compiled?
![dog](https://user-images.githubusercontent.com/25992149/208687605-f476cdae-ce28-4c30-88cd-8f0bc1527a44.png)

**Comment by hiukim** [comment]
There are low resolution and grey scale images, but not the original image.

**Comment by Squidmaan** [comment]
How did you create the grey scale image from the tracking data?

**Comment by vishnusaivivek** [comment]
Actually as far as i knew its not possible to extract images from .mind, to achieve your requirement you have to manually convert all the images to greyscale and store them in assets of your project and have a config.json which contains in which order the images are given for compilation and for which targetIndex which image to be shown.
