### ISSUE TITLE
lag in facemesh AR

### ISSUE THREAD

**Issue by 0xhrsh** [hiukim/mind-ar-js#324]
I'm trying to create an AR scene with threejs facemesh, but there is quite some lag in it, here's a [deployed example](https://0xhrsh.com/lipstick-ar).

am I doing something wrong or is this as good as it gets?

**Comment by 0xhrsh** [comment]
cc: @hiukim

**Comment by hiukim** [comment]
Is the official demo lag for you? https://hiukim.github.io/mind-ar-js-doc/face-tracking-samples/three-facemesh.html

**Comment by 0xhrsh** [comment]
Yes

**Comment by hiukim** [comment]
Then you haven't done anything wrong.

**Comment by nosy-b** [comment]
It does lag a bit yes (on a super powerful computer) so I guess there is some motion stability parameters that we could tweek so it feels more reactive?
thanks!

**Comment by nosy-b** [comment]
@0xhrsh It is indeed just that :) 
  const mindarThree = new MindARThree({
        container: document.querySelector("#container"),
        filterMinCF: 0.1,
        filterBeta: 0.1,
      });
