### ISSUE TITLE
kernel is already registered when importing 'mind-ar/dist/mindar-image-three.prod.js'

### ISSUE THREAD

**Issue by Squidmaan** [hiukim/mind-ar-js#328]
When I import mind-ar/dist/mindar-image-three.prod.js, I receive roughly 200 warnings that are all something like
The kernel 'name of kernel' for backend 'cpu' is already registered

I am currently running mind-ar in Angular. 
This is what my import looks like

`import 'mind-ar/dist/mindar-image-three.prod.js' ;`

Does anyone know what I can do to remove these warnings?

**Comment by hiukim** [comment]
Did you also import `tensorflowjs` in your project?
