### ISSUE TITLE
npm installation  creates error when trying to run 

### ISSUE THREAD

**Issue by kordou** [hiukim/mind-ar-js#330]
HI, i am trying to install THREE from npm but when i i mport the Lib 
import { MindARThree } from "mind-ar/dist/mindar-image-three.prod.js";

i ma getting this error. 

Failed to resolve 'three/addons/renderers/CSS3DRenderer.js' from './node_modules/mind-ar/dist/mindar-image-three.prod.js'

 hree/addons/renderers should be three/examples/jsm/renderers.

compiling with parcel

how can i correct this 

thanks

**Comment by hiukim** [comment]
you might need to install `three` as well, which is an external dependency since v1.2.0

Refer to this as an npm example: https://github.com/hiukim/mind-ar-js-react
