### ISSUE TITLE
Example's Compiler is not working.

### ISSUE THREAD

**Issue by tokufxug** [hiukim/mind-ar-js#331]
@hiukim 
Download MindAR and go to examples/image-tracking/compile.html. 
https://ss395120.stars.ne.jp/mind-ar/examples/image-tracking/compile.html
Uploading images is not working first. Please let me know if there is anything missing to make this work.

Thanks.

**Comment by hiukim** [comment]
you can use the one in documentation https://hiukim.github.io/mind-ar-js-doc/tools/compile

**Comment by tokufxug** [comment]
@hiukim Thank you for your prompt reply.

I would like to create an application that incorporates this Compiler. I tried to verify the operation of this Example first, but it did not work, so I am asking this question.

The purpose is not to create a marker file, but to incorporate the compiling function to create a marker file into a web application I am developing.

**Comment by hiukim** [comment]
what's the error ?

**Comment by tokufxug** [comment]
If you upload below, you will get a captcha error in the console.
I also can't drag and drop images.
https://ss395120.stars.ne.jp/mind-ar/examples/image-tracking/compile.html
![image](https://user-images.githubusercontent.com/323081/212249105-388c9edf-5a71-4619-a3b6-34ab3842d0ee.png)

**Comment by hiukim** [comment]
404 - It said your `mindar-image.js` doesn't exist.

**Comment by tokufxug** [comment]
@hiukim I downloaded the entire project, does that mean that mindar-image.js is not included in the project?
Where can I find mindar-image.js?

**Comment by hiukim** [comment]
`npm run dev` to generate development version and `npm run build` to generate production version.

**Comment by 632366134** [comment]
> 我下载了整个项目，这是否意味着mindar-image.js不包含在项目中？我在哪里可以找到mindar-image.js？

Can you please share how to build image compiler on your own webpage
