### ISSUE TITLE
[feature request] flip webcam horizontally when using face tracking ar

### ISSUE THREAD

**Issue by marcusx2** [hiukim/mind-ar-js#333]
[This page](http://christianheilmann.com/2013/07/19/flipping-the-image-when-accessing-the-laptop-camera-with-getusermedia/) explains it very well.

You can see how the flipped camera should [behave here](https://editor.p5js.org/enickles/sketches/rJ9j1sx0M). It would be great if the face camera was flipped for the face tracking ar (not image tracking ar which uses the rear camera, only the front camera).

**Comment by sewonist** [comment]
Yes. It's really need. I try to find easy solution before update it. Although, I hope to update it on main repo.

**Comment by BoraYang** [comment]
@marcusx2 @sewonist 
Hi y'all, I also looked for flipping webcam horizontally and then found this discussion here.

https://github.com/hiukim/mind-ar-js/discussions/159

In addition, I added the codes below to flip an image on face as well.
```
    canvas {
      transform: scaleX(-1);
    }
```
