### ISSUE TITLE
MindAR stuck at initialization when deployed using Chrome Web Sever + Ngrok

### ISSUE THREAD

**Issue by aenoriss** [hiukim/mind-ar-js#335]
Hello everyone. I am having a problem hosting a static site with mindAR on the chrome web server and then using ngrok to deploy. It turns out that mindAR gets stuck at initialization and no error appears on the console. On the contrary, it seems to work fine on localhost. Has anyone experienced the same problem?

**Comment by aenoriss** [comment]
https://www.loom.com/share/49c1664f649543c183d55eeccde2fada

**Comment by aenoriss** [comment]
It seems to start after 6 minutes for some reason. Maybe there is a timeout or something?

**Comment by hiukim** [comment]
Maybe it's just loading. The free version of ngrok could be slow these days.

**Comment by kanzaky** [comment]
> Maybe it's just loading. The free version of ngrok could be slow these days.

yep, I had to pay the cheapest plan for it to work fine, if its for development its a good price since you can add a custom domain.
