### ISSUE TITLE
Object capture scalability

### ISSUE THREAD

**Issue by Ebeleh** [hiukim/mind-ar-js#34]
Is it possible to set up the camera to grasp images at a distance of 0.5-1 meter?

**Comment by hiukim** [comment]
I'm not sure what do you mean by that

**Comment by Ebeleh** [comment]
> I'm not sure what do you mean by that

I am sorry, my English - is bad, I mean grab a target image from a distance, maybe there is some kind of setting?

**Comment by hiukim** [comment]
still not sure what you mean by that. but I guess the answer is probably no. The available settings are probably mentioned in the documentation.
