### ISSUE TITLE
Do we have API for the image target compile tool?

### ISSUE THREAD

**Issue by TomDDH** [hiukim/mind-ar-js#341]
Hey Hiukim
Do we have API for the image target compile tool? or ways dynamically generate image target.   thanks very much.

**Comment by fieldOfView** [comment]
See https://github.com/hiukim/mind-ar-js/blob/master/examples/nodejs/createImageTargetLibrary.js

**Comment by 632366134** [comment]
> 请参阅 https://github.com/hiukim/mind-ar-js/blob/master/examples/nodejs/createImageTargetLibrary.js

I don't know how to use this file in my own project
