### ISSUE TITLE
Image Tracking Examples – demos broken with old library path

### ISSUE THREAD

**Issue by ffd8** [hiukim/mind-ar-js#342]
Just checking out v1.2 now, your installation page is super clear and great how reduced it all is to just 2 scripts when using AFrame. I noticed that in both the [Image Tracking Quickstart](https://hiukim.github.io/mind-ar-js-doc/quick-start/webpage) and all the [Examples](https://hiukim.github.io/mind-ar-js-doc/examples/basic), it's still referring to importing 2 scripts for mindar, of which they're not to be found anymore on the CDN links. 
Seems like all those examples need to be updated to just include the following:

```
<script src="https://aframe.io/releases/1.3.0/aframe.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/mind-ar@1.2.0/dist/mindar-image-aframe.prod.js"></script>
```

**Comment by MTLightCollective** [comment]
YES ! Exactly what I was looking for. 
I tried the QuickStart and had no result but a white screen. And this was the solution !

Thanks, 
The tutorial is great, but need to be updated indeed. I know a couple of guys who would have ragequitted for less than that.

**Comment by hiukim** [comment]
thx, thanks for reporting!

**Comment by schoukah** [comment]
@hiukim Just posting to let you know that the wrong paths are still in this [documentation's quickstart example](https://hiukim.github.io/mind-ar-js-doc/quick-start/webpage): 

```
<script src="https://cdn.jsdelivr.net/gh/hiukim/mind-ar-js@1.2.5/dist/mindar-image.prod.js"></script>
    <script src="https://aframe.io/releases/1.5.0/aframe.min.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/hiukim/mind-ar-js@1.2.5/dist/mindar-image-aframe.prod.js"></script>
```
