### ISSUE TITLE
Can I used other video stream for AR?

### ISSUE THREAD

**Issue by langxiankui** [hiukim/mind-ar-js#347]
I want to inquiry that could I used other video stream for AR? Or use the video stream in a-scene tag for other functionality like live streaming.

**Comment by hiukim** [comment]
not with the provided release build. But I imagine you can hack the source code to achieve something like that.

**Comment by langxiankui** [comment]
> not with the provided release build. But I imagine you can hack the source code to achieve something like that.

Can you give me some hints, please? For example, should I import the video stream into <a-scene>, or should I export the video stream from <a-scene>?

**Comment by hiukim** [comment]
depends on your use case. It's hard to tell.  If you're using aframe version, you probably need to work on this file: https://github.com/hiukim/mind-ar-js/blob/master/src/image-target/aframe.js

**Comment by langxiankui** [comment]
> depends on your use case. It's hard to tell. If you're using aframe version, you probably need to work on this file: https://github.com/hiukim/mind-ar-js/blob/master/src/image-target/aframe.js

Thanks！
