### ISSUE TITLE
You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by aenoriss** [hiukim/mind-ar-js#348]
I am having the problem shown in the capture below when trying to import the ThreeJS image tracking module into my React project (used Create-React-App and Eslint). Any help would be appreciated =)

![image](https://user-images.githubusercontent.com/46512125/217765490-ca0963ca-f29b-49b5-a59d-d1190e30dfe4.png)

**Comment by chansk131** [comment]
If you are using v1.2.0, I think you just need to change how you import the library from
```
import 'mind-ar/dist/mindar-image.prod.js';
import 'aframe';
import 'mind-ar/dist/mindar-image-aframe.prod.js';
```
to
```
import 'aframe';
import 'mind-ar/dist/mindar-image-aframe.prod.js';
```

Read more: https://hiukim.github.io/mind-ar-js-doc/installation#image-tracking-1
