### ISSUE TITLE
Is there a way to change canonical-face-model.obj?

### ISSUE THREAD

**Issue by mileshiroo** [hiukim/mind-ar-js#358]
Hello! 

Thanks for making this amazing library.

I was wondering if there's a way to change the face model that's used, for example to replace it with a higher poly one. I got as far as running face-data-generator.js and rebuilding the library with a new face-data.js, but I get errors that I suspect have to do with the way specific vertex indices are mapped to facial landmarks in estimator.js.

Do you have any tips or suggestions for making a face model that works with the library? Thanks!

**Comment by hiukim** [comment]
There is no direct and easy way to change the face model, but I guess it's possible to make use of the face-data-generator.js to do that, as you described. There might be some issues along the way. I'm not really sure.
