### ISSUE TITLE
i want surface-tracking in mind ar 

### ISSUE THREAD

**Issue by moshiuzzaman** [hiukim/mind-ar-js#359]
**I want surface-tracking in mind ar. is it possible?**
if possible then tell me how?
if not possible then suggest which free library is best for surface-tracking.
I want to use it in react.

**Comment by hiukim** [comment]
MindAR does not provide surface tracking.

I don't recall any free library for that. Except WebXR, which is not supported in iOS unfortunately.

**Comment by adilsonv77** [comment]
Search for Model viewer. Google technology. However it works on both: Android and IOS
