### ISSUE TITLE
Trigger Actions when marker is tracked and marker is lost

### ISSUE THREAD

**Issue by rudrjain** [hiukim/mind-ar-js#36]
Hi Actually I want to trigger several actions when the marker is detected and the marker is lost, But not able to do so. Can you please let me know how to achieve it.

**Comment by hiukim** [comment]
You can refer this for custom events handling:

https://hiukim.github.io/mind-ar-js-doc/examples/events-handling

**Comment by rudrjain** [comment]
Thanks it worked for me. And what if I want to check which marker has been detected (when I am using multiple targets). How to do that?

**Comment by rudrjain** [comment]
Thanks it worked for me
