### ISSUE TITLE
Tracking Config with Threejs demo

### ISSUE THREAD

**Issue by jamess922** [hiukim/mind-ar-js#361]
Hi :
About the [threejs-image demo](https://hiukim.github.io/mind-ar-js-doc/more-examples/threejs-image),how to  fine tune the tracking?
 is there some parameters like filterMinCF,filterBeta,warmupTolerance?

**Comment by LeithBA** [comment]
I think you can set your config when creating your MindARThree by doing this:

```js
const mindarThree = new MindARThree({
    container: document.querySelector("#container"),
    imageTargetSrc: './assets/card-example/card.mind',
    filterMinCF: 1,
    filterBeta: 10000,
    missTolerance: 0,
    warmupTolerance: 0,
  });
```

You can find a threejs example [here](https://github.com/hiukim/mind-ar-js/blob/master/examples/image-tracking/three.html).
