### ISSUE TITLE
viewing mind.js on codesandbox 

### ISSUE THREAD

**Issue by LovesPictures** [hiukim/mind-ar-js#363]
Hello  

The following error occurs when trying to view the application on codesandbox

![image](https://user-images.githubusercontent.com/25634451/224565692-de531317-2dac-4c8a-a665-495accfeacb4.png) 

Is this an issue you are able to take a look at, please?

**Comment by LovesPictures** [comment]
Also, code in codesandbox itself is not loading, thank you.

**Comment by hiukim** [comment]
Have live demo?
