### ISSUE TITLE
Minimal Example of face tracking does not work

### ISSUE THREAD

**Issue by kageori** [hiukim/mind-ar-js#367]
Hi,

When I try to run the minimal face tracking example code on local server, I get an error `Uncaught SyntaxError: Illegal return statement (at mindar-face-aframe.prod.js:1:1648)
` as shown in the attachment.

I am using the following code as is.
https://hiukim.github.io/mind-ar-js-doc/face-tracking-quick-start/webpage

How should I deal with this?

<img width="1336" alt="スクリーンショット 2023-03-18 13 21 32" src="https://user-images.githubusercontent.com/31335394/226105861-85fbf7e7-848b-45de-978d-844c842bf865.png">

**Comment by hiukim** [comment]
Thanks for reporting.  You will need to add type=module. I'll fix the documentation.

`<script src="https://cdn.jsdelivr.net/npm/mind-ar@1.2.1/dist/mindar-face-aframe.prod.js" type="module"></script>`

**Comment by kageori** [comment]
Thank you.

I tried to change it, but there appears to be another error.

<img width="421" alt="スクリーンショット 2023-06-03 16 02 34" src="https://github.com/hiukim/mind-ar-js/assets/31335394/fee3d034-b839-40cf-897b-8c2649dca92e">

**Comment by hiukim** [comment]
what other error

**Comment by kageori** [comment]
As you can see in the attached screen above.
`Uncaught SyntaxError: Illegal return statement (cdn.jsdelivr.net/npm…ce-aframe.prod.js:1)`

**Comment by hiukim** [comment]
sorry, my bad. Ignore my previous comment.

But it should now be fixed in latest version v1.2.2

**Comment by kageori** [comment]
It worked!

Thank you so much!
