### ISSUE TITLE
Mesh distortion on a curved marker

### ISSUE THREAD

**Issue by devhims** [hiukim/mind-ar-js#37]
Hi @hiukim, we've been trying to replicate the curved images tracking feature offered by the 8th wall with the mind ar library.

We tried using a curved plane and curved image primitives offered by a-frame, but in both cases, the edges of the mesh appear to distort when the device is moved wrt the marker. 

<img width="137" alt="Screenshot 2021-06-13 at 11 46 45 PM" src="https://user-images.githubusercontent.com/17825870/121868774-01095080-cd1f-11eb-8d34-047f555d123e.png">

Here a [video recording](https://drive.google.com/file/d/1U9LXllVHIqRdhMwxDMKLjAJos3yf69zq/view?usp=sharing) of the same issue.

I'm curious to know your thoughts on the issue and any workaround you can suggest to overcome this?

**Comment by hiukim** [comment]
@devhims Unfortunately, the library does not support curved markers at this point. I don't have good suggestions for this.  If you are only tracking it in a specific view (e.g. frontal view). maybe you can make a distorted image as the marker to somehow simulate a plane......

**Comment by devhims** [comment]
Unfortunately, we can't decide the view in advance. Anyway, thanks for the response @hiukim. I'll close this issue for now.
