### ISSUE TITLE
Generate file.mind server-side?

### ISSUE THREAD

**Issue by Bobbianss** [hiukim/mind-ar-js#372]
Hi, 
I would need to understand if the "compiler.js" is able to be integrated for generating the ".mind" file inside a web server.

Basically I am trying to have the ".mind" file generated directly by the server without going through the browser (client-side), and I don't understand if it is necessary to use webGL which is client-side only.

**Comment by kasual1** [comment]
I'd also like to know if it is possible to generate target files on the server side

**Comment by virbas** [comment]
It's in the examples: 
examples/nodejs/createImageTargetLibrary.js
