### ISSUE TITLE
Landscape Video Not Full Width

### ISSUE THREAD

**Issue by chasbrouck** [hiukim/mind-ar-js#373]
When run in landscape orientation (mobile phone), the video does not fill the full width of the screen 
![IMG_F8496A198C81-1](https://user-images.githubusercontent.com/11258207/229606971-ec68773e-f731-42e0-b7ce-64005ceee5fc.jpeg)

**Comment by hiukim** [comment]
Did you set the css right? Is your container 100% width and height?
