### ISSUE TITLE
how to use image assets with transparency

### ISSUE THREAD

**Issue by carlesgutierrez** [hiukim/mind-ar-js#379]
Dears mind-ar-js users and creator, 
  I've not seen documentation or issues related to this. I would like to use images with alpha ( png ) so the image overlapped might do the magic as 3d model does. 
   Is there any way to allow it?
Thanks a lot for this space and awesome framework.

**Comment by carlesgutierrez** [comment]
Thanks for your reply but my question is more about how to use the transparency of the png image it self. 
I guess is possible, I've seen it working with [pictarize ](https://pictarize.com/)but not here with mind-ar-js -> alpha is painted in black instead of transparent.

My code: ( A4-TargetRelax2.png is an image with transparency )
```

<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <script src="https://aframe.io/releases/1.4.1/aframe.min.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/donmccurdy/aframe-extras@v6.1.1/dist/aframe-extras.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/mind-ar@1.2.1/dist/mindar-image-aframe.prod.js"></script>
  </head>
  <body>
      <a-scene mindar-image="imageTargetSrc: ./data/targets_nature_scaled5.mind;" color-space="sRGB" renderer="colorManagement: true, physicallyCorrectLights" vr-mode-ui="enabled: false" device-orientation-permission-ui="enabled: false">

      <a-assets>
         <img id="card" src="./data/A4-TargetRelax2.png" /> 
      </a-assets>

      <a-camera position="0 0 0" look-controls="enabled: false"></a-camera>
      
      <a-entity mindar-image-target="targetIndex: 0">
        <a-plane src="#card" position="0 0 0" height="1" width="1" rotation="0 0 0"></a-plane>
      </a-entity>

    </a-scene>
  </body>
</html>
```

**Comment by dvbridges** [comment]
Have you tried adding "transparent: true" to your a-plane? I have transparent background on transparent png files when using this.

**Comment by carlesgutierrez** [comment]
Thanks @dvbridges That was!
