### ISSUE TITLE
About camera fov for non AR objects

### ISSUE THREAD

**Issue by sharimken** [hiukim/mind-ar-js#385]
May I know how to get the vertical fov of the mindar camera on mobile?
Because I noticed that we will have different fov, when starting between landscape mode and portrait mode?

When starting with portrait mode, seems the horizontal fov is wider for non AR objects in the scene.
In my use case, I have two type of 3D models:
"myModel1-NotAR" is relative to the camera in scene.
"myModel2-AR" is relative to face tracking.

In my case, the AR position is completely correct.
However,  "myModel1-NotAR" rendering result is different(seems related to fov), depending on mobile orientation when loaded the scene.

Ideally, I want to have fixed vertical fov for non-AR objects. If not possible, then I need to find a way to get camera vertical fov, then calculate the relative position for my 3D models(non-AR).

Below is my example script...etc.

        <a-scene mindar-face="autoStart: true" embedded color-space="sRGB" renderer="colorManagement: true, physicallyCorrectLights" vr-mode-ui="enabled: false" device-orientation-permission-ui="enabled: true">
            <a-camera active="false" position="0 0 0" look-controls-enabled="false"></a-camera>

            <a-assets>
              <a-asset-item id="myModel1-NotAR" src="myModel1-NotAR.glb"></a-asset-item>
              <a-asset-item id="myModel2-AR" src="myModel2-AR.glb"></a-asset-item>
            </a-assets>

            <a-gltf-model id="myModel1-NotAR" position="0 0 -5">

            <a-entity mindar-face-target="anchorIndex: 1" scale="1 1 1">
              <a-gltf-model id="myModel2-AR">
            </a-entity>

        </a-scene>

**Comment by hiukim** [comment]
The syntax is probably wrong. But something like this:

`querySelector("#a-camera").getObject3D('camera').fov`

Can you check aframe documentation on how to get object3D from the element?
