### ISSUE TITLE
Memory leak issue

### ISSUE THREAD

**Issue by BoraYang** [hiukim/mind-ar-js#386]
Is there anyone who was encountered with a memory leak issue?

After 15 mins of app running, the app's JavaScript memory usage increases up to around 250,000K and makes Chrome freeze.
 
Probably I'm doing something wrong with the library, but I want to know how to solve this memory leak issue.

![Screenshot 2023-04-07 at 11 49 40 AM](https://user-images.githubusercontent.com/19316616/232642146-9878e890-5558-4044-829f-231a01540bf5.png)

**Comment by hiukim** [comment]
@BoraYang 

can you try with the deployed version: https://hiukim.github.io/mind-ar-js-doc/face-tracking-samples/three-facemesh.html

Just to make sure it's not caused by your localhost server.
