### ISSUE TITLE
GLTF 3D models not loading on my server

### ISSUE THREAD

**Issue by M3056789** [hiukim/mind-ar-js#388]
Hi master Hiukim,

I´m having issues in playing a GLTF 3D model from my server. Your example works fine, but after moving your gltf (Bear and Raccoon) to my server, things stop to work...  Do I need a 3D viewer installed in the same directory of the GLTF file on my server? Why is not loading the 3D files from my server?
Thanks a lot

**Comment by felipefierro** [comment]
Hi! did you manage to make it work? I can't seem to find a solution :(

**Comment by M3056789** [comment]
Hi there, yes, the solution that I found was to load your GLTF file on GitHub and place a file called "GLTFLoader.js" next to it. Your 3d model needs to get this name "scene.gltf", after this is placed on GitHub get the link and placed it on your code. Sometimes the 3D model is too small and you don´t see it on the AR experience. hope it helps. Look into Hiukim and follow his trail....
https://www.jsdelivr.com/github

**Comment by felipefierro** [comment]
Thank you so much!! it was super helpful! I couldn't find any info related to that issue before! My best regards!
