### ISSUE TITLE
Trouble accessing camera texture

### ISSUE THREAD

**Issue by keption** [hiukim/mind-ar-js#39]
Hi,

I am trying to capture screenshot of the scene & camera.

When I tried to access the camera texture using:

document.querySelector('video');

This is returning a black screen.

Any ideas how to correct this issue?

Thanks

**Comment by hiukim** [comment]
@keption Can you provide a minimal and running example to try?

**Comment by mrizkiaiman** [comment]
Hi, can you share how you solve this issue? @keption
