### ISSUE TITLE
Documentation errors loading json libs

### ISSUE THREAD

**Issue by carlesgutierrez** [hiukim/mind-ar-js#395]
Dear @hiukim,

There is a missing </script> tag in the documentation example: [face mesh](https://hiukim.github.io/mind-ar-js-doc/more-examples/threejs-face-facemesh/) 

![image](https://user-images.githubusercontent.com/203877/236442199-94c884f5-4b5d-4ea7-a0c8-0d3eeaa9e69a.png)

And another not fully detected error:

At [minimal example](https://hiukim.github.io/mind-ar-js-doc/face-tracking-examples/minimal) there are at least 2 CDN jsons files are missing. 

https://cdn.jsdelivr.net/gh/hiukim/mind-ar-js@1.2.1/dist/mindar-face-aframe.prod.js
and
https://cdn.jsdelivr.net/gh/hiukim/mind-ar-js@1.2.1/dist/mindar-face.prod.js

they should be: 

https://cdn.jsdelivr.net/npm/mind-ar@1.2.1/dist/mindar-face-aframe.prod.js
and
?

**Comment by hiukim** [comment]
the doc is fixed. thx
