### ISSUE TITLE
How to get facemesh from video camera.

### ISSUE THREAD

**Issue by carlesgutierrez** [hiukim/mind-ar-js#397]
Hello all,
 I'm trying to get a real-time texture facemesh from the video camera.  
 So I was looking for a facemesh extractor in this library but not sure if this is already available or how to achieve this.
 May help **[this feature](https://github.com/hiukim/mind-ar-js/pull/242#issue-1348458136)** when it says "allowing for screenshots of the face mesh"?
 
 My intention is to occlude some part of the raw facemesh video and give custom "light and color texture" to a animated face mesh for a better filter integration. 
 
Any tips are so welcome.

**Comment by hiukim** [comment]
Unfortunately nope, the library doesn't provide that. You might be able to compute that, I'm not sure.
