### ISSUE TITLE
Question regarding track multiple targets

### ISSUE THREAD

**Issue by HuzaifaKhan20** [hiukim/mind-ar-js#401]
Hi @hiukim
I want to ask you that:

I want to track multiple targets simultaneously but I am unable to combine multiple mind files so how can I do it?

Whether the solution is to combine multiple mind files or to create a single mind file with a single frame containing multiple images?

I want to learn about the .mind file extension and how the image is compiled into the .mind file. So kindly tell me any resource where I can learn from?

**Comment by carlesgutierrez** [comment]
Hi @HuzaifaKhan20 ,
 What is exactly not working for you? Did you tried with the [example multiple targets? ](https://hiukim.github.io/mind-ar-js-doc/examples/multi-tracks)
  In my case I've tried and worked combine multiple targets. You just have to do drag and drop you your too tracker images into the [image target compiler](https://hiukim.github.io/mind-ar-js-doc/tools/compile). 
Not idea what scale is the best or better, but I like to do some scaling "just in case" ( scale 5  ). 

 Just trying to help, but probably you already did all this
 Cheers!

![several_images_targetCompiler](https://github.com/hiukim/mind-ar-js/assets/203877/562733cf-4b7f-4366-910f-2e063166eb94)
![several_images_targetCompiler_scale](https://github.com/hiukim/mind-ar-js/assets/203877/17e290c6-6e5f-4f71-9383-ec97b65c52d8)

**Comment by HuzaifaKhan20** [comment]
Thanks @carlesgutierrez for your kind help.

I have tried the above way but it only detects a single image in my case. but I downloaded the whole repository and then after installing node packages I successfully combined multiple images into a single mind file.
