### ISSUE TITLE
Type-Definitions for MindAR for react projects in Typescript 

### ISSUE THREAD

**Issue by Legend101Zz** [hiukim/mind-ar-js#403]
Hello!!

First of all thanks for this tremendous open-source AR library, I have been using it extensively, alongside your Udemy course.

I tried to use the mind-ar npm package in a ts-react project, but there does not seem to be a type definition file for the mind-ar library...

**Comment by hiukim** [comment]
yes. Unfortunately, we don't have a typescript version.
