### ISSUE TITLE
Anchor identification when emits onTargetFound

### ISSUE THREAD

**Issue by adilsonv77** [hiukim/mind-ar-js#408]
In image-target/three.js, line 161, I identified that any information is send to onTargetFound.

With multiple-targets, I´m interesting to identifiy which target emitted this event. How can I do this? Suggestions...

**Comment by hiukim** [comment]
onTargetFound is bind to specific anchor already

**Comment by adilsonv77** [comment]
Ok. How can access It?

**Comment by hiukim** [comment]
```
anchor.onTargetFound = () => {
}
```

**Comment by adilsonv77** [comment]
OK... I understood your point. However, I´m working with multi targets, dinamically loaded from a database. 

I have this piece of code, to adding an anchor for each target. When the target is detected, then show a button (in thruth is an hyperlink) in the page. Each target must change the value of the parameter from the hyperlink.

for (var i = 0; .....) {

        ...
        const glb = await loadGLTF(<dinamically from a database>);
        const glbScene = glb.scene;
         ...
       const anchor = mindarThree.addAnchor(i);
      anchor.someAttribute = take the value from somewhere
      anchor.group.add(glbScene);
    
        anchor.onTargetFound = () => {
          buttonAR.href = buttonAR._href + "?id=" + <I wanna get someAttribute from the current anchor>
          buttonAR.style.display = 'block';
        }
        ....
  }
Can you see? Anchor is dinamically created in multitarget problem.

**Comment by hiukim** [comment]
Yes,  `buttonAR.href = buttonAR._href + "?id=" + anchor.someAttribute` should work.

**Comment by adilsonv77** [comment]
I tried now, and it gave the error message "Uncaught ReferenceError: anchor is not defined"

**Comment by adilsonv77** [comment]
I changed three.js with this code

if (this.anchors[i].onTargetFound) {
   this.anchors[i].onTargetFound(this.anchors[i]);
 }

It worked for me.

**Comment by hiukim** [comment]
That's weird. I really don't think you need to do that.  But whatever works for you.

**Comment by adilsonv77** [comment]
However, I would like to use your suggestion. After compile the code with my modification and use mindar-image-three.js, seems the model is shivering.

**Comment by adilsonv77** [comment]
Everything is ok. I tried your suggestion.
