### ISSUE TITLE
Tracking a smaller or farther image

### ISSUE THREAD

**Issue by hbaugmentedreality** [hiukim/mind-ar-js#41]
Hi all...
Is it possible to track the image when the image is farther?   I mean, to detect a target image, it is necesary to be quite near or have almost 50% of the camera screen with the image.    Is is possible to track the image being farther or at least to keep the 3D model when the camera goes farther?
Thanks!!!

**Comment by hiukim** [comment]
Technically, there is no limits on how far/near the target should be located. It just comes down resolution and the target details, etc.  and of course the performance and quality of the library.  

I will keep trying to improve the core algorithm. Would really appreciate any computer vision experts to help in this area.

**Comment by hiukim** [comment]
should be fixed in latest release
