### ISSUE TITLE
 WeChat cannot access the camera

### ISSUE THREAD

**Issue by ggRosen** [hiukim/mind-ar-js#411]
Hello，I wrote the ar code using mind-ar-js, and I can watch it through Google browser and Safiri browser. After I converted the link into a QR code，Scanning the QR code in WeChat cannot access the camera,However, the QR code I generated through https://studio.pictarize.com publish can be used to access the camera by scanning it through WeChat.The screenshot is the screen I scanned the QR code through WeChat. I clicked to allow, but the camera was not called, and the display was blank. I put the link in the sarifi browser to call the camera。 I don't know how to solve this problem, please help me, thank you

![微信图片_20230605203538](https://github.com/hiukim/mind-ar-js/assets/108643655/b69c95d8-3303-4c5b-9fcb-93277f488c21)

**Comment by zhangda-cpu** [comment]
Hello, has the problem been solved?
