### ISSUE TITLE
World Tracking Applications can't run in iPhone's safiri browser

### ISSUE THREAD

**Issue by ggRosen** [hiukim/mind-ar-js#412]
World Tracking Applications I have successfully tested it in the Google browser, but when I tested it with the ![微信图片_20230605210135](https://github.com/hiukim/mind-ar-js/assets/108643655/098af253-2369-4426-882a-14f4261a3652), it prompts: "", how can I use the mobile phone to watch the effect of World Tracking? Please help me, thank you

**Comment by hiukim** [comment]
WebXR api is not supported in iOS

**Comment by ggRosen** [comment]
Is there any other way I can achieve this World Tracking ? Because I want to watch the effect through ios, I kindly ask for your help。thank you

**Comment by hiukim** [comment]
Unfortunately, I do not aware of any opensource or free solutions for world tracking AR.  You might have to go for commercial options.

**Comment by BostonLeeK** [comment]
there is opensource solution but it work on another concepts 
https://github.com/alanross/AlvaAR
