### ISSUE TITLE
getUserMedia error DOMException: Requested device not found In face AR

### ISSUE THREAD

**Issue by DevaPandiyan** [hiukim/mind-ar-js#413]
Not working your Live Demo too How to Fix it...

<img width="1285" alt="Screenshot 2023-06-05 at 9 00 35 PM" src="https://github.com/hiukim/mind-ar-js/assets/25933803/10e0e61e-895e-4d4b-9592-ab51b4192304">

<img width="1339" alt="Screenshot 2023-06-05 at 9 02 09 PM" src="https://github.com/hiukim/mind-ar-js/assets/25933803/0963bf30-bb2e-45e8-8a7f-0d6d179b85a8">

**Comment by hiukim** [comment]
Do you have a webcam connected?

**Comment by DevaPandiyan** [comment]
yes have it and its mac inbuild  face camera ....
