### ISSUE TITLE
Green screen error on android and video is not loading on ios

### ISSUE THREAD

**Issue by siam88** [hiukim/mind-ar-js#414]
After putting this on the server it works fine on pc but unfortunately in Android, it acts differently in different browsers.  like in Chrome camera is not loading it's showing a green screen but the video is showing on the other hand in Firefox camera is showing but the video is black. in the above circumstances, what should we do?

![WhatsApp Image 2023-06-08 at 13 04 26](https://github.com/hiukim/mind-ar-js/assets/29373770/6edfeee3-56cb-4ee1-a96f-de25e1af547d)

![WhatsApp Image 2023-06-08 at 13 28 09](https://github.com/hiukim/mind-ar-js/assets/29373770/c6ba2cc8-e29f-47ea-85bb-5bcbcedfdadb)

**Comment by hiukim** [comment]
Take away the mindar code and double check your video works in a regular threejs application first

**Comment by siam88** [comment]
I checked with a different phone. For ios, it didn't work like the video is not showing but there are no greenscreen issues on the other hand on some phones it works and for some, it occurs with greenscreen

**Comment by hiukim** [comment]
without mindar?

**Comment by siam88** [comment]
no with mindar

**Comment by hiukim** [comment]
try without first

**Comment by siam88** [comment]
So, briefly, I was trying to create a marker-based AR application where a video will pop up after scanning the target image. I was trying it with mindAR only as I do not have any working experience with other AR frameworks. It works fine in the desktop version but facing some problems while using it with mobile devices after deploying it on the server.
1. In some Android phones green screen is appearing (especially versions that are less than 10). So can u please confirm whether it is the issue with the phone or Google ARCore or something else, will appreciate your wise advice?
2. Does mindAR have support in iOS, we were unable to play this with iOS devices.
3. If you suggest trying without mindAR, what is your preferred library/framework to work with webAR?
Can you please kindly help by answering the above questions as we are struggling to create a stable production-ready webAR application? I will really appreciate it.

**Comment by enemali** [comment]
The stable webAr platforms out there are not free and expensive.
If you can afford it then try 
BlippAr
Zappar

**Comment by zsolitech** [comment]
Same error: Samsung Galaxy S8, Android 9

**Comment by sundaram75** [comment]
> So, briefly, I was trying to create a marker-based AR application where a video will pop up after scanning the target image. I was trying it with mindAR only as I do not have any working experience with other AR frameworks. It works fine in the desktop version but facing some problems while using it with mobile devices after deploying it on the server.
> 
> 1. In some Android phones green screen is appearing (especially versions that are less than 10). So can u please confirm whether it is the issue with the phone or Google ARCore or something else, will appreciate your wise advice?
> 2. Does mindAR have support in iOS, we were unable to play this with iOS devices.
> 3. If you suggest trying without mindAR, what is your preferred library/framework to work with webAR?
>    Can you please kindly help by answering the above questions as we are struggling to create a stable production-ready webAR application? I will really appreciate it.

Me too facing the green screen issue. 
Device - (Redmi Note Pro 8 ) 
Chrome version - 114.0.5375.196
Operating System - Android 9, Redmit Note 8 Pro Build/PPR1.180610.011

**Comment by ehsanwwe** [comment]
this problem is steel for me
Huawei Y9 2019
chrome browser  114.0.5735
Android 8.1

**Comment by ehsanwwe** [comment]
i found a solution to it

https://stackoverflow.com/questions/74344146/getusermedia-green-screen-on-android

in the mind-ar-image-three.prod.jd
i edit the 
getUserMedia with this answer and finaly work without greenscreen

**Comment by ehsanwwe** [comment]
no no - its not work

it is a chrome bug

> 
It turns out it's a [Google Chrome Bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1156408). Thanks to Philipp Hancke.

**Comment by sundaram75** [comment]
There is a workaround published a few days ago on the Google Chrome bug.
The workaround is 
Disable "Use passthrough command decoder" in chrome://flags and it shows the video feed for me now.
It worked on my device Redme Note 8 Pro.
Hope this helps all the members who are stuck due to this.
