### ISSUE TITLE
Videos in Mindar

### ISSUE THREAD

**Issue by bgarnb** [hiukim/mind-ar-js#418]
Why videos (mp4 ) that play locally do not play on the GitHub page? There is only one frame of them with no movement at all... 
Thank you

**Comment by Yaroslaw9050** [comment]
What platform will you be testing on?

**Comment by bgarnb** [comment]
Thank you for your reply. I've tested it with Android, using the Chrome browser. There are three videos (*.mp4) without sound to be displayed. Their size is not big. The code with one video runs ok.

**Comment by Yaroslaw9050** [comment]
@bgarnb Are you using A-Frame or Three.js for the implementation of the task?
Can you share any video materials that work and don't work?

**Comment by bgarnb** [comment]
@Yaroslaw9050  You can find the code here:
https://github.com/t20terz/SkoteinosThalamos
It is 3js and mindar. The targets and the videos.

**Comment by Yaroslaw9050** [comment]
@bgarnb Please try this[ Git page](https://yaroslaw9050.github.io/web-ar-test-targets/). Can you play the video?

(I modified the markers purely for my convenience. I will attach them to the message.)

![marker_0](https://github.com/hiukim/mind-ar-js/assets/67838013/f7e56018-6453-41b6-a234-84ef5d9c1858)
![marker_3](https://github.com/hiukim/mind-ar-js/assets/67838013/6fafb176-f06c-40c4-9e1b-c21a3c56139d)
![marker_4](https://github.com/hiukim/mind-ar-js/assets/67838013/66a7eeef-62bf-4a5e-824d-94cce293d975)

**Comment by bgarnb** [comment]
@Yaroslaw9050 OK... stupid of me. It was the markers! 
Thank you!!!

**Comment by Yaroslaw9050** [comment]
@bgarnb  Are you sure? The **play** `video1.addEventListener('play')` event caused issues for me. It set a specific frame for the video, which prevented it from playing. Try commenting it out for all the clips.

**Comment by bgarnb** [comment]
@Yaroslaw9050 I've tested all of them and they played. I will test them more carefully. Anyway, I really thank you for your time and help!
