### ISSUE TITLE
How deploy in Ubuntu 20?

### ISSUE THREAD

**Issue by johnfelipe** [hiukim/mind-ar-js#42]

**Comment by hiukim** [comment]
what do you mean to deploy?

**Comment by johnfelipe** [comment]
I mean install and review on public IP...

**Comment by hiukim** [comment]
It's the same as how you host a regular website.

**Comment by johnfelipe** [comment]
Apache ir nginx?

**Comment by hiukim** [comment]
yes. those will work.
