### ISSUE TITLE
Problem with audio when playing video

### ISSUE THREAD

**Issue by hassanayoub1985** [hiukim/mind-ar-js#422]
Hello,
I am trying to show a video when the target image is found here https://newsite.technodel.net/gfc/ but I have 2 problems:
1- when the page load, even if the marker is not on camera, the video's sound is played!
2- Sometimes the video don't load when the image is detected and sometimes is played.
3- When the image target is lost, the sound keep playing.
Any idea what I made wrong?

**Comment by MohanreddyMummareddy** [comment]
@hassanayoub1985 

I will look at this issue. I want to contribute to this project and couldn't find a way to connect with you over it.
My work experience:  https://mohanreddymummareddy.github.io/MyResume/
Linkedin: https://www.linkedin.com/in/mohan-reddy-mummareddy-50409b132/

**Comment by hiukim** [comment]
@MohanreddyMummareddy  thx, feel free to look into that.
