### ISSUE TITLE
max targets amount

### ISSUE THREAD

**Issue by colorao** [hiukim/mind-ar-js#432]
Hi. 
I'm new to Mindar but planning to create a project with it, but I'm worried on the limits.

My project will have around 200 targets and 200 assets (3D, or videos, or images...)

Are 200 targets too much to compile?
Are 200 targetstoo much for the system to detect?
Is there a way to defer the asset loading in order to not to preload 200 assets, but load them once the target is detected ?

Thanks in advanced

**Comment by BostonLeeK** [comment]
I don't know answer for question of limitation for markers but second question I can give details.

Yes you can load content only on marker detection. There are two possible ways. 

The simplest is using inline assets, example 
<a-image src="url-to-file" /> and it will load only when marker was found. In that case can be some problems with video files (I have before when try to control them, video textures caches and I cannot stop it).

More complicated is to make some logic that will dynamic add resources to assets and then you can control them from cache. This need to track marker, load asset, check asset is ready and then render it.

**Comment by hiukim** [comment]
the answer to the first question. Yes, 200 is too much.  There is no hard limit, but practically speaking, around 10 to 20 I would say.
