### ISSUE TITLE
anchor interact with object in world position

### ISSUE THREAD

**Issue by patacoding** [hiukim/mind-ar-js#435]
init like this: 
const { renderer, scene, camera } = mindarThree;

when add object into scene by:
scene.add(cube);

how to get/set world position rotation of cube ?  seems mindar scene has different coordination from normal threejs scene

thanks!

**Comment by patacoding** [comment]
set camera position, solve the problem!!

**Comment by patacoding** [comment]
if I want the anchor interact with other object like detect collide, how to get the world position of the anchor?
and , the video steam plane seems to have a position, if it's position.z bigger then a mesh will cover it.

**Comment by maxrpark** [comment]
Hello, 
I was going to ask a similar question, but maybe I can join this one. 
I am also wondering how to get the position of the anchor when using mindar-face-three.

**Comment by patacoding** [comment]
> Hello, I was going to ask a similar question, but maybe I can join this one. I am also wondering how to get the position of the anchor when using mindar-face-three.

I figure out a workaround, append an object to an anchor, then using .getWorldPosition() on the object to get position value.
