### ISSUE TITLE
Mindar Studio example not working when deployed in Amazon amplify

### ISSUE THREAD

**Issue by sundaram75** [hiukim/mind-ar-js#437]
I tried exporting the code in https://studio.mindar.org/ with default 3D object ( glasses) to a webserver.
The code works well when deployed on a local webserver.
But when I tried to host it on Amazon Amplify it is failing with 404 error on trying to get _x1.
The code is deployed here https://test.d3gjein32q5cd9.amplifyapp.com/
The browser used is Chrome Version 115.0.5790.110 (Official Build) (64-bit).
Could someone please help me to resolve the issue?
Do i need to change some settings on the webserver ?
I'm not sure if this is an issue with the code. 

Please see a screenshot of the error here.

![image](https://github.com/hiukim/mind-ar-js/assets/15609691/31c0f432-aa97-46f9-9d34-5a362c711ece)

**Comment by hiukim** [comment]
not sure about amplify. but the errors seems to indicate that file is missing. probably have something to do with the file path resolution.
