### ISSUE TITLE
Compiled .mind file is outdated... (August 23)

### ISSUE THREAD

**Issue by orgaralf** [hiukim/mind-ar-js#443]
This framework is exactly, what we need and I am happy I found it. Yet the compiler contained in the current release triggers an error, that the created mind file is outdated. Anything we can change here?

![image](https://github.com/hiukim/mind-ar-js/assets/326428/cdf464b6-9225-4570-b1bc-e02bfa0ecb4b)

**Comment by BostonLeeK** [comment]
You can generate your personal new .mind file local using source code or online web service that provide author 

https://hiukim.github.io/mind-ar-js-doc/tools/compile
