### ISSUE TITLE
Screen Recording in WebAR

### ISSUE THREAD

**Issue by Fatima-Aslam** [hiukim/mind-ar-js#451]
I want to record the AR experience in the form of a video using a button click. Is there any method for this? As in model-viewer, user can record their AR experience. Same like this, I want in MindAR. Please help me to do it. Thanks

**Comment by BostonLeeK** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API/Using_Screen_Capture
please read.
You can capture only canvas and video (in your example).
But you need to compose two videos (ar and video) and then save. It very expensive for browser.

**Comment by vizsatiz** [comment]
How does the model viewer do it with ease? Any comments on that? I will be happy to contribute to this solution

**Comment by BostonLeeK** [comment]
Please give information about what model viewer you talking. I just can give example what I'm try and it give me bad results and productivity

**Comment by vizsatiz** [comment]
The question had mentioned about model viewer and I assumed it was established. Well, i meant google model viewer https://modelviewer.dev/

**Comment by hiukim** [comment]
As mentioned by BostonLeek, you will need to record the canvas and the video. One way I would recommend is to create another canvas, then you draw both the video and the AR canvas on it every frame, then you somehow capture that new canvas and export as video.
