### ISSUE TITLE
Scene not rendering in Laravel

### ISSUE THREAD

**Issue by mock1ngj** [hiukim/mind-ar-js#452]
there are no errors the targetFound event is firing so i know its working fine but the scene is not playing or rendering when the image is found outside of laravel its working just fine so i think something in laravel is causing the scene to not render or play when the image is found any help is appreciated

**Comment by BostonLeeK** [comment]
Give code for understand your problem. Maybe you use laravel with ssr ore something else?

**Comment by mock1ngj** [comment]
> Give code for understand your problem. Maybe you use laravel with ssr ore something else?

i didnt use any server side rendering on laravel and the only thing i did was import it via npm with vite and load it via jquery load i know it seems like a roundabout way of doing things but i want to easily change the assets inside the mind-ar but since vite is loaded last i had to do it that way or it will not recognize mind-ar inside the blade template

**Comment by hiukim** [comment]
can you provide screen recording to show your issue?

**Comment by mock1ngj** [comment]
> can you provide screen recording to show your issue?

thanks for the reply but i decided to just build it outside of laravel
