### ISSUE TITLE
Play audio on marker detection

### ISSUE THREAD

**Issue by Fatima-Aslam** [hiukim/mind-ar-js#464]
Is there any method to play audio as the marker got detected and pause as the marker lost? I want it for both Android and IOS. Thanks in advance

**Comment by lulu1140** [comment]
yeah its simple code 
 <script type="module">import {loadGLTF, loadVideo, loadAudio} from "./loader.js";
      const THREE = window.MINDAR.IMAGE.THREE;
      
      document.addEventListener('DOMContentLoaded', () => {
        const start = async() => {
          const mindarThree = new window.MINDAR.IMAGE.MindARThree({
            container: document.body,
            imageTargetSrc: './tow',
          });
          const {renderer, scene, camera} = mindarThree;
          
          //here is code for audio 
          //audio load
    const audioClip = await loadAudio('./10.mp3');

    const listener = new THREE.AudioListener();
    camera.add(listener);

    const audio = new THREE.PositionalAudio(listener);
    const anchorA = mindarThree.addAnchor(9);
    anchorA.group.add(audio);

    audio.setBuffer(audioClip);
    audio.setRefDistance(1500);
    audio.setLoop(true);

    anchorA.onTargetFound = () => {
      audio.play();
    }
    anchorA.onTargetLost = () => {
      audio.pause();
    }
