### ISSUE TITLE
Transparent images

### ISSUE THREAD

**Issue by Carnaux** [hiukim/mind-ar-js#47]
Hey, @hiukim how do images, that are mostly transparent backgrounds, work on mind-ar? On JsArtoolkit5 the background becomes black and then there are issues tracking the image on white or bright backgrounds.

**Comment by hiukim** [comment]
I think @akhrarovsaid is right. that's also what I would do if cropping is possible.

I know there are cases where cropping is not possible. For example, your target is in circular shape, or your transparency background is in an inside area. 

I think the simple answer to the original question is that the library didn't handle that. It will just turn them into a single color (maybe white or black, I'm not certain).

**Comment by Carnaux** [comment]
Yeah, that should solve and I tried that too, but in my case, most images fall back to what @hiukim said. 

Depending on the tracking algorithm I think gray would be better. I'm currently using black on the NFT-Marker-Creator and that is part of the issue.

I have this [proposal](https://github.com/webarkit/jsartoolkit5/issues/13) on JsArtoolkit5, I will test it today and maybe it can be applied to Mind-Ar too. 

If you are interested I will keep you updated on the matter. Thanks, guys!
