### ISSUE TITLE
android cellphone open the worry camera

### ISSUE THREAD

**Issue by jamess922** [hiukim/mind-ar-js#470]
Hi：
    When use the chrome open the demo with an Android cellphone,looks use the worry camera ,i think because of the mult-cameras ,is there any solution,like switch the cameras
![Worry camera](https://github.com/hiukim/mind-ar-js/assets/28625879/83b39582-e0d3-45dd-9787-b523ed55f16d)

**Comment by jamess922** [comment]
![Uploading 微信图片_20231117100043.jpg…]()

**Comment by jamess922** [comment]
![Uploading Worry camera.jpg…]()

**Comment by hiukim** [comment]
I don't know how to pick the "correct" camera.  But as of v1.2.4, you can specify your desired camera in the mindarThree constructor, so you can implement your own logic of picking the camera.

Ref: https://github.com/hiukim/mind-ar-js/blob/master/examples/image-tracking/three.html
