### ISSUE TITLE
Image tracking rotation of plane and correlation bugs - Reproduce-able on example project

### ISSUE THREAD

**Issue by JakobHakansson** [hiukim/mind-ar-js#473]
**Exploring the example:**
https://hiukim.github.io/mind-ar-js-doc/examples/basic
_(Last tested 2023-11-27)_

with iOS and Android there's a difference. The plane is not turned in the correctly for iOS while Android is working properly, see pictures:

**Android:**
![telegram-cloud-photo-size-4-5992265099693375305-y](https://github.com/hiukim/mind-ar-js/assets/50398514/de35cd87-8c2d-4422-9649-6d5fd36d2012)

**iOS:**
![telegram-cloud-photo-size-4-5992265099693375304-y](https://github.com/hiukim/mind-ar-js/assets/50398514/d8a5386e-640e-4e8d-8dab-503364b15110)

This most likely cause some follow up bugs which is why I noticed it in the first place.

**Comment by JakobHakansson** [comment]
**Update:**
Tested different versions to see where the breaking change occurred:
1.1.5 - Works ✅ 
1.2.0 - Works ✅ 
1.2.1 - Does not work ❌ 
1.2.2 - Does not work ❌ 
1.2.3 - Does not work ❌

**Comment by JakobHakansson** [comment]
Seems like the version for:
- imageTargetSrc
- img card src
Causes the issue.

Using MindAR 1.1.5 with:
`https://cdn.jsdelivr.net/gh/hiukim/mind-ar-js@1.1.5/examples/image-tracking/assets/card-example/card.mind;`
`https://cdn.jsdelivr.net/gh/hiukim/mind-ar-js@1.1.5/examples/image-tracking/assets/card-example/card.png`
Works ✅ 

Using MindAR 1.2.3 with:
`https://cdn.jsdelivr.net/gh/hiukim/mind-ar-js@1.2.2/examples/image-tracking/assets/card-example/card.mind;`
`https://cdn.jsdelivr.net/gh/hiukim/mind-ar-js@1.2.2/examples/image-tracking/assets/card-example/card.png`
Does not work ❌  (this is what the example on the website uses)
Using MindAR 1.2.3 with:
`https://cdn.jsdelivr.net/gh/hiukim/mind-ar-js@1.2.3/examples/image-tracking/assets/card-example/card.mind;`
`https://cdn.jsdelivr.net/gh/hiukim/mind-ar-js@1.2.3/examples/image-tracking/assets/card-example/card.png`
Does not work either ❌ 

I think this is the reason? @hiukim

**Comment by JakobHakansson** [comment]
Update:
Using Mind-AR 1.2.3 I can get it to work with
```
https://cdn.jsdelivr.net/gh/hiukim/mind-ar-js@1.2.0/examples/image-tracking/assets/card-example/card.mind;
https://cdn.jsdelivr.net/gh/hiukim/mind-ar-js@1.2.0/examples/image-tracking/assets/card-example/card.png
```
Version above seems to be broken. Suspect it's the .mind file?

**Comment by hiukim** [comment]
I'm not entirely sure. I guess the important question is:

does the latest mindar version works with the .mind file given in the latest cdn version?

I guess if the .mind file given in cdn 1.2.0 works, then we can assume the older .mind file is somehow outdated (I kind of forgot)

**Comment by JakobHakansson** [comment]
I haven't reviewed 1.2.4 or 1.2.5 since they were release today and yesterday. But when using 1.2.3 this caused for the issue mentioned before. My assumption is that the .mind for the other versions than 1.2.0 was broken. It works well with a newly generated .mind file on its own. And that's the important part!
