### ISSUE TITLE
Issue with fullscreen?

### ISSUE THREAD

**Issue by nooberjones** [hiukim/mind-ar-js#481]
When I tap on full screen I get a black screen. Nothing in it.

**Comment by ifly-leonard** [comment]
I think what you're toggling is the "VR" option. 

(I might be wrong, just discovered this tool today, but I've been working with AR.js for a while, so thought I'll just share something I knew)

You can try toggling full screen manually. Tested, it worked for me locally. 

For Mac: `Press Control + Command + F`
For Windows: `Press F11`

Via code, you can try: 

![image](https://github.com/hiukim/mind-ar-js/assets/29737466/91f6bb50-a19a-4ade-afaf-5dfac8fdaa62)
