### ISSUE TITLE
v1.2.5 could not open camera

### ISSUE THREAD

**Issue by jamess922** [hiukim/mind-ar-js#490]
Tried with the examples from image-tracking and face-tracking，don't know why could not open the camera
![20240125225738](https://github.com/hiukim/mind-ar-js/assets/28625879/1a1fbf3c-0907-407d-b8bb-0ec0340e422e)

**Comment by hiukim** [comment]
can you check console logs

**Comment by jamess922** [comment]
![2024-01-26 221851](https://github.com/hiukim/mind-ar-js/assets/28625879/1802444b-27dc-440e-919e-66a3bd221ba8)
example2.html shows this

**Comment by jamess922** [comment]
![2024-01-27 081850](https://github.com/hiukim/mind-ar-js/assets/28625879/1a7a2061-721c-4a57-a618-a2fdda451081)
three.html shows this   and tried to add ./  or ../ not working
![Uploading 2024-01-27 082006.jpg…]()

**Comment by jamess922** [comment]
![Uploading 2024-01-27 082006.jpg…]()

**Comment by hiukim** [comment]
does our live examples working for you? https://hiukim.github.io/mind-ar-js-doc/face-tracking-examples/minimal/

**Comment by jamess922** [comment]
Yes your live example is working for me ，and tried in local also working
