### ISSUE TITLE
Error compiling fragment (GPU)

### ISSUE THREAD

**Issue by kalwalt** [hiukim/mind-ar-js#5]
Hi @hiukim while i was testing your example https://hiukim.github.io/mind-ar-js/samples/example1.html i receive this error:
```js
gpu-browser.js:14991 Uncaught (in promise) Error: Error compiling fragment shader: Fragment shader compilation failed.
ERROR: 0:2: '' :  integer constant overflow 
ERROR: 0:67: '' :  integer constant overflow 
ERROR: 2 compilation errors.  No code generated.

�
    at WebGLKernel.build (gpu-browser.js:14991)
    at WebGLKernel.run (gpu-browser.js:18496)
    at shortcut (gpu-browser.js:18516)
    at Tracker._combineImageList (tracker.js:334)
    at new Tracker (tracker.js:38)
    at eval (controller.js:84)
```
of course nothing can be tracked or displayed...
Maybe my Android device is not supported? i tested with a Wiko View with Android 7.1.2 but i will test with another device. 
EDIT: tested on Chrome browser 86.04240.110

**Comment by hiukim** [comment]
Whenever you see "WebGLKernel", it's from the underlying gpu.js. I have experienced different behaviours in different devices with this library. I have tested with all my available devices and fixed a lot of things. Unfortunately, it's really hard to debug without the actual devices.

**Comment by kalwalt** [comment]
@hiukim `Whenever you see "WebGLKernel", it's from the underlying gpu.js.` i supposed this. Probably this is caused because my device (it is an Adreno CPU) does not support high precision float? I will investigate this.

**Comment by hiukim** [comment]
@kalwalt  thx a lot.

Please noted that I'm using a custom branch of gpu.js instead of their current master. They are basically the same, but have one line difference here:    https://github.com/hiukim/gpu.js/blob/1ab9497dfd05fdc9e62ea599adc6efb51abedbcd/src/backend/gl/kernel.js#L33

It's to temporarily suppress an issue found in ios: https://github.com/gpujs/gpu.js/issues/632

**Comment by kalwalt** [comment]
ok understood, look this is the device specipication: https://www.devicespecifications.com/en/model-cpu/fa444577

**Comment by hiukim** [comment]
I guess you can try running the gpu.js examples with your devices and see if they works first.

gpu.js basically translate the js code into shader programs in webgl and reformat the result back. My experience is that most of the issues come from the js code failed to translate or the translated shader programs run differently in different devices.

The proper fix is probably figuring out what's wrong and fixing the gpu.js. That's the final move and can fix anything, but hard to do.

Sometimes I just do trial and error and see which lines of js code caused the problem, and rewrite it in some other ways hopefully to bypass the problems.

**Comment by kalwalt** [comment]
> I guess you can try running the gpu.js examples with your devices and see if they works first.
> 
> gpu.js basically translate the js code into shader programs in webgl and reformat the result back. My experience is that most of the issues come from the js code failed to translate or the translated shader programs run differently in different devices.
> 
> The proper fix is probably figuring out what's wrong and fixing the gpu.js. That's the final move and can fix anything, but hard to do.
> 
> Sometimes I just do trial and error and see which lines of js code caused the problem, and rewrite it in some other ways hopefully to bypass the problems.

If i have time i will try the gpu.js examples, just to understand which code run or not. I had also to debug the error, i will try when i have a bit of time. Thank you for the answer and support! :smile:

**Comment by hiukim** [comment]
no problem. whenever you have time. Feel free to let me know if you encountered any troubles.

**Comment by subjectdenied** [comment]
same here, doesnt work on android 10 samsung s10e

**Comment by kalwalt** [comment]
@subjectdenied which error do you receive? 
@hiukim i tried the gpu.js examples and i got the same result, i have the suspect that my Gpu is not supported. 
GPU: Adreno (TM) 308 with OpenGLES 3.0

**Comment by subjectdenied** [comment]
it hangs at the "loading" for an example in example2, the error is about "precission missing"

Uncaught (in promise) Error: precision missing
    at lookupKernelValueType (webpack:///./node_modules/gpu.js/dist/gpu-browser.js?:13365)
    at Function.lookupKernelValueType (webpack:///./node_modules/gpu.js/dist/gpu-browser.js?:14602)
    at WebGLKernel.setupConstants (webpack:///./node_modules/gpu.js/dist/gpu-browser.js?:14908)
    at WebGLKernel.build (webpack:///./node_modules/gpu.js/dist/gpu-browser.js?:14944)
    at WebGLKernel.run (webpack:///./node_modules/gpu.js/dist/gpu-browser.js?:18496)
    at Detector.shortcut [as inputKernel] (webpack:///./node_modules/gpu.js/dist/gpu-browser.js?:18516)
    at Detector.detect (webpack:///./src/image-target/detectorGPU/detector.js?:149)
    at Controller.dummyRun (webpack:///./src/controller.js?:100)
    at NewSystem._startAR (webpack:///./src/aframe.js?:147)`

`

**Comment by hiukim** [comment]
@subjectdenied Can you try some examples from gpu.js? https://gpu.rocks/#/examples

**Comment by subjectdenied** [comment]
i tried some, they seem to work fine, with the exception of "video convolution", where the first canvas shows only black on my phone. however there is no error in the console

**Comment by hiukim** [comment]
I don't really have much idea now. Most of the time when it involves gpu.js, I need to tweak the code line of by line and see what triggers the error.

**Comment by kalwalt** [comment]
Testing in firefox. It doesn't works but i receive a bit different message:

```js
unreachable code after return statement
mindar.prod.js:9077:4
Use of the motion sensor is deprecated. mindar.prod.js line 547 > eval:65126:11
Use of the orientation sensor is deprecated. mindar.prod.js line 547 > eval:85127:11
video ready... 
<video autoplay="" muted="" playsinline="" style="position: absolute; top:…0.667px; height: 518px;" width="640" height="480">
aframe.js:71:17
unreachable code after return statement
mindar.prod.js line 558 > eval:9077:4
WebGL warning: drawArraysInstanced: Drawing to a destination rect smaller than the viewport rect. (This warning will only be given once) mindar.prod.js line 558 > eval:15136:8
Uncaught (in promise) Error: Error compiling fragment shader: Fragment shader compilation failed.
ERROR: 0:2: '' :  integer constant overflow 
ERROR: 1 compilation errors.  No code generated.

    build webpack:///./node_modules/gpu.js/dist/gpu-browser.js?:14991
    run webpack:///./node_modules/gpu.js/dist/gpu-browser.js?:18496
    shortcut webpack:///./node_modules/gpu.js/dist/gpu-browser.js?:18516
    detect webpack:///./src/image-target/detectorGPU/detector.js?:149
    dummyRun webpack:///./src/controller.js?:100
    Aframe 40
mindar.prod.js line 558 > eval:14991:13
Errore mapping di origine: Error: NetworkError when attempting to fetch resource.
URL risorsa: webpack:///./node_modules/aframe/dist/aframe-master.js?
URL mapping di origine: aframe-master.js.map
```

**Comment by hiukim** [comment]
@subjectdenied @kalwalt 

I have just finished a big revamp, removing GPU.js completely. Hopefully it will solve a lot of these problems.

If you guys could try the example again with your devices (whatever devices you have, haha), that would be nice!

https://hiukim.github.io/mind-ar-js/samples/example1.html

**Comment by kalwalt** [comment]
Dejar @hiukim i will try for sure! 🙂🎉😉

**Comment by kalwalt** [comment]
I tested the new version but i got an error see #10.
