### ISSUE TITLE
How to select camera when you have

### ISSUE THREAD

**Issue by jamess922** [hiukim/mind-ar-js#50]

**Comment by jamess922** [comment]
Now phones  have three or four cameras，is there a way to choice camera ？

**Comment by hiukim** [comment]
Unfortunately, there is no way to do that right now. 

I guess it's mostly for switching between front and back camera, right?

**Comment by jamess922** [comment]
Actually It's between back cameras ，i tried with my Huawei P40 ，it have three back cameras，and open with telephoto camera  ，not the main camera

**Comment by hiukim** [comment]
@jamess922 
I'm not sure how to select the correct camera and I don't have a device to test that. Right now, I'm just doing

```
navigator.mediaDevices.getUserMedia({audio: false, video: {
    facingMode: 'environment',
}})
```

Maybe you can try to see what changes are required first?

**Comment by akhrarovsaid** [comment]
Hey @jamess922 ,

You can choose the device used to capture a stream via the navigator.getUserMedia.enumerateDevices API (See the [spec](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/enumerateDevices)). What you'll notice is that the output is a list of device ID's. You can request a device ID in the navigator.getUserMedia call parameters. 

However, I don't believe there is a way to specifically access a particular camera device. If memory serves, then the actual environment you get is what the browser considers 'ideal' at the time. Hope this helps!

Cheers
