### ISSUE TITLE
unexpected identifier

### ISSUE THREAD

**Issue by marcusx2** [hiukim/mind-ar-js#53]
Trying the facetracking examples, I get this message
![image](https://user-images.githubusercontent.com/5656275/136102477-cd2e8676-9f59-46a4-a904-201b796089c1.png)

In the source code there are lines like 
<script src="../../dist-dev/mindar-face.js"></script>

But the folder dist-dev doesn't exist, nor does the file mindar-face.js. The folder that exists is just "dist" and the file is "mindar-face.prod.js". Even changing these things I still get the error. Would love to try out the facetracking, but I can't get it to work.

**Comment by hiukim** [comment]
@marcusx2 I'm writing up the documentation for face tracking at the moment. Will be ready soon!

**Comment by marcusx2** [comment]
Can you leave a "try it yourself" face tracking in the main page as well? Also, shouldn't the example folder work out of the box? Did I do something wrong? I just served the folder with https.

**Comment by hiukim** [comment]
done

**Comment by hiukim** [comment]
@marcusx2 sorry, it's a typo. should be https://cdn.jsdelivr.net/gh/hiukim/mind-ar-js@1.0.0/dist/mindar-face-aframe.prod.js
