### ISSUE TITLE
feature request: marker based ar

### ISSUE THREAD

**Issue by marcusx2** [hiukim/mind-ar-js#55]
Something [like this](https://ar-js-org.github.io/AR.js-Docs/marker-based/).

**Comment by Blackclaws** [comment]
The problem is that normal image tracking is much less stable especially on longer distances. If you have a multitude of markers that you want to use to create content at the same time NFT is rather slow. Markers can usually be read over a longer distance.

**Comment by marcusx2** [comment]
So then let's have marker based ar as well! Hahaha

**Comment by nicolocarpignoli** [comment]
In my opinion, I agree with @Blackclaws and markers still have their own sense for performances and tracking stability, even if Mind-arjs image tracking is already great.
Anyway, I do not know if this is the best feature where to carry efforts: I mean, what are the most used type of AR today?

- Markerless (aka plane tracking)
- Image tracking (already on mindarjs)
- Location based? (could be ported from AR.js)
- Marker based

I think (personally) that markers are a subset of image tracking, with some enhancements but also bigger limitations.
If I'd have to choose, I will not go for markers as first next thing to add but rather on Markerless. Just my opinion looking at the current market situations and other paid libraries like 8thWall.
