### ISSUE TITLE
feature request: using mind-ar with native threejs (without a-frame)

### ISSUE THREAD

**Issue by ThorstenBux** [hiukim/mind-ar-js#56]
Hi Hiukim,

could you maybe provide an example on how to use mind-ar with just vanilla threejs. That would be awesome. Thank you

**Comment by akhrarovsaid** [comment]
Hey @ThorstenBux ,

I recently integrated ThreeJS + React + MindAR using a Context Provider. I did this, however, before the last major release. The code is essentially just a rewrite of the aframe wrapper in the src. Let me know if you'd like to know more - I'd be happy to run you through the process.

Cheers

**Comment by hiukim** [comment]
@ThorstenBux Yes, I'm working on it, but probably need a bit more time.  Need to make the API right before officially releasing something, otherwise it will be hard to maintain in the long run, or break backward compatibility.

**Comment by gjcope** [comment]
Great project! Interested in this feature as well.

**Comment by hiukim** [comment]
@ThorstenBux @akhrarovsaid 

threejs integration is added in latest release. You can check out this installation guide: 

https://hiukim.github.io/mind-ar-js-doc/installation

and a quick example:

https://hiukim.github.io/mind-ar-js-doc/more-examples/threejs-image
