### ISSUE TITLE
Unable to run image tracking demo in 1.0.0

### ISSUE THREAD

**Issue by jonomatusky** [hiukim/mind-ar-js#57]
I copied the example code here: https://hiukim.github.io/mind-ar-js-doc/quick-start/overview

When I ran it, I initially received crossorigin errors but fixed them by adding crossorigin="anonymous" to the scripts.

Now I'm seeing: 

GET https://cdn.jsdelivr.net/gh/hiukim/mind-ar-js@1.0.0/dist/mindar-image.aframe.js net::ERR_ABORTED 404

Seems it's unable to load the mind ar a-frame resource? 

Love the tool. Can't wait to try this new version. Thanks!

**Comment by hiukim** [comment]
@jonomatusky sorry, it's a typo.

should be `https://cdn.jsdelivr.net/gh/hiukim/mind-ar-js@1.0.0/dist/mindar-image-aframe.prod.js`
