### ISSUE TITLE
can not open camera in android edge browser 

### ISSUE THREAD

**Issue by chenleicrm** [hiukim/mind-ar-js#59]
can not open camera in android edge browser . app version is 96.0.1043.0 and its ok in old version of edge.

**Comment by chenleicrm** [comment]
just open the demo link **https://hiukim.github.io/mind-ar-js-doc/samples/basic.html**  in edge browser, already get the camera permission, but can not open the camera and the whole screen is white --

**Comment by maurosala** [comment]
The problem is still here. On edge browser the page remain white.
