### ISSUE TITLE
Image targets need to be square

### ISSUE THREAD

**Issue by spotd** [hiukim/mind-ar-js#6]
It tracks the marker at index 0 perfectly. But any other index doesn't work. 
Strangely i can reorder the markers when making it, and it is always the one at 0 that functions as expected. So its not the image that is the issue here.

Just downloaded your latest to double check (as i had made changes), but still the same behaviour.

**Comment by spotd** [comment]
I can see yours runs 2 markers ok, but i have one with 7, and only ever uses one at position 0. So I am wondering if its the make up of the .mind file itself?

**Comment by spotd** [comment]
Do all images need to be same dimensions?

**Comment by spotd** [comment]
Ok i letterboxed the images with black to make square 800 x 800 images and it now works. So that must be it

**Comment by hiukim** [comment]
I don't remember it needs to be same dimensions. But I need to double check.

**Comment by hiukim** [comment]
but it definitely doesn't need to be square.

**Comment by spotd** [comment]
Its a great project this btw... runs smoother for me than AR js. 
Maybe they just need to be the same dimensions. As before i had all with different heights. That caused index 0 to only work

**Comment by hiukim** [comment]
thx. It's good to know. Let me double check with that.
