### ISSUE TITLE
Video not showing, not playing

### ISSUE THREAD

**Issue by brandon-verastegui** [hiukim/mind-ar-js#64]
Hi, I've done everything to try to make a video appear and play efficiently, I was able to see a little bit of it but only when the video was just too big to be completely shown.
What is the right way to code it?

      <a-scene mindar-image="imageTargetSrc: ./SSS-target.mind" vr-mode-ui="enabled: false" device-orientation-permission-ui="enabled: false" color-space="RGB" renderer="colorManagement: true, physicallyCorrectLights">
``
<a-camera position="0 0 0" look-controls="enabled: false"`
<a-cursor></a-cursor></a-camera>
``
<a-light type="ambient" intensity="1"></a-light>
``
<a-assets>
<video id="SSS-video"
        preload="auto"
        autoplay loop="true" crossOrigin="anonymous" muted
        src="https://www.v4verastegui.com/mindar-project/Scottmillersss.mp4" controls>
      </video></a-assets>
``
<a-entity mindar-image-target="targetIndex: `0">`
<a-video src="#SSS-video"  position="0 0 .05" width=".96" height=".54" rotation="0 0 0" preload="auto" `></a-video>`
<a-image id="background" src="topshapeandbackground.png" opaciy="0.5" position="0 0 0" height="1.3145" width="1" rotation="0 0 0"></a-image>
``
</a-entity>
</a-scene>
</body>
</html>

**Comment by hiukim** [comment]
Does it work without MindAR? I mean as a regular aframe application?
