### ISSUE TITLE
Define hidding time of a-entity after "targetLost"

### ISSUE THREAD

**Issue by abundis-rmn2** [hiukim/mind-ar-js#65]
Hello guys, before starting the text I would like to congratulate you for the excellent work developing the library. Congratulations!

I set up an augmented reality timeline that has around 44 bookmarks with another application (OpenSpace3d), the problem came with registering the app in the playstore and the lack of interest from users to download them, so I decided to reprogram it now with mindAR. Just to show off I leave you a picture :)

![image](https://user-images.githubusercontent.com/67477259/138384180-3d7d2d2e-0a96-4493-a09e-34205fe46636.png)

Returning to the topic of the thread. Would you like to see if it is possible to define the time it takes for the a-entity to disappear once the target is lost?

![image](https://user-images.githubusercontent.com/67477259/138384552-6d30622d-490b-4809-8c25-2d04bc55ea38.png)

clickMe.addEventListener("targetLost") takes about 8 seconds after the marker is no longer in front of the camera to log it to the console. I don't know if it is a tolerance that can be defined in the a-scene attribute or if I could make a direct modification to the core of the library to short that tolerance time.

Greets, Angel

PS. Sorry for the funny english.
PS. You can check the web version of that linetime at https://rmn2.com/graffiti-gdl/recorriendo-el-trazo/

**Comment by ayalantonovdev** [comment]
Has anyone solved this problem?
I think that when there is no image, the scene should immediately disappear. it just doesn't look pretty.
please tell me how can i change targetlost delay

**Comment by hiukim** [comment]
added in the latest release. Check out this documentation: https://hiukim.github.io/mind-ar-js-doc/quick-start/tracking-config
