### ISSUE TITLE
Website (WebAR) collapsed (error 404-500) server update?

### ISSUE THREAD

**Issue by brandon-verastegui** [hiukim/mind-ar-js#68]
Hi, my website collapsed after requesting Byte-Range, later they said that the system error log pointed at one of mind-ar-image-tracking libraries gave: "Uncaught TypeError: systems[e] is not a constructor at HTMLElement.value"

Has this happened before to anybody? is there any suggestions on how to have my website back online by fixing this error?

It all happened because I was trying to make videos show through IOs devices, it all was working on android.

Thanks.

![Capture211189](https://user-images.githubusercontent.com/61775457/139553844-0b1deb6f-7c96-4fd9-80e1-b494421b6fa9.png)

**Comment by hiukim** [comment]
Does it happen on the provided examples? or only on your applications?

If it's the latter, a minimal example would be helpful to debug.
