### ISSUE TITLE
[feature request] AR Camera GYRO

### ISSUE THREAD

**Issue by marcusx2** [hiukim/mind-ar-js#69]
With the gyroscope alone, it's possible to do something [like this](https://www.youtube.com/watch?v=8etGUUtLoJY&ab_channel=MakakaGames%3AMadewithUnity). I have no idea how. But I suppose it works by placing the objects around the camera, and use the gyroscope to keep them on a more or less fixed position. Can mind-ar-js implement this feature?

**Comment by hiukim** [comment]
with gyroscope alone, seems hard to stick to the ground.  will at least need some kind of plane detection and tracking maybe?

**Comment by marcusx2** [comment]
No, I confirmed with the author that's it's just the gyroscope. There is no slam or anything. You can see that the objects drift a bit. Still, it's good enough for a number of use cases.

**Comment by marcusx2** [comment]
@hiukim Do you have an idea how to do it? Do you use Unity?

**Comment by hiukim** [comment]
@marcusx2 That's very interesting.  But it seems like it can detect the floor, judging from the shadows?

**Comment by marcusx2** [comment]
It doesn't detect the floor, the shadows is just an effect. There is no floor detection at all. Nothing. It's just the gyroscope.
