### ISSUE TITLE
Enhancement: Gyro take over

### ISSUE THREAD

**Issue by spotd** [hiukim/mind-ar-js#7]
If you give me a few pointers to start, I will look at making Gyroscope take over when marker is lost for a limited time.

**Comment by hiukim** [comment]
that would be interesting! As a site note, I'm always thinking about using the gyroscope to enhance tracking. Now the tracking algorithm is mostly based on matching point in similar locations in the previous frame. I'm sure the gyroscope data can give an expected locations that can help the search.

But anyway, that could be the next step. One easy start for your proposal is to look at `src/aframe.js`. This wrapped up the dirty work so you don't find too daughting at first. This line might be a good start:

https://github.com/hiukim/mind-ar-js/blob/7fa1c67b4b07a47394ba86e0cbb0ae320f4ea8ff/src/aframe.js#L206

When the marker is lost, `worldMatrix` would return null. You might be able to take over here with gyroscope. I guess the work is to continue estimate the worldMatrix here.

**Comment by spotd** [comment]
Great thanks.. already in that function as the hook for other stuff. I'll let you know how i get on!

**Comment by hiukim** [comment]
cool. thx. I really like this enhancement!  Once we are able to correlate the worldMatrix with gyroscope data, we can definitely use this to improve the tracking.

**Comment by Arvrairobo** [comment]
@spotd how did it go for you? would you be able to do with gyro take over?
