### ISSUE TITLE
dynamically create AR scene? (Javascript)

### ISSUE THREAD

**Issue by sabuone** [hiukim/mind-ar-js#70]
First of, thank you so much for open such a good library.

While using your library, there are times when you have to dynamically designate model information and location, but is there a way to manipulate this with JavaScript?

**Comment by hiukim** [comment]
I think you can do something similar by scripting aframe component: https://aframe.io/docs/1.2.0/introduction/javascript-events-dom-apis.html

I'm also working on a three.js interface, that would allows greater flexibility.
