### ISSUE TITLE
Module not found: Error: Can't resolve 'mind-ar' in 'C:\Users\PC\Desktop\Task\Booking\booking\src'

### ISSUE THREAD

**Issue by UtilExe** [hiukim/mind-ar-js#74]
Hi,

After using the module with npm:
https://www.npmjs.com/package/mind-ar

And importing it to my project through this:
import 'mind-ar';
The error comes up:
Module not found: Error: Can't resolve 'mind-ar' in 'C:\Users\PC\Desktop\Task\Booking\booking\src'

Please note, it only happens with this particular npm module.
Note: Using VUE
@hiukim  - Thanks in advance!

**Comment by hiukim** [comment]
can you screencap your ./node_modules directory?
