### ISSUE TITLE
Is there a way to show multiple 3D images on top of each other?

### ISSUE THREAD

**Issue by UtilExe** [hiukim/mind-ar-js#75]
Is there a way to show multiple 3D images on top of each other, once scanning the target image?

If so - is there any reference/examples/hints to do so?

Thanks in advance! And thanks to @hiukim for your great work!

**Comment by UtilExe** [comment]
Update - I actually found my own answer. It was quite easy, so good job to the library author!

For people with same issue:
Just add multiple image ids:
<img id="card" src="./photo1.png" />
<img id="card2" src="./photo2.png" />

 <a-plane src="#card" position="0 0 0" height="0.552" width="1" rotation="0 0 0"></a-plane>
 <a-plane src="#card2" position="1 0 0" height="0.952" width="1" rotation="0 0 0"></a-plane>

**Comment by gabdanGraldev** [comment]
i have the same problem but i can't solve it.
If I insert two 3d model in the html I only see one.
