### ISSUE TITLE
Can't disable Blue Loading Screen

### ISSUE THREAD

**Issue by ltsfwrs** [hiukim/mind-ar-js#77]
Hey,

how to disable the Blue Loading Screen with the three dots and the two blue boxes?

Thank you!

**Comment by jonomatusky** [comment]
That's the A-frame loading screen. You can change it to an all-black screen by adding `loading-screen="backgroundColor: black"` to the `a-scene` element or disable it entirely with `loading-screen="enabled: false"`. More info here: https://aframe.io/docs/1.2.0/components/loading-screen.html

**Comment by ltsfwrs** [comment]
Thank you **so** much!
