### ISSUE TITLE
Device issue - Failed to launch

### ISSUE THREAD

**Issue by UtilExe** [hiukim/mind-ar-js#78]
Anyone used Mind-AR and AFrame on a phone? With the most basic examples, I'm getting an error that the device/browser is not compatible. 
Tried with an iPhone 12 & SE, and in Chrome/Safari. 

I tried with for example this basic example:
https://hiukim.github.io/mind-ar-js-doc/quick-start/overview

![image](https://user-images.githubusercontent.com/4083129/142772299-db0f75e6-a228-4db8-b1b7-337f1e6d728c.png)

**Comment by UtilExe** [comment]
@hiukim

**Comment by hiukim** [comment]
what's the iOS version? @UtilExe

**Comment by UtilExe** [comment]
iOS 14 @hiukim and also tested on a device with iOS 15.1 (up to date/latest), so that shouldn't be the issue.

**Comment by hiukim** [comment]
@UtilExe Does it work on the hosted version instead of localhost? e.g. https://hiukim.github.io/mind-ar-js-doc/samples/minimal.html

**Comment by UtilExe** [comment]
It works on your version.

Therefore, I tried to set it up to production, and it seems like it solved it! The conclusion is that it requires a HTTPS/SSL certificate, just for info. Probably an Apple/iPhone security thing when accesing the camera.

Thanks for the help @hiukim
