### ISSUE TITLE
Special characters / Letters / UTF-8

### ISSUE THREAD

**Issue by UtilExe** [hiukim/mind-ar-js#79]
Hi!

Using Image Tracking, I'm displaying a text above the image.

My issue is that special characters (for example Danish/specific UTF-8 letters) are not displaying. They are just completely ignored.

Example:
`<a-text position="-0.5 1.3 0" value="Øresund" color="red"></a-text>`
The title will just be:
"resund" instead of "Øresund". 

I declared the page with:
`<meta charset="utf-8" />
`
Do you know if there's a work-around for this, @hiukim?

**Comment by Tashows** [comment]
@UtilExe Did you solve this somehow? Facing the same issue with Greek characters.

**Comment by Tashows** [comment]
Found the solution here: https://github.com/etiennepinchon/aframe-fonts/issues/1
