### ISSUE TITLE
Can i use the Event Handing just to show or hide my assets? Don't have to follow the target

### ISSUE THREAD

**Issue by szYuan** [hiukim/mind-ar-js#80]
Hi, HiuKim.
I'd like to show a 3D model or image when target found, but no need to attach with the target.
I tried to put a `<a-plane>` inside the `<a-scene>`, but it didn't shown.
```
<a-scene id="scene-1" ... >
      <a-assets>
        <a-asset-item id="body2" src="" ...>
      </a-assets>
      <a-camera id="camera" position="0 0 0" look-controls="enabled: false"></a-camera>
      <a-entity id="front-ent" class="mindar-ent" mindar-image-target="targetIndex: 0">
        <a-gltf-model ...>
      </a-entity>

      <a-plane position="0 0 -4" rotation="-90 0 0" width="4" height="4" color="#7BC8A4"></a-plane>
 </a-scene>
```
How to modify the code to get what i expect? Thanks

**Comment by hiukim** [comment]
In that case, maybe you can just create an empty mind-image-target entity and capture the targetFound event, and then set visibility of another entity.

**Comment by szYuan** [comment]
> In that case, maybe you can just create an empty mind-image-target entity and capture the targetFound event, and then set visibility of another entity.

yes, that what i tried to do, but i can't make the another entity visible. 
When mind-ar was ready, the `<a-gtlf>` disappeared:
```
<a-scene mindar-image="imageTargetSrc: target.mind; autoStart: false; maxTrack: 2" ...>
    <a-camera id="camera" position="0 0 0" look-controls="enabled: false"></a-camera>
    <a-entity id="front-ent" class="mindar-ent" mindar-image-target="targetIndex: 0">
        [empty mind-image-target entity]
    </a-entity>
    <a-gltf-model  src="#body2"></a-gltf-model>
</a-scene>
```

**Comment by hiukim** [comment]
@szYuan 
top of my head, I guess because mindar updated the camera pose, so you model is not in front of the camera anymore.  Try putting the model inside the camera entity, as its child.  It's an hack. It might work I'm not sure.

**Comment by szYuan** [comment]
thx~
