### ISSUE TITLE
event targetLost problem

### ISSUE THREAD

**Issue by ayalantonovdev** [hiukim/mind-ar-js#81]
event targetLost delay is doesn't look pretty.
when I link a video to an image, it does not disappear with it.

**Comment by hiukim** [comment]
Hi, I'm aware of this. There is a PR about this: https://github.com/hiukim/mind-ar-js/pull/84

I didn't have time to look into it and merge it yet. You can use his branch temporarily if needed.

**Comment by hiukim** [comment]
A few tracking config parameters are added in latest release. check here:

https://github.com/hiukim/mind-ar-js/blob/23e505d98e8dc5c8c0a791502b3425b1ae2b609d/examples/image-tracking/example4.html#L28

default should be
```
interpolationFactor: 5; warmupTolerance: 5; missTolerance: 5
```
