### ISSUE TITLE
How to get the mark targets' position?

### ISSUE THREAD

**Issue by DivoWu** [hiukim/mind-ar-js#85]
Thank you for sharing this great work!

I tried to get the position of the marker in the targetfound event. But I got a zero value Vector3(0,0,0)
Below is my code:

> marker.addEventListener('targetFound', (e) => {
>     let pos = marker.object3D.position;
> // all marker targets position are zero
> }

Has any way to get the position? 

Thank you!

**Comment by hiukim** [comment]
top of my head, I'm not sure.  maybe it's not yet updated on targetFound. try get it 0.01 seconds later

**Comment by DivoWu** [comment]
Yes, it has delay on targetFound.
I had get the position on aframe tick function.

Thanks for your reply.
