### ISSUE TITLE
Click on specific target?

### ISSUE THREAD

**Issue by UtilExe** [hiukim/mind-ar-js#86]
Hi @hiukim  (and everyone else)

Working with image tracking, I'm trying to achieve that once you click on one of the images that appear after scanning the target images, it must pop up with a alert.

I tried to use https://hiukim.github.io/mind-ar-js-doc/examples/events-handling

However the thing is that I have multiple images and IDS, so any idea how to make it flexible without a querySelector on each ID?

**Comment by brunoshine** [comment]
Hi all,

I'm also unable to trigger the click event. Any thoughts?
thanks
