### ISSUE TITLE
How to trigger targetFound again after unpause or stop?

### ISSUE THREAD

**Issue by szYuan** [hiukim/mind-ar-js#87]
expect: 
video feeding -> **targetFound** -> pause -> [environment remains unchanged]-> unpause -> **targetFound**

current situation:
After unpause, the targetFound never triggered until i move the target outside the camera to trigger targetLost event.

attempt:
1. i called `arSystem.stop` and `arSystem.start()`，the `.mind` file was reloaded, but the targetFound won't be triggered.
1. i used` jQuery.trigger` to trigger `targetFound` from outside after unpause, didn't work....

**Comment by hiukim** [comment]
Your use case seems pretty tricky. I'm not sure a `targetFound` event firing after `unpause` should be the expected behaviour.
