### ISSUE TITLE
image-tracking and Intereactive video

### ISSUE THREAD

**Issue by wduo** [hiukim/mind-ar-js#88]
This is a great code repository! In addition, can you provide the code for the effect shown in the figure below? That would be greatly appreciated.
![image](https://user-images.githubusercontent.com/19623177/144975999-604f310b-02b4-4109-a888-3ffd2ecb2041.png)

**Comment by wduo** [comment]
@hiukim I would also like to ask, can I use some cv algorithms for detection?

**Comment by hiukim** [comment]
@wduo I'm not sure I understand the questions.

What effect are you referring to?

and what do you mean by using some "cv" algorithms for detection?

**Comment by wduo** [comment]
Hi, @hiukim The effect I am talking about refers to: pop-up card, pop-up 3D model, pop-up video (click to play this video), pop-up the 4 icons below. I only found html sample codes for pop-up cards and pop-up 3D models. Can you provide the complete code for the effect shown in the above gif animation? Thank you so much.

**Comment by hiukim** [comment]
@wduo "view-source:https://hiukim.github.io/mind-ar-js-doc/samples/advanced.html"

**Comment by wduo** [comment]
@hiukim Great job! very interesting. In addition, I am a computer vision algorithm engineer, can we have some cooperation?

**Comment by hiukim** [comment]
@wduo Definitely! I'm looking for some help with computer vision in the feature tracking part. Do you think you have some time to take a look and provide some advices?
