### ISSUE TITLE
AR Content is clipped, modifying camera clipping plane doesn't change anything

### ISSUE THREAD

**Issue by Aupuma** [hiukim/mind-ar-js#89]
Hi! I'm using this amazing library to build an AR business card for myself! After testing for a while, if I the mobile is 14-15cm away from the target, the 3D content is clipped, and changing the camera far clipping plane to a bigger value doesn't affect anything, you can see that the legs of my 3d model are disappearing

![Screenshot_20211208-134306](https://user-images.githubusercontent.com/22346231/145210704-9d8cfb41-148a-4f38-a99e-85fc99df5dc5.jpg)
.

**Comment by hiukim** [comment]
I'm aware of this issue. I will look into it.

**Comment by hiukim** [comment]
@Aupuma should be fixed in the latest release.
