### ISSUE TITLE
about miniprogram

### ISSUE THREAD

**Issue by zero16832** [hiukim/mind-ar-js#90]
can make it support wechat miniprogram?

**Comment by hiukim** [comment]
Do you know whether wechat miniprogram can start webcam? @zero16832

**Comment by zero16832** [comment]
I mean that can make support with wechat?

**Comment by hiukim** [comment]
I understand your question. I'm just wondering if wechat miniprogram can start webcam

**Comment by zero16832** [comment]
Yes,it can start webcam.

**Comment by zero16832** [comment]
@hiukim

**Comment by hiukim** [comment]
@zero16832 Actually I don't know very well about wechat miniprogram. Last time I checked (long time ago), I remembered webcam cannot be started. Maybe it's changed.

What's the easiest way to test it nowadays?

Is there a specific error message you are receiving?

**Comment by lpj716** [comment]
test it，in android wechat，webcam can work fine，but ios can not work

**Comment by lzlandyezi1116** [comment]
> 测试一下，在android微信中，摄像头可以正常工作，但ios不能工作

你好，这个测试在微信小程序是可以用的吗？为什么我引入都报错，看原因还是源码是用了window上面的方法，但是微信小程序是没有去全局window对象
