### ISSUE TITLE
Is it possible to play a video automatically when the target image is detected with no interaction?

### ISSUE THREAD

**Issue by hbaugmentedreality** [hiukim/mind-ar-js#94]
Hi.   First of all, excellent repository and excellent work Hiukim.   
Now... I think my question is more related to aframe.  Do you know if is possible to play a video automatically when the target image is detected with no interaction?
Thanks!

**Comment by RajSriShanker** [comment]
I actually implemented this in my AR example, I first had video assets clarified as such
`<video id="arvideo" autoplay muted webkit-playsinline artoolkit loop="true" src="assets/arvideo.mp4"></video>
`

In this case I have my video auto playing as soon as my marker visible, however for iOS you need to have a interaction for the video to be playing. I tried on several devices and it needs a click before you play the video.

You can perform this by adding these interaction in your script section
```
 // detect target found
     targetMarker.addEventListener("targetFound", event => {
        videoObject.play();      
    });
```

or by
```
      videoObject.addEventListener('click', function(){
        videoObject.play();      
});
```

**Comment by hbaugmentedreality** [comment]
Hi @RajSriShanker .   Thank you for your help.  
Yes, I saw that option but the video that I want to play has also audio and I cannot use "muted".
So, is the only way to click on it to play it?
Thanks!!

**Comment by RajSriShanker** [comment]
Unfortunately, for iOS you have to do a interaction to play the video. Here is the official a-frame documentation for this issue. 
https://aframe.io/docs/1.2.0/introduction/faq.html#why-does-my-video-not-play

However for Android auto-play will function as intended.

**Comment by Sov3rain** [comment]
> Hi @RajSriShanker . Thank you for your help. Yes, I saw that option but the video that I want to play has also audio and I cannot use "muted". So, is the only way to click on it to play it? Thanks!!

In most modern browsers, you'll need to register a "click" event (touch or mouse click) anywhere on the page to be able to play video and/or audio. This is a privacy and security feature.
