### ISSUE TITLE
How to fixed position of object 3D model on image target?

### ISSUE THREAD

**Issue by tienvb-mirabo** [hiukim/mind-ar-js#95]
Hi team, I try test this sample.

[https://hiukim.github.io/mind-ar-js-doc/samples/basic.html](https://hiukim.github.io/mind-ar-js-doc/samples/basic.html)

But when I move camera to left or right, 3D model also moving. Then, it took 1s for back to image target position.

I tried test this scenario with ARjs ( hiro marker), 3D model was fixed position on marker, it didnt move when I move camera to left or right.

how can I fix it with mind-ar-js ?

**Demo with mind-ar-js**

![demo_mindar](https://user-images.githubusercontent.com/58162709/147030157-62bac0b1-274c-45b8-a14b-dc2e91c09288.gif)

**Demo with arjs (hiro marker)**

![demo_arjs](https://user-images.githubusercontent.com/58162709/147030167-ea7618cc-c1f5-42ea-b1f5-9560247467e1.gif)

**Comment by hiukim** [comment]
probably just because the marker lost track.

**Comment by tienvb-mirabo** [comment]
@hiukim thanks for reply.
But Marker still show in camera view, so "targetLost" event isnt  trigger, I dont think marker lost track in that case.

**Comment by hiukim** [comment]
@tienvb-mirabo There is an intentional delay for triggering the "targetLost" event, to make the tracking more tolerant. It's already lost but re-detected again within the tolerance period.

**Comment by tienvb-mirabo** [comment]
@hiukim thanks for your answer. where source I can check for "intentional delay"? I also attached gif file for my question details.

**Comment by hiukim** [comment]
@tienvb-mirabo  Yes, that's the problem I mentioned. 

The sample target image is a bad one actually, so the tracking performance is bad. It will be more stable if you use a better one.

**Comment by hiukim** [comment]
Yes, ar.js hiro marker is very performant. It could reach 60fps easily.  But natural image is different, you can try their example.

**Comment by tienvb-mirabo** [comment]
@hiukim yes, my image target is very simple. I will try another image.
I also tried my image target with Arjs. I think your lib is better than it. Thanks for your help.

**Comment by hiukim** [comment]
@tienvb-mirabo I have written a blog post about picking good target image before. You can check it out if you are interested: https://blog.pictarize.com/how-to-choose-a-good-target-image-for-tracking-in-ar-part-3/
