### ISSUE TITLE
Uncaught ReferenceError: _computeKMedoids is not defined

### ISSUE THREAD

**Issue by mkhennoussi** [hiukim/mind-ar-js#96]
Hi,

Thanks for your work and for this lib ! 

When I follow the installation process from the docs, using npm : 
```
> npm i mind-ar --save
> npm i aframe --save
```

I have this error in the console : 
```
mindar-image.prod.js:2 Uncaught ReferenceError: _computeKMedoids is not defined
    at Object.80723 (mindar-image.prod.js:2)
    at n (mindar-image.prod.js:2)
    at Object.95217 (mindar-image.prod.js:2)
    at n (mindar-image.prod.js:2)
    at Object.57957 (mindar-image.prod.js:2)
    at n (mindar-image.prod.js:2)
    at Object.65260 (mindar-image.prod.js:2)
    at n (mindar-image.prod.js:2)
    at mindar-image.prod.js:2
    at node_modules/mind-ar/dist/mindar-image.prod.js (mindar-image.prod.js:2)
```

Everything is working when I use the HTML scripts : 
```
<script src="https://cdn.jsdelivr.net/npm/mind-ar@1.1.0/dist/mindar-image.prod.js"></script>
<script src="https://aframe.io/releases/1.2.0/aframe.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/mind-ar@1.1.0/dist/mindar-image-aframe.prod.js"></script>
```

The version are the same on npm : 

```
  "dependencies": {
    "aframe": "^1.2.0",
    "mind-ar": "^1.1.0"
  }
 ```
 
 I am using Vite.js vanilla js template. 
 
 Any ideas where this issue comes from ? 
 
 Thanks !

**Comment by hiukim** [comment]
@mkhennoussi Thanks for bringing it up. I haven't had a chance to test out the npm version since last release. Probably something's wrong. I'll check.

**Comment by Blitzy** [comment]
Im having this issue as well, even when I import the JS directly from the CDN:

```js
import 'https://cdn.jsdelivr.net/npm/mind-ar@1.1.0/dist/mindar-image-three.prod.js';
```

![Screen Shot 2022-01-04 at 12 41 54 PM](https://user-images.githubusercontent.com/1583792/148101135-d012cd5f-ee7f-4d40-a591-72a062b16208.png)

**Comment by Blitzy** [comment]
I figured out a workaround by injecting a script element into the page and loading it that way.

```typescript
const script = document.createElement('script');
script.src = 'https://cdn.jsdelivr.net/npm/mind-ar@1.1.0/dist/mindar-image-three.prod.js';

script.onload = (event) => {
    console.log(`script loaded.`, event);
}

document.body.append(script);
```

**Comment by Makio64** [comment]
in src/image-target/matching/hierarchical-clustering.js
_computeKMedoids should be defined before its call in the _build function 
Changing the functions order made it works.
